### ISSUE TITLE
[Panel] Change template option disabled when blueprints don’t include subpages

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1014]
I used the latest Plainkit and nightly build:

After downloading the plainkit, I create two blueprints `default` and `article` with the same fields (except for the title):
```
title: Default Page
sections:
  content:
    type: fields
    fields:
      text:
        label: Text
        type: textarea
```

Although there are multiple blueprints, I cannot change the template of a page in the panel. The option in the settings menu is disabled.

Now I add a pages section to both blueprints:
```
title: Default Page
sections:
  content:
    type: fields
    fields:
      text:
        label: Text
        type: textarea
  pages:
    type: pages
    headline: Pages
```

And now the »Change template« option in the settings menu is enabled.

----

Also: Limiting the pages section to one template disables the option again.
```
...
  pages:
    type: pages
    headline: Pages
    templates:
      - default
```
Adding two templates enables the option again.
```
...
  pages:
    type: pages
    headline: Pages
    templates:
      - default
      - article
```
