### ISSUE TITLE
[Cms] Thumb object return values of the parent image except for url

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1015]
All the properties of a resized image are returning those of the parent image, except the public url.
For example, a thumbnail of a file named _image-1.jpg_ generated with ```resize(150)``` returns:

```
root: >
  /Users/Sylvain/Documents/_dev/docs/content/1_sandbox/image-1.jpg
url: >
  http://docs/media/pages/sandbox/image-1-150x224-q90.jpg
hash: cb0f0e495449941cfd197562f1901725
filename: image-1.jpg
name: image-1
safeName: image-1
extension: jpg
size: 460094
niceSize: 449.31 kB
modified: 2018-09-23T18:19:15+02:00
mime: image/jpeg
type: image
isWritable: true
isReadable: true
dimensions:
  width: 1289
  height: 1923
  ratio: '0.67030681227249'
  orientation: portrait
exif:
  camera:
    make: null
    model: null
  location:
    lat: null
    lng: null
  timestamp: 1537719555
  exposure: null
  aperture: null
  iso: null
  focalLength: null
  isColor: true
header:
```
