### ISSUE TITLE
[Panel] label with string "Y" unexpected

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1024]
`label: Y` will show `true` as label. `Y` was expected.
`label: N` will show `` (nothing) as label. `N` was expected.
using `label: "Y"` fixes this. when fixing this issue please check for other bool parsing like when using `0`, `1`, `N` as label.

```yaml
why:
    label: Y
    type: text
    default: is this label "true"
```
