### ISSUE TITLE
Files section: Uploads to wrong page when parent option is used

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/kirby#1025]
For testing, I used the following section in the `home` blueprint of the Starterkit:

```yaml
files:
  type: files
  parent: site.find('projects/oceans-are-quite-nice')
```

The files are displayed correctly, but if I upload a new file to that section, it gets uploaded to the current page instead of to the configured `parent`.
