### ISSUE TITLE
[Panel/Blueprint] Allow creation of new pages with a specific template only 

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#1034]
Related to this discussion : https://getkirby.slack.com/archives/CBN859614/p1538043474000100

What I'm trying to achieve and there's currently no solution for it, is to have a Pages section in the panel that will display a list of pages with different templates but will allow the creation of new pages only with a specific template.

Right now the `templates` option is used to both filter the displayed results and the available blueprints one can use to generate new pages. Would be nice to have two separate options for those two cases.

**Use Case**

A Pages Section to gives user access to the homepage, the error page and other static pages but prevents the creation of new pages with the home.yml and error.yml blueprints.

Right now the only workaround is to use two separate pages sections, one to only display all pages with multiple templates and another section to create new pages with the desired template.

**Comment by bastianallgeier** [comment]
You can now finally set a new "create" option to define the template(s) that should be available when creating new pages. 

```
sections: 
  pages: 
    type: pages
    create: 
      - a
      - b
    templates: 
      - a 
      - b
      - c
```

Can also be just a single template

```
sections: 
  pages: 
    type: pages
    create: a
    templates: 
      - a 
      - b
      - c
```
