### ISSUE TITLE
[Panel] Sections props don't return the default values

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1037]
This:

```php
Kirby::plugin('my/plugin', array(
  'sections' => array(
    'mysection' => array(
      'props' => array(
        'example' => function($example = 'default') {
          return $example;
        },
        'buttons' => function($buttons = ['one', 'two']) {
          return $buttons;
        },
      ),
    ),
  ),
));
```

With these options in the blueprint:

```yaml
sections:
  mysection:
    type: mysection
    example: Some string
    buttons:
      - one
      - two
      - three
```     

Works fine.

But if I only set:

```yaml
sections:
  mysection:
    type: mysection
```    

```example``` and ```buttons``` are ```undefined``` in my js.

This behaviour doesn't happen when I change its type to be a Field, the issue happens only with sections.
