### ISSUE TITLE
[Docs] Time field references incorrect parameters for Format and Interval.

### ISSUE THREAD

**Issue by louiswalch** [getkirby/kirby#1038]
Current K3 docs reference incorrect variables for Format and Interval. 
```
  time:
    label: Time (Incorrect)
    type: time
    format: 12
    interval: 30
```

The correct variables are `notation` and `step`.
```
  time:
    label: Time (Correct)
    type: time
    notation: 12
    step: 30
```
