### ISSUE TITLE
[Panel] Changes are not saved for drafts (files field)

### ISSUE THREAD

**Issue by robinscholz** [getkirby/kirby#1041]
When adding the following field to a blueprint, changes are not saved if the page status is set to `draft`. However, updating the field works fine if the page is published.

```
  cover:
    label: Übersicht
    type: files
    query: page.images
```
or

```
layouts:
    type: structure
    label: Layouts
    required: true
    fields:
      images:
        label: Fotos
        type: files
        query: page.images
        max: 3
```
(Here I can add structure entries, but cannot fill them with an image selection.)

Tried with a fresh install of the starterkit as well as with a current project.
