### ISSUE TITLE
[Panel] Select field - query: user

### ISSUE THREAD

**Issue by iskrisis** [getkirby/kirby#1047]
When using select field to get users like this (taken from docs)
```
user:
  type: select
  options: query
  query: users.filterBy("role", "admin").sortBy("name", "desc")
```
Select field shows expected list of emails which can be selected
![screen shot 2018-10-04 at 18 37 17](https://user-images.githubusercontent.com/4954323/46492115-97fa7c80-c804-11e8-99c4-89be8b2d7e3a.png)
But result saved in content file is this string
```
User: ab755c89908bd9fb094d310af311fce93db2aad7
```
Instead of expected 
```
User: krisa@krisa
```

I am not sure if it is a bug or i can use that hash to get user somehow.
