### ISSUE TITLE
[Panel] Select field query with filterBy "in" operator results in error

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#1057]
I used the Beta 6 starterkit: This query results in an error:

```
  test:
    label: Test
    type: select
    options: query
    query: site.index.filterBy("template", "in", ["project", "projects"])
```

<img width="777" alt="screenshot" src="https://user-images.githubusercontent.com/15672385/46597705-8a354780-cae1-11e8-8630-3645b26bb39f.png">

**Comment by bastianallgeier** [comment]
Array notation is something that our rather simple syntax cannot handle. You could solve this with a collection.

**Comment by SebastianEberlein** [comment]
If anyone has the same issue, here’s the solution using a collection as Bastian suggested:

Create a collection likes this:
```php
// site/collections/project-pages.php

<?php

return function ($site) {
  return $site->index()->filterBy("template", "in", ["projects", "project"]);
};
```

And use it in the blueprint like this:
```yaml
test:
    label: Test
    type: select
    options: query
    query: kirby.collection('project-pages')
```
