### ISSUE TITLE
[Panel] Error when loading sections data (this.load is not a function)

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1062]
Following the docs, calling `this.load` on `created` in a section component throws an error.

```javascript
created() {

  // Doesn't work
  // throws: this.load is not a function
  this.load().then(response => {
      this.test = response.test
  })

  // Hackish way that works
  this.$api
        .get(this.parent + "/sections/" + this.name)
        .then(response => {
            this.test = response.test
        })

}

**Comment by bastianallgeier** [comment]
Hm, I can't reproduce this in the latest nightly. Could you double-check if you still run into it?

**Comment by bastianallgeier** [comment]
In order to keep the beta tickets clean I'll close this. Please feel free to reopen, if it turns up again.

**Comment by sylvainjule** [comment]
Unfortunately it isn't fix on my end (latest nightly). I've made the change in one of my plugin on a dedicated branch: https://github.com/sylvainjule/kirby-annotator/tree/load

You can set-up a blueprint with:
```yaml
title: Annotator

columns:
  - width: 2/3
    sections:
      annotator:
        type: annotator
        storage:
          src: src
          markers: markers

  - width: 1/3
    sections:
      myfields:
        type: fields
        fields:
          src:
            label: Image file
            type: files
            max: 1
          markers:
            label: Markers
            type: structure
            fields:
              note:
                label: Note
                type: text
```

Throws:

<img width="1278" alt="capture d ecran 2018-12-05 a 12 58 06" src="https://user-images.githubusercontent.com/14079751/49512184-73b32e80-f88d-11e8-9721-278f8a23e9d9.png">
