### ISSUE TITLE
[Panel] Add an alternative for shorter k-empty

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1075]
Empty field states can be quite tall vs. their filled states. 

For example, a `files` field limited to 1 file only is 3 times less tall when a file is selected than its placeholder. 

This difference might be be problematic (well, as problematic as a placeholder height can get, but still) when trying to fit lots of fields in a minimal space.

I wonder if we could have access to an option like:

```yaml
empty: card
empty: list
```

Where card would be the current display, and `list` something like this:

<img width="404" alt="capture d ecran 2018-10-11 a 10 51 14" src="https://user-images.githubusercontent.com/14079751/46792863-98cf6900-cd44-11e8-81bc-dbc494da3f19.png">

```scss
.k-empty {
    padding: 0;
    display: flex;
    align-items: center;
    flex-direction: row;
    justify-content: flex-start;
    .k-icon {
        width: 38px;
        height: 38px;
        border-right: 1px solid #d6d6d6;
        margin-bottom: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        svg {
            width: 14px;
        }
    }
    p {
        line-height: 1.25rem;
        padding: .5rem .75rem;
    }
}
```

**Comment by bastianallgeier** [comment]
I actually really like the idea!

**Comment by REHvision** [comment]
I also see the "problem" and I really like the idea, too! :+1:

BUT PLEASE don't introduce yet another option for this!!
Instead, simply link the placeholder layout to the actual layout options of that section

E.g.
```
layout: cards
item:
  image:
    ratio: 1/1
```
would show a square placeholder,
```
layout: cards
item:
  image:
    ratio: 4/1
```
a 4/1 ratio placeholder and
```
layout: list
```
the proposed layout of @sylvainjule.

This way every placeholder already implies how items will look like and reserve only the space needed to display the first item.
