### ISSUE TITLE
[Panel] Some role permissions are not considered by the panel.

### ISSUE THREAD

**Issue by julien-gargot** [getkirby/kirby#1118]
With a `users: false` permissions in a role blueprint it was expected that the user cannot create or modify other users nor change critical options about himself. But the user still has the opportunity to change is own role and to change language of others.

Here the blueprint:
```
#/site/blueprints/users/editor.yml

title: Editor
description: The editor has all rights on contents
permissions:
  users: false
```
also tried with
```
#/site/blueprints/users/editor.yml

title: Editor
description: The editor has all rights on contents
permissions:
  users:
    create: false
    createAvatar: true
    deleteAvatar: false
    changeName: false
    changeEmail: false
    changePassword: false
    changeRole: false
    delete: false
    update: false
```

**Comment by bastianallgeier** [comment]
That the user is still able to change the language of others is a bug. But access to their own account can be limited with the user keyword. 

```
#/site/blueprints/users/editor.yml

title: Editor
description: The editor has all rights on contents
permissions:
  users: false
  user: false
```
