### ISSUE TITLE
Nested structure field: entries in nth-level not clickable

### ISSUE THREAD

**Issue by MathiasGmeiner** [getkirby/kirby#1119]
I'm not able to click entries in the 2nd entry level of a structure field.
I tried it first with a composer install of the devkit and beta 6 and the screencast is with the same devkit and a manually copied nightly from 2018-10-18

This is the structure field I'm using:

```
fields:  
  sectionTitle:  
    label: Titel  
    type: text  
    required: true  
  dishes:  
    label: Einträge  
    type: structure  
  fields:
    itemTitle:
      label: Titel
      type: text
      required: true
    itemText:
      type: textarea
      label: Text
      buttons: false
      required: true
    itemPrice:
      type: text
      label: Preis
      required: true
```
The saved content is correct, as far as I can tell.
This is the short screencast of the behaviour:
![kapture 2018-10-22 at 12 45 18](https://user-images.githubusercontent.com/103595/47288866-67825300-d5f8-11e8-936f-4163dff47980.gif)
