### ISSUE TITLE
[Panel] Pages field in section info

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1120]
When using the pages field in a section info, it displays the plain field values and not the names of the pages:

```yaml
headline: Awards
type: pages
layout: cards
parent: site.find("awards")
status: listed
templates: award
info: '{{ page.related }} ({{ page.year }})'
```

![bildschirmfoto am 2018-10-22 um 12 43 33](https://user-images.githubusercontent.com/25466/47288851-40c41c80-d5f8-11e8-85df-f4e804537b39.png)

### Expected behaviour

I'd expect the panel to display `Channelled Buried Moved Lost (2015)` instead of `- projects/cbmlex (2015)`. If there were multiple referenced pages, I'd expect a comma-separated list.
