### ISSUE TITLE
[Panel] Add possibility to filter files by template in blueprints

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#1125]
https://nnnnext.getkirby.com/docs/cheatsheet/fields/files

```
fields:
  gallery:
    label: Gallery
    type: files
    template: gallery-image
```
