### ISSUE TITLE
File field: Wrong path

### ISSUE THREAD

**Issue by MathiasGmeiner** [getkirby/kirby#1127]
I have a problem with file paths in a image field, I get different behaviour locally and on my production server.

I have a field for a slider:
```
fields:
  sliderTop:
    extends: fields/images
    required: true
```

The section is defined like this:
```
label: Slider
type: files
headline: Bilder
template: image
query: page.images
```

Locally the image is saved without the path:
```
Slidertop: 

- 0484.jpg
```

and on the server it’s saved like this:
```
Slidertop:

- uber-katrina/0484.jpg
```

Both systems run on PHP 7.1.23 and Apache on the latest nightly.

With the beta6 everthing works fine!
