### ISSUE TITLE
[Panel] Custom preview link is not implemented everywhere

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#1128]
If I add a custom preview link to a blueprint like so

```yml
title: Some Title
options:
  preview: '{{ page.parent.url }}#123demo'
```

the custom link works like expected when clicking on **open** in the page's editing mode.

In page sections though, the custom preview link is not used when opening the page vie the page options (dots).

Expected behavior: If a blueprint has a custom preview link, use it for **all** preview links
