### ISSUE TITLE
[Panel] File field: parent items are not saved

### ISSUE THREAD

**Issue by MathiasGmeiner** [getkirby/kirby#1133]
I have a template for a site wide media library:

**media-library.yml**
```
title: Media
preset: files
pages: false
options:
  url: false
  status: false
  delete: false
  changeTitle: false
  preview: false
```

I can grep and select this files within e.g. the **about.yml** with this:
```
fields:
  hSliderTop:
    label: Slider Oben
    type: headline
  sliderTop:
  sliderTop:
    label: Slider
    type: files
    parent: site.find('bibliothek')
```
But after saving the field is empty.

![kapture 2018-10-25 at 13 57 13](https://user-images.githubusercontent.com/103595/47498573-ef1ccb80-d85d-11e8-9295-13d8d25fd45b.gif)
