### ISSUE TITLE
Checkboxes / Default values

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1136]
1. Uncheck all the boxes
2. Hit save
= The boxes get checked again.
(If you uncheck only one and leave one checked it works..)
```
display:
                                label: Display
                                type: checkboxes
                                default:
                                    - pages
                                    - files
                                options:
                                    pages: Pages
                                    files: Files
```
