### ISSUE TITLE
Changing status of page from Published to In Review or Draft throws an unexpected error

### ISSUE THREAD

**Issue by omz13** [getkirby/kirby#1147]
Running the latest beta (build feadd58).

![screen shot 2018-10-27 at 18 37 36](https://user-images.githubusercontent.com/88007/47606746-91cc7a00-da17-11e8-9676-8d5b90f951e0.png)

Changing status of page from Published to In Review or Draft throws an unexpected error

Changing the status from In Review to Published is ok

Changing status from In Review to Draft throws an error.

From Draft to In Review throws an error.

From Draft to Published throws an error.

Even though the error is thrown, the page's status is correctly changed.

**Comment by bastianallgeier** [comment]
Could you activate debug mode in the config and let me know what you get in the console?

**Comment by omz13** [comment]
```PHP Fatal error:  Nesting level too deep - recursive dependency? in .../vendor/getkirby/cms/src/Toolkit/Collection.php on line 895```


![screen shot 2018-10-28 at 14 47 18](https://user-images.githubusercontent.com/88007/47616689-86815900-dac0-11e8-96f1-966e998a85d9.png)

**Comment by bastianallgeier** [comment]
Thank you! Now we need to find out what causes the endless loop. Could you send me the blueprint setup you are using? Sorry for the hassle.

**Comment by johannahoerrmann** [comment]
Here's what I get:

```
{
  "status": "error",
  "exception": "Whoops\\Exception\\ErrorException",
  "code": 1,
  "message": "Nesting level too deep - recursive dependency?",
  "details": null,
  "file": "branchplant.k3/kirby/src/Toolkit/Collection.php",
  "line": 895
}
```

And a blueprint setup (this happens across a lot of different setups though – as I said, all site/children/grandchildren pages show this same behavior):

```
name: award
title: Award
num: zero
tabs:
  content:
    label: Content
    icon: text
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              title:
                label: Title
                type:  text
              category:
                label: Category
                type: text
              other:
                label: Other
                type:  text
              url:
                label: External Link
                type: url
              related:
                label: Awarded Project
                type: pages
      - width: 1/3
        sections:
          year:
            headline: Year
            type: fields
            fields:
              year:
                label: Year
                type: text
                validate:
                  minLength: 4
                  maxLength: 4
                  - num
```
