### ISSUE TITLE
[Panel]: Structure field with parent issue

### ISSUE THREAD

**Issue by MathiasGmeiner** [getkirby/kirby#1149]
**Describe the bug**
Inside a structure field I have a file field with a parent query:
```
  itemImage:
    label: Image
    extends: fields/image-global
    required: true
```

this is the "global" file definition:
```
label: Image
type: files
max: 1
parent: site.find('bibliothek')
```

I can select the images/files inside the structure field, but after saving the value is not stored.
In the .txt the field looks like that:

```
  itemimage: [ ]
```

**Screenshots**

**Kirby Version**
I tried it with the latest nightly (26.10.2018) and the develop branch (29.10.2018 3pm)

**Additional context**
The parent query works great with a file filed outside the structure field. 
Maybe it's related to this one  #https://github.com/k-next/kirby/issues/1133
