### ISSUE TITLE
Page with tabs can not be saved with required fields

### ISSUE THREAD

**Issue by georgobermayr** [getkirby/kirby#1153]
It seems as if this issue is back again: https://github.com/k-next/kirby/issues/748

If have a simple blueprint setup like this:
```
title: Test

pages: false
files: false

tabs:

  mytab:
    fields:
      testfield:
        type: text
        required: true

  anothertab:
    fields:
      anothertest:
        type: text
        required: true
```

This leads to the behaviour in the Panel shown in the screencast from the old issue. 

**Kirby Version**
Latest nightly build
