### ISSUE TITLE
Toggle field broken on files blueprint

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1166]
**Describe the bug**
The toggle field does not work on files blueprint. It works on page blueprint.
```
autoplay:
  label: Autoplay
  type: toggle
  width: 1/3
  text:
    - Nope
    - Yay
```
**To Reproduce**
1. Go to a file
2. Click on toggle field
3. Click save
4. It reverts back...

**Kirby Version**
3.0.0-beta-6.14

**Desktop (please complete the following information):**
 - macOS
 - chrome
 - Version 70.0.3538.77
