### ISSUE TITLE
[Panel] Unbreakable words break checkboxes / radios columns display

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1180]
**Describe the bug**
Having unbreakable words in a checkbox / radio input makes the columns expand and overflow:

<img width="753" alt="avant" src="https://user-images.githubusercontent.com/14079751/48332642-e2b5b280-e654-11e8-9e9d-7e31c0915e43.png">

**To Reproduce**
3 columns radio / checkboxes.
1 - 5f922438039265.5794e9837c7ee.jpg
2 - 8ef2221bf0047920fe1c8b26d719f396.jpg
3 - image-3.jpg

**Expected behavior**
I'm fixing it like this:

```scss
.k-input[data-theme=field][data-type=checkboxes],
.k-input[data-theme=field][data-type=radio] {
    .k-checkboxes-input li, .k-radio-input li {
        min-width: 0; // makes sure the columns don't auto-expand
        overflow-wrap: break-word; // force word-break
    }
}
```

<img width="762" alt="apres" src="https://user-images.githubusercontent.com/14079751/48333035-3e347000-e656-11e8-825b-47a50d0b2f3c.png">
