### ISSUE TITLE
[Panel] Strange data corrupting structure field bug

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#1190]
**Describe the bug**
When adding a new item to a structure field which has a number field inside, it "selects" the previous entries and overwrites their (also possibly already entered) values in all fields inside the "add new" dialog.

When entering the first number it auto-fills and jumps to a already existing number entry. By increasing the value nothing additional happens to all fields but when lowering the value below the previous selected, it "selects" this entry..

When pressing Enter now, this gets directly safed and messes up the whole data of this structure field.
When pressing Escape or clicking outside, you can see the corrupted data and can luckily revert it.

btw: In another structure field on the same page without number field nothing similar seems to happen.

**To Reproduce**
1. place a number field inside a structure (and have other fields, too)
2. add a first item with some data
3. add a new item and enter one digit or press an arrow key inside the number field
4. See the error happening

**Screenshots**
![peek 2018-11-16 01-21](https://user-images.githubusercontent.com/2584674/48589999-37e81180-e93e-11e8-9fac-f3ab48ff1180.gif)

**Kirby Version**
I guess something got mixed up between 3.0.0-beta-6.13 (there it still works correctly) and 3.0.0-beta-6.16 (skipped 3 versions) where it happens up to  the current 3.0.0-beta-6.19...

**Console output**
no errors in the console

**Desktop (please complete the following information):**
 - OS: Ubuntu 17.10
 - Browser Firefox 61.0.1

**Comment by bastianallgeier** [comment]
Hm, I cannot reproduce this. Could you send me the blueprint for the field. I replicated it from the video, but maybe I'm missing some option that causes this.

**Comment by REHvision** [comment]
Thanks a lot for looking into this :smiley: and this is my blueprint-section
`/blueprints/sections/geschichtsabschnitt.yml`:
```yaml
type: fields
fields:

  geschichte:
    label: Geschichte
    type: structure
    sortBy: jahr asc

    columns:
      prefix:
        width: 1/5
      jahr:
        width: 1/5
      ereignis:
        width: 3/4

    fields:

      prefix:
        label: Prefix
        type: select
        width: 1/4
        options:
          seit: seit
          ab: ab
          von: von
          nach: nach
          bis: bis

      jahr:
        label: Jahr
        type: number
        width: 1/4

      ereignis:
        label: Ereignis
        type: textarea
```

**Comment by REHvision** [comment]
And the page blueprint where I use this looks like this:
```yaml
...
columns:
  - width: 1/1
    sections:
      intro: sections/intro

  - width: 3/4
    sections:
      inhalt: sections/inhaltsabschnitte
      geschichte: sections/geschichtsabschnitt
...
```
