### ISSUE TITLE
[Panel] Default value for checkboxes doesn't work

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1197]
**Describe the bug**
Adding a default value to a checkboxes field does not show on a newly created page, it seems that the page creation process doesn't store the value correctly.

**To Reproduce**

Add this snippet to a blueprint:

```yaml
category:
  label: Categories
  type: checkboxes
  default: first
  options:
    first: First category
    second: Second category
```

**Expected behavior**
The panel does indeed store the default value in the .txt file, but in a wrong format. Default is stored as an array:

```
Category: 

- first
```

Whereas manually-checked checkboxes are stored as a comma-separated list, the field is expecting:

```
Category: first
```

**Kirby Version**
3.0.0-beta-6.20
