### ISSUE TITLE
More options for parent in pages sections

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/kirby#1202]
**Describe the bug**
Currently the only option for `parent` is `site.find("blog")`. It would be great if we could access a parent page relative to the current page with `parent: page.find("subpages")`.

https://nnnnext.getkirby.com/docs/cheatsheet/sections/pages#filtering-pages

**To Reproduce**
In the Starterkit:  
This modified `one-pager.yml` blueprint does not show subpages of `one-pager/sections` in the “Sections” section.

```yml
title: One Pager

sections:
  sections:
    headline: Sections
    type: pages
    status: all
    parent: page.find("sections")
```

This is the file structure.
<img width="240" alt="bildschirmfoto_2018-11-15_um_14 31 28_480" src="https://user-images.githubusercontent.com/1524319/48707179-e621de80-ebfe-11e8-8094-43552084da3e.png">

**Expected behavior**
Should show subpages of `one-pager/sections` (“Headline”, “Gallery”, “Text”, etc.)

**Kirby Version**
3.0.0-beta-6
