### ISSUE TITLE
[Panel] Field option disabled prevent $page->update() from updating field in panel

### ISSUE THREAD

**Issue by mattiashaal** [getkirby/kirby#1203]
**Describe the bug**
When using the field option disabled in a page blueprint it prevent $page->update() (used in corresponding page template) from updating the field in the panel.

```
fields:
          counter:
            label: Page views
            type: number
            disabled: true
            width: 1/2
```

**Expected behavior**
That the field updates in the panel when running the template code:

```php
$counter = $page->counter()->int();
$counter++;

$page->update([
  'counter' => $counter
]);
```

**Kirby Version**
Nightly Build 2018-11-16. It worked fine in Nightly Build 2018-11-14.
