### ISSUE TITLE
Not translatable content is not in sync with default langauge

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#1239]
**Describe the bug**
Not translatable content only gets updated after saving a specific language.  
Of course after the langauge specific text file is created.

**To Reproduce**
1. Create a multilang site and add a secondary language
2. Add a at least two fields to a blueprint. One with `translate: false` one that allows translation
3. Add and save the content in the default language
4. Save the content in the second language
5. Change the not translatable content in the default language
6. Switch to secondary language (`ipsum` will only get updated after resaving the secodnary language)

```yml
fields:
  lorem:
    label: Lorem
    type: text
    
  ipsum:
    label: Ipsum
    type: text
    translate: false
```

**Expected behavior**
The not translatable content should always be up to date in all languages.

**Kirby Version**
3.0.0-beta-6.25
