### ISSUE TITLE
Infinite loop when calling a custom page method in a blueprint query

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#1240]
**Describe the bug**
I have a little plugin which creates a uuid if requested.

``` php
use Ramsey\Uuid\Uuid;

Kirby::plugin('lukaskleinschmidt/uuid', [
    'pageMethods' => [
        'uuid' => function (): string {
            if ($uuid = $this->content()->uuid()->value()) {
                return $uuid;
            }

            $this->update([
                'uuid' => $uuid = Uuid::uuid4(),
            ]);

            return $uuid;
        }
    ]
]);
```

This all works great.  
As soon as I try to reference a page like the following example a uuid is created once on the fly.
``` yml
title: Product

fields:
  places:
    label: Places
    type: multiselect
    options: query
    translate: false
    query:
      fetch: site.find("places").children
      text: "{{ page.title }}"
      value: "{{ page.uuid }}"
```

But if I try to do something like related products.
``` yml
title: Product

fields:
  related:
    label: Related
    type: multiselect
    options: query
    translate: false
    query:
      fetch: page.siblings(false)
      text: "{{ page.title }}"
      value: "{{ page.uuid }}"
```

I get following error:
``` html
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in vendor\getkirby\cms\src\Data\Txt.php on line 107

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in vendor\filp\whoops\src\Whoops\Util\Misc.php on line 1
```
Referencing products from another page works as expected.

**Edit:**  
Forgot to mention. The problem only occurs if the field values are not set yet. As soon as the uuid is already created the related field works.

**Expected behavior**
I would expect that it would work 😬  
Actually I can easily work around by doing all this in a hook.  
But still a bug I guess.

**Kirby Version**
3.0.0-beta-6.26
