### ISSUE TITLE
Structure columns

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1251]
**Describe the bug**
Structure columns not working.

````
addresses:
                        label: Addresses
                        type: structure
                        columns: [city]
                        fields:
                            street:
                                label: Street
                                type: text
                            zip:
                                label: ZIP
                                type: text
                            city:
                                label: City
                                type: text
````

**Screenshots**

![structure](https://user-images.githubusercontent.com/19476159/49795352-0e9e8380-fd3a-11e8-84bb-b4d509c1e5c5.png)

**Kirby Version**
3.0.0-beta-6.28

**Comment by bastianallgeier** [comment]
That's the wrong syntax: 

```yaml
addresses:
    label: Addresses
    type: structure
    columns: 
        city: true
    fields:
        street:
            label: Street
            type: text
        zip:
            label: ZIP
            type: text
        city:
            label: City
            type: text
```
