### ISSUE TITLE
[Panel] Nested structure "prefilling"

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#1317]
**Describe the bug**
For a specific workflow nested structure fields get somehow prefilled when adding a new entry. The bug only occurs when I fill in the second structure at the same time as the first one. The bug occurs on a single languge and multilang site.

Workflow when the error occurs:
![error](https://user-images.githubusercontent.com/10027897/50765655-daee4500-1276-11e9-8350-b898e43f65e1.gif)

Workflow when the error does not occur:
![no-error](https://user-images.githubusercontent.com/10027897/50765702-08d38980-1277-11e9-98ab-8a048b79c067.gif)

The blueprint I was using to narrow down the bug:
```yml
fields:

  firstLevel:
    label: First Level
    type: structure
    fields:

      title:
        label: Title
        type: text

      secondLevel:
        label: Second Level
        type: structure
        fields:

          title:
            label: Title
            type: text

```

**Expected behavior**
The nested structure field should not get prefilled.

**Kirby Version**
3.0.0-RC-3.0

**Desktop**
 - Windows 10
 - Firefox 65 / Chrome 71
