### ISSUE TITLE
[Panel] Structure fields with capitals and column width doesn't work

### ISSUE THREAD

**Issue by samvantoever** [getkirby/kirby#1336]
**Describe the bug**
When you're using structure fields with capitals and set the column width, they don't show up in the panel.

**To Reproduce**
``` yaml
socialmedia:
  label: Social Media
  type: structure
  columns:
    platform: 
      width: 1/4
    platformUrl: 
      width: 3/4
  fields:
    platform:
      label: Platform
      type: text
    platformUrl:
      label: Url
      type: url
```
`platformUrl` won't show up in the structure field unless you use `platformurl`

**Expected behavior**
`platformUrl` to show up in panel field when setting column width.

**Kirby Version**
3.0.0-RC-4.0

**Console output**
No errors

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version:  71.0.3578.98
