### ISSUE TITLE
Field disappears in blueprint with tabs

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1344]
**Describe the bug**
When creating a blueprint like this with two tabs and clicking on tab1, the textarea field disappears

```
title: Test Page
tabs:
  one:
    label: tab1
    fields:
      text1:
        label: Text
        type: textarea
  two:
    label: tab2
    fields:
      text2:
        label: Text
        type: textarea
```

**To Reproduce**
1. Create a new page with this blueprint
2. Open the page in Panel
3. Click on tab1, in the URL `#one` is added
4. See error (the textarea field disappears) (it reappears if you click on tab2 and then again on tab1

**Expected behavior**
The textarea field should still be there.

**Screenshots**
![tab](https://user-images.githubusercontent.com/5312492/51056877-4d975180-15e4-11e9-9c40-4e9474d23dae.gif)

**Kirby Version**
Tested with RC-5

**Console output**
No console output visible

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Safari
