### ISSUE TITLE
[Panel] Extended field option is merging with original field option, instead of replacing it

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/kirby#1349]
**Description + to reproduce**

Same as https://github.com/k-next/kirby/issues/1088, but for extended fields.

Was mentioned for the markdown-field (https://github.com/sylvainjule/kirby-markdown-field/issues/51), but applies to all (and core) fields:

In `blueprint/fields/textarea.yml`, I set:

```yaml
type: textarea
buttons:
  - bold
  - italic
```

Then in another page, if I want to only show the `ul` button:

```yaml
extends: fields/textarea
buttons:
  - ul
```

**Expected result:**

<img width="206" alt="capture d ecran 2019-01-12 a 16 46 12" src="https://user-images.githubusercontent.com/14079751/51075268-9b19ca00-1689-11e9-9546-88da9f7b6118.png">

**Current result:**

<img width="208" alt="capture d ecran 2019-01-12 a 16 45 51" src="https://user-images.githubusercontent.com/14079751/51075271-a0771480-1689-11e9-95ac-3d96df69b95f.png">
