### ISSUE TITLE
Default value in blueprint for site.yml doesn’t populate the field

### ISSUE THREAD

**Issue by felixbridell** [getkirby/kirby#1396]
Fields in the site.yml blueprint with default values never show up in the panel.

**To Reproduce**
1. Add a field in the site.yaml blueprint
2. Give it a default value
3. Login in to the Panel and take a look at the field, no value is showing up inside the field.

This is an example of the field inside site.yml
```
field_name:
        label: My label
        type: text
        default: This is my default value
        required: true
```

**Expected behavior**
The default value (This is my default value) should show up in the panel

**Kirby Version**
v 3.0.0
