### ISSUE TITLE
[yml] site.images query doesn't seem to work

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby/kirby#1404]
**Describe the bug**
Code in site YML file:
```
    sections:
      files:
        type: files
        headline: Dateien
        max: 20
        sortable: false
        query: site.images
```
=> Lists all files, not just images.
