### ISSUE TITLE
Panel Fields Should Support Query Templates in Placeholder Field

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1421]
**Describe the bug**
The Blueprint Query Language does not seem to be supported in placeholder fields (at least for Text fields).

In my situation, a parent page has a "default" value stored in a field, and children have a field that can optionally override that field. It would be very helpful to have the "default" value displayed as a placeholder on the children pages.

```
      headline:
        label: Headline
        type: text
        placeholder: "{{ page.parent.defaultHeadline }}"
```

**To Reproduce**
1. Have a parent page with a field
2. Have a child page with a Text field has a placeholder that should display the parent field
3. View the child page in the panel

**Expected behavior**
The stored value of the parent should be in the placeholder text. Instead the string `{{ page.parent.defaultHeadline }}` literally appears as the placeholder.

**Kirby Version**
`3.0.1-rc.1`
