### ISSUE TITLE
Remove `num: date` or `num: datetime`

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1425]
**Describe the bug**
In Kirby 2, I could specify which field should be used to generate a date-based timestamp. In Kirby 3, this is no longer possible and makes handling legacy content files problematic. This feels like a serious regression.

Kirby 2 style:
```
pages:
  num:
    mode: date
    field: created
    format: YmdHi
```

The code that handles this in Kirby 3 is hardcoded to use the `date` field.

https://github.com/getkirby/kirby/blob/4fef488a4a1b9644f8b89df227829fc1b6f9d108/src/Cms/PageActions.php#L384

**Kirby Version**
`3.0.0-rc.1`
