### ISSUE TITLE
[Panel] Extending nested panel components not possible

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#1438]
**Describe the bug**
Extending a panel component and at the same time one if it's nested components does not change the nested component.

**To Reproduce**
```yaml
# Blueprint
title: Test
sections:
  pages_section:
    headline: Pages Section
    type: pages
  files_section:
    headline: Files Section
    type: files
```

```javascript
// index.js
panel.plugin('my/plugin', {
    components: {
        'k-empty': {
            extends: 'k-empty',
            template: `<p>lalala</p>`
        },
        'k-headline': {
            extends: 'k-headline',
            template: `<p>headline</p>`
        },
        'k-pages-section': {
            extends: 'k-pages-section'
        }
    },
});
```

result:
`k-empty` and `k-headline` are not extended inside `k-pages-section`

![pages-section](https://user-images.githubusercontent.com/46723734/52168607-533c0f00-272c-11e9-8160-312b5e91a9e7.PNG)

**Expected behavior**
`k-empty` and `k-headline` also extended inside `k-pages-section`

![section-overwritten](https://user-images.githubusercontent.com/46723734/52168635-7cf53600-272c-11e9-894c-f46b8137b9ea.PNG)

**Kirby Version**
3.0.0

**Console output**
```
Plugin is replacing "k-empty" app.js:1:236187
Plugin is replacing "k-headline" app.js:1:236187
Plugin is replacing "k-pages-section" app.js:1:236187
```

**Additional context**
[Post in the forum](https://forum.getkirby.com/t/extending-nested-panel-components-not-possible/12638)
