### ISSUE TITLE
Unable to Set Time When in AM/PM mode in Date Field

### ISSUE THREAD

**Issue by luxlogica** [getkirby/kirby#1449]
**Describe the bug**
If we have a date field with time set to `notation: 12`, the panel throws an error when the user tries to set the time, or change the AM/PM setting.

**To Reproduce**
1. Setup a date field with time set with a `notation: 12`:
``` yaml
date:
  type: date 
  label: Published On
  required: true
  time:
    notation: 12
```
2. Access the field in the Panel, and try to change the time

**Screenshots**
<img width="308" alt="screen shot 2019-02-05 at 8 56 13 am" src="https://user-images.githubusercontent.com/2994472/52241634-61ef1580-2928-11e9-9cb0-8d0780340ca7.png">

**Kirby Version**
3 - release.
