### ISSUE TITLE
Placeholder text for empty sections doesn't work.

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1467]
**Describe the bug**
The customization of the placeholder text (via the `empty` option) in pages and files sections doesn't work.

**To Reproduce**
1. Create a files section with the `empty` option:
```yml
sections:
 foo:
  type: files
  empty: "Hello Kirby"
```
2. The default text "No files yet" will show up. 

**Expected behavior**
"Hello Kirby" should be written

**Kirby Version**
stable 3.0.1

**Additional context**
In the `empty.php` mixin, in the `'empty'` prop. The `$empty` variable is passed to `I18n::translate`, but no fallback option is specified. Therefore, unless a translation actually exists for our string, NULL is returned for the prop. 
I don't know if `I18n::translate` should return the translation key when no translation is found and no fallback is given or if the `empty` mixin should pass a fallback option, like this:

```php
return I18n::translate($empty, $empty);
```

**Bonus points**
Also, the `empty` mixin prop requires its argument to be a `string`. This prevents us to pass it an associative array, like when when giving it multiple translations in the blueprint:
```yml
sections:
 foo:
  type: files
  empty:
   en: Hello Kirby
   it: Ciao Kirby
```
