### ISSUE TITLE
Permissions only partialy applied, everyone can create Admin users

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1468]
**Describe the bug**
Some not granted permissions are ignored. Every user can create new users of any role they want without permission.

**To Reproduce**
1. Create a User Blueprint that is not admin and set permissions like this:
```yaml
# site/blueprints/users
title: User
permissions:
  user: false
```

2. Log in to panel,  create a new user with role User
3. Log out and log in as the new user
4. Enjoy the ability to create new admin users

**Expected behavior**
Apply permissions as set in the blueprint

**Kirby Version**
3.0.1

**Comment by qwerdee** [comment]
Same goes for
```yaml
permissions:
  user: 
    create: false
```
and
```yaml
permissions:
  user: 
    *: false
```
