### ISSUE TITLE
[ToggleField] default option doesn't work

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby/kirby#1471]
**Describe the bug**
Form always loads with toggle button to true, no matter what default value is set in yaml file.

**To Reproduce**
```
  img_rounded:
    label: Abgerundete Ecken
    type: toggle
    default: false
    text:
      - Nein
      - Ja
```

**Kirby Version**
3.0.1
