### ISSUE TITLE
[Panel] using query with `filterBy()` doesn't work with array

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1479]
**Describe the bug**

I'd expect a query in a pages field like this to work:
```
    fields:
      references:
        label: References
        type: pages
        multiple: true
        query: site.index.filterBy('template', 'in', ['note', 'album'])
```

But this throws the error

"in_array() expects parameter 2 to be array, string given"

Tested with Kirby 3.0.1
