### ISSUE TITLE
“permissions: site: update: false” does not disable renaming of site

### ISSUE THREAD

**Issue by fooness** [getkirby/kirby#1480]
The following permissions for some role should probably also disable the renaming of site, I guess. But it’s still possible for this user to rename site.

```
title: Editor

permissions:
  site:
    update: false
```

**Comment by bastianallgeier** [comment]
This is not a bug but maybe not well documented enough. For pages and the site, the update permission applies to all form content. There's an additional changeTitle handle if you want to control renaming the page or site. 

```
title: Editor

permissions:
  site:
    changeTitle: false
```
