### ISSUE TITLE
Can't translate user blueprint fields

### ISSUE THREAD

**Issue by olach** [getkirby/kirby#1483]
**Describe the bug**
Translating fields in a user blueprint generates an error:

`Argument 1 passed to Kirby\Cms\Role::setDescription() must be of the type string or null, array given, called in /kirby/src/Toolkit/Properties.php on line 130`

**To Reproduce**
```yml
# /site/blueprints/users/visitor.yml
title:
  en: Visitor
  sv_SE: Besökare
description:
  en: Visitors has no access to the Panel
  sv_SE: Besökare har ingen access till panelen
permissions:
  access:
    panel: false
```

**Expected behavior**
Blueprint fields should be translatable.

**Kirby Version**
3.0.1
