### ISSUE TITLE
[Panel] Switching templates deletes existing content

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1489]
**Describe the bug**
I have a blueprint that allows switching between two templates. You can think of both templates as a short and a long version of the same content: they share the base fields but the longer version has additional fields.

Now, when I switch templates all my content is erased.

**Expected behavior**
The content file should not be cleared and all fields of the same name should be reused and shown in the panel.

**Kirby Version**
Kirby 3.0.2, multilingual setup

**Comment by bastianallgeier** [comment]
Are the fields all of the same type as well? Content should only be erased if the field types are different.

**Comment by nilshoerrmann** [comment]
I copied the blueprint and added an additional field. So yes.
The content file still exists but is completely empty.

Just added above: this is in a multilingual setup.

**Comment by nilshoerrmann** [comment]
I've just seen the `missing: information` tag: is there anything else I can provide you with?

**Comment by distantnative** [comment]
I can confirm this.

Multilanguage (en & de) when switching templates with saved values (works fine with localstorage, but not after saving):

```yaml
# event.yml

title: Event
preset: page

options:
  changeTemplate:
    - gala

fields:
  intro:
    type: textarea
    size: small
  text:
    type: textarea
    size: small
```

and 

```yaml
# gala.yml

title: Gala
preset: page

options:
  changeTemplate:
    - event

fields:
  intro:
    type: textarea
    size: small
  text:
    type: textarea
    size: small
  invitation:
    type: textarea
    size: small
```
