### ISSUE TITLE
[Api] Wrong order of site files in JSON

### ISSUE THREAD

**Issue by robinscholz** [getkirby/kirby#1498]
**Describe the bug**
The sort order of site images is not respected in the generated JSON. Instead images are returned alphabetically.

**To reproduce**
1. Download the starterkit
2. Adjust the site blueprint:

```
title: Site

columns:
  - width: 1/2
    sections:
      albums: sections/albums
      images:
        type: files
        query: site.files
        layout: cards
        template: image
  - width: 1/2
    sections:
      notes: sections/notes
      pages:
        type: pages
        create: default
        template:
          - about
          - home
          - default
```

3. Enable basic auth
4. Add some images to the site folder and change their order in the panel
4. Send a post request to `/api/site?select=files`

**Expected behavior**
Images should be included in the array in the correct sorting order

**Kirby Version**
3.0.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser /

**Additional context**
