### ISSUE TITLE
[Panel] File sections in sidebar don’t respect template’s ‘accept’ settings

### ISSUE THREAD

**Issue by robinscholz** [getkirby/kirby#1511]
**Describe the bug**
When overwriting the  `sidebar` within a  `preset: page` blueprint, sections with `type: files` and `template: files/XYZ` do not respect the `accept` settings  of the `files` blueprint

**To Reproduce**
1. Create blueprint with `preset: page`
2. Include:
```
sidebar:
  images:
   type: files
   template: files/image
```
and create `files/image` blueprint:
```
title:
  de: Bild
  en: Image
type: files
accept:
  mime: image/jpeg, image/png
  maxwidth: 3000
  maxheight: 3000
  maxsize: 1000000
```

3.  Try uploading a .gif or .pdf in the panel
4.  Should still be possible

**Expected behavior**
It should not be possible to upload wrong files.

**Kirby Version**
3.0.2

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome
 - Version 74.0.3710.0 (Official Build) dev (64-bit)
