### ISSUE TITLE
[MultiselectField] Options not sorted

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1516]
**Describe the bug**

The docs of the multiselect field state:

> `sort` – If true, entries will be sorted alphabetically on selection

Nevertheless, the result is not sorted in the UI.

**To Reproduce**

Blueprint:

```yaml
period:
  type: multiselect
  label: Zeitraum
  sort: true
  options: api
  api:
    url: "{{ site.url }}/my-api/years"
    fetch: years
```

The `api` returns a list of years:

```json
{"years":{"2019":"2019","2018":"2018","2017":"2017","2016":"2016","2015":"2015","2014":"2014","2013":"2013","2012":"2012","2011":"2011","2010":"2010","2009":"2009"}}
```

Result:

![grafik](https://user-images.githubusercontent.com/25466/53575656-4b785a80-3b72-11e9-882a-da1fe3253d78.png)

**Expected behavior**
In the given example above, the dropdown should stay as is, but the selected values should be sorted in ascending order. It should be `2017, 2018, 2019`.

3.0.3-rc.1 using latest Firefox on macOS
