### ISSUE TITLE
[Panel] Blurry images in image section

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1520]
**Describe the bug**
We are using an image section limited to a single image in the main column of our page (2/3 width). The layout is set to cards in order to have a large preview of the cover image.

Generally, everything displays as expected but Kirby is loading a small image scaling it up to the needed size which results in a very blurry preview. The source image is 2560 × 1600 pixels.

![grafik](https://user-images.githubusercontent.com/25466/53638519-c13dfe00-3c26-11e9-9f6c-587c23f3b0a0.png)

Setting `size: large` has no effect. The maximum image width seems to be 400 pixels.

**To Reproduce**
Simplified blueprint:

```yml
title: Projekt
sections:
  cover:
    type: files
    headline: Titelbild
    template: cover
    layout: cards
```

**Expected behavior**
The image should not be scalled and display in correct resolution.

**Kirby Version**
Kirby 3.0.3-rc.1 using Firefox on macOS Mojave.
