### ISSUE TITLE
[Panel] Select field is empty if field name has dash 

### ISSUE THREAD

**Issue by ThePoddi** [getkirby/kirby#1545]
**Describe the bug**
When you add an select field with an dash in the field name ("my-field-name") to an blueprint, kirby savex the input, but dont display the value in the select field. 

**To Reproduce**

1. Add select field in blueprint. Field name contains dashes. 

```
select-with-dash: 
    label: Select with dash  
    type: select  
    options:  
        option1: yes  
        option2: no  
```

2. Open Page in Panel which is linked with this blueprint.
3. Choose Option in Select field and save.
4. Kirby saves value in content file, but does not show the value in the select field.

**Expected behavior**
Show selected option in Select field like in fields without dash in field name.

**Screenshots**
![kirby-issue-select](https://user-images.githubusercontent.com/6749108/53913774-6fe5a280-405c-11e9-8c31-1ebec3b3532c.png)

**Kirby Version**
3.0.3

**Console output**
no errors

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version 72
