### ISSUE TITLE
Populating not possible with Structure fields

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#1551]
Structure fields can't have default values (as described in the docs). Create a new Blueprint with the code below. No entries were created.

Reference: https://getkirby.com/docs/reference/panel/fields/structure#default-values

```
accordion:
    label: Einträge
    type: structure
    columns:
      accordion_title:
        width: 1/1
    default:
      - accordion_title: "No 1"
      - accordion_title: "No 2"
      - accordion_title: "No 3"
    fields:
      accordion_title:
        label: Titel
        type: text
      accordion_content:
        label: Inhalt
        type: textarea
        size: medium
```

Tested with newest Kirby Version I've found.
