### ISSUE TITLE
Image background option in a pages section always black

### ISSUE THREAD

**Issue by pedroborges** [getkirby/kirby#1564]
**Describe the bug**
Image background option in a pages section is always black when the image is an icon.

**To Reproduce**
1. Add an `image.back` option to a pages section in the blueprint.
2. Go to the panel.

```yaml
title: Site

tabs:
  dashboard:
    label: Dashboard
    icon: dashboard
    sections:
      pages:
        headline: Panel
        type: pages
        image:
          query: page.icon
          back: white
```

**Expected behavior**
Display white background.

**Screenshots**

<img width="66" alt="Screen Shot 2019-03-12 at 15 30 15" src="https://user-images.githubusercontent.com/688309/54226068-c3804200-44db-11e9-935d-4fa09c954f7a.png">

<img width="609" alt="Screen Shot 2019-03-12 at 15 14 11" src="https://user-images.githubusercontent.com/688309/54225600-d34b5680-44da-11e9-8293-a1f2e1739a73.png">

**Kirby Version**
I have tested in all 3.0.* versions and 3.1.0-rc.1. It happens on all of them.

**Console output**
None.
