### ISSUE TITLE
12-Hour (AM/PM) Time Panel Field Does Not Save Value

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1574]
**Describe the bug**
When using the 12-hour notation `time` field in the Panel, the value does not get saved and loading the page always shows "12:00 AM".

The 24-hour notation works fine.

**To Reproduce**
1. Add a time field with the `12` notation
2. Select a time like "5:20 PM"
3. Save the page
4. Reload the page

```
      scheduledTime:
        label: Scheduled Time
        type: time
        notation: 12
        width: 1/3
        help: scheduledTime
```

**Expected behavior**
The time "5:20 PM" should still be there and saved in the content file as "5:20 PM". (The content file has no value saved for the time field.)

**Screenshots**
<img width="326" alt="Screen Shot 2019-03-14 at 2 04 50 PM" src="https://user-images.githubusercontent.com/417182/54391466-256ab400-4662-11e9-8497-d5c3a848c982.png">

**Kirby Version**
`3.0.3`

**Console output**
No console output given.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Browser: Safari
 - Version 12.0.3 (14606.4.5)

**Additional context**
My server's locale is en_US.
