### ISSUE TITLE
`translate: false` in a child of a structure field is saved as `null` on secondary language

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#1602]
**Describe the bug**
I was eager to test this feature of Kirby 3.1.0:
>translate: false is no longer ignored in structure fields

But it seems there's a problem with it. When you modify a structure entry that has a `translate: false` field in a secondary language, that field's value is not saved.

**To Reproduce**
1. Create a page with the following template:
```yaml
title: Test Page
preset: page
fields:
  title:
    type: text
  mydata:
    type: structure
    fields:
      foo:
        type: text
      bar:
        type: text
        translate: false
```
2. In the panel, create a new page using the new template.
3. In the default language, add a new entry in the structure.
4. Save your changes.
5. Switch to a secondary language.
6. Open the newly added structure field entry. The `translate: false` field should correctly be disabled and have the default language value, while the other field is editable.
7. Change the editable field.
8. Save your changes.
9. The `translate: false` field of the entry is suddenly empty and if you open the secondary language's txt file, you can see that the field's value is `null`. The other field (the translatable one) is alright, though. However, since the field has `translate: false` and is disabled, you can no longer give it a value via the panel.

**Expected behavior**
When you click save in step 8, it should either:
1. Copy the default language's untranslatable fields instead of setting `null` for their values.
2. Save only the translatable fields and merge the default language's data with the translated data.

**Kirby Version**
3.1.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 73.0.3683.75 (Official Build) (64-bit)
