### ISSUE TITLE
Structure Field Column Label Taken from 'fields', Not from 'columns'

### ISSUE THREAD

**Issue by luxlogica** [getkirby/kirby#1612]
**Describe the bug**
The [docs for table columns in structure fields](
https://getkirby.com/docs/reference/panel/fields/structure#table-columns) show that there is a 'label' option for columns that should be used to set the COLUMN LABEL in a structure field. That option, however, seems to do nothing: the column label seems to be taken from the respective field definition's 'label' option instead.

**To Reproduce**
1. setup a structure field, like this:

```
slideshow:
    type: structure
    label: Optional Slideshow Images 
    fields:
      slide_img:
        label: Label from Fields
        type: files
    columns:
      slide_img:
        label: Label from Columns
```

2. Gasp at how the column header in the Panel displays "Label from Fields".

Note that removing the 'label' option from 'fields', and leaving only the one from 'columns', makes the column header take the field name ('Slide_img') - implying that the columns label is perhaps not being used at all.

**Kirby Version**
3.1.0
