### ISSUE TITLE
[Panel] Site files with template don’t fetch filled in data upon reload/navigation

### ISSUE THREAD

**Issue by robinscholz** [getkirby/kirby#1623]
**Describe the bug**
When adding site files with a template/blueprint and filling out fields, the data is written to the txt files (which is how it’s supposed to be), but never fetched once the page is reloaded or navigated away from and back to.

**To Reproduce**
1. Download starterkit
2. Add an images section to the `site.yml` file:

```
images:
        headline: Slideshow
        query: site.files
        layout: cards
        size: small
        type: files
        template: slide
```
3. Add `files/slide,yml` 

```
title: Slide
type: files
accept:
    mime: image/*
    orientation: portrait
    maxheight: 3000
    minheight: 2000
fields:
  view:
    type: toggle
    label: Type
    text: Installation View?
    options:
      - Ja
      - Nein
  location:
    type: text
    label: Location
    when:
      view: true
  title:
    type: text
    label: Titel
    width: 1/2
    required: true
  year:
    type: number
    label: Jahr
    width: 1/2
  height:
    type: number
    label: Höhe
    step: .1
    after: ×
    width: 1/2
    when:
      view: false
  width:
    type: number
    label: Breite
    step: .1
    after: cm
    width: 1/2
    when:
      view: false
  technique:
    label: Technik
    type: text
    when:
      view: false
```
4. Add a title and save

5. Reload page

**Expected behavior**
Data should be visible once added.

**Screenshots**
<img width="942" alt="Screenshot 2019-03-28 at 13 08 09" src="https://user-images.githubusercontent.com/8195463/55156626-bd849500-515a-11e9-8206-1f217fda976e.png">

<img width="640" alt="Screenshot 2019-03-28 at 13 08 30" src="https://user-images.githubusercontent.com/8195463/55156628-be1d2b80-515a-11e9-808b-b94629d8dcd8.png">

**Kirby Version**
3.1.1.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 74.0.3729.22 (Official Build) dev (64-bit)

**Additional context**
