### ISSUE TITLE
Select field with numeric values show an empty option/value instead of the first option

### ISSUE THREAD

**Issue by jesuismaxime** [getkirby/kirby#1643]
All my select (extended or not) with numeric values skip the first value - whatever it is (if I remove the '0' and '01' options, then the '02' option doesn't show up.

**One of my select field**
```
          title_type:
            extends: fields/utils/select-heading-type
            options:
              - value: '0'
                text: Aucun
              - value: '01'
                text: Type 01
              - value: '02'
                text: Type 02
              - value: '03'
                text: Type 03
              - value: '04'
                text: Type 04
            default: '03'
            width: 1/4
```

**And the result**
https://imgur.com/H0TsQfY
https://imgur.com/4QyY05j

**Kirby Version**
3.1.1

**Comment by distantnative** [comment]
Works for me with 3.1.3:
<img width="1023" alt="Screenshot 2019-05-03 at 18 25 28" src="https://user-images.githubusercontent.com/3788865/57134617-e68aec00-6dd0-11e9-9eb4-ecbe392c8f18.png">

```
title_type:
  type: select
  options:
    - value: '0'
      text: Aucun
    - value: '01'
      text: Type 01
    - value: '02'
      text: Type 02
    - value: '03'
      text: Type 03
    - value: '04'
      text: Type 04
  default: '03'
```

Please try yourself and re-open if it still exists for you in 3.1.3
