### ISSUE TITLE
Manual sorting lost after selecting additional files

### ISSUE THREAD

**Issue by dinko** [getkirby/kirby#1645]
I'm experiencing a manual sorting problem in 3.1.1 (it's also the case in 3.1.0) when assigning new files to a gallery.

1 — I select a previously uploaded file and reorder manually
2 — After selecting another previously uploaded file, everything is sorted by filename again automatically, manual sorting order is gone, see video at
https://www.dropbox.com/s/hnsjybk7g6kk0a5/sorting-lost.mov?dl=0

Blueprint for that part is
```
fields:
  gallery:
    label: Gallery
    type: files
    layout: cards
    size: tiny
```
