### ISSUE TITLE
[Panel] Tags Field: Selecting from Suggestions Broken in Safari

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1646]
**Describe the bug**
Trying to select an autocomplete suggestion in the `tags` field does nothing in Safari. Works fine in Chrome.

```
      related:
        label: Related Pages
        type: tags
        accept: options
        options: query
        query: site.index
```

**To Reproduce**
1. Have a `tags` field in a blueprint
2. Type a few characters
3. Try to click the result

**Expected behavior**
The clicked result should go into the field.

**Screenshots**
<img width="259" alt="Screen Shot 2019-04-02 at 1 35 27 PM" src="https://user-images.githubusercontent.com/417182/55434419-7593b280-554c-11e9-8287-5d23ee7c48ba.png">

**Kirby Version**
`3.1.1` and `3.1.2-rc.1`

**Console output**
None

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Browser: Safari 12.1 (14607.1.40.1.4)
