### ISSUE TITLE
Date Picker: Min not working

### ISSUE THREAD

**Issue by georgobermayr** [getkirby/kirby#1650]
**Describe the bug**
The date picker is not honouring the `min` value in the blueprint.

**To Reproduce**
Create a blueprint with a date field:
```
birthday:
  label: Birthday
  type: date
  min: 01.01.1900
```
Test in the Panel.

**Expected behavior**
The field show allow dates back to 1900, but is only allowing the the last then years. 

**Kirby Version**
3.1.2-rc.1

**Comment by bastianallgeier** [comment]
I think this is not a regression. This has most likely been broken before. I will look into it for 3.1.3

**Comment by bastianallgeier** [comment]
Forget my previous comment. I missed the conversation in Slack. Sorry!

**Comment by bastianallgeier** [comment]
Hm, the only way I can reproduce the issue is in the calendar popup. The year selector in the popup does not show all years. But that happened before as well. I can select a year down to 1990 with the select fields in the input though without an issue. Maybe I'm missing something?

**Comment by distantnative** [comment]
@bastianallgeier I think his issue was about 1900 not 1990

**Comment by bastianallgeier** [comment]
@distantnative I meant 1900. It's still very early here \*cough\* :) 1900 works for me as well.

**Comment by georgobermayr** [comment]
Strange. I tested it again, and the issue still persists on my end, Kirby 3.1.2-rc.1

The full blueprint:
```
            fields:
              birthday:
                label: Birthday
                type: date
                min: 01.01.1900
                translate: false
                help: The birthday of the athlete.
```

The field is in a tab. 

In the Panel:
<img width="358" alt="Bildschirmfoto 2019-04-04 um 12 28 09" src="https://user-images.githubusercontent.com/8470615/55549000-2331cd80-56d5-11e9-992d-5eb656f60dd1.png">

The `min` value seems to be populated into the date field:
<img width="404" alt="Bildschirmfoto 2019-04-04 um 12 29 06" src="https://user-images.githubusercontent.com/8470615/55549053-49576d80-56d5-11e9-88e4-f7ec22ff99bc.png">

Maybe I'm missing something here? 
It used to work in the previous version.

**Comment by nilshoerrmann** [comment]
Does it work with the ISO date: `1900-01-01`?

**Comment by bastianallgeier** [comment]
That's so weird. Your exact blueprint code works totally fine for me in rc-1

![Bildschirmfoto 2019-04-04 um 12 38 19](https://user-images.githubusercontent.com/24532/55549637-9e47b380-56d6-11e9-808f-8665e1402ac1.png)

**Comment by georgobermayr** [comment]
@nilshoerrmann No, this not helping either.
@bastianallgeier Very weird indeed. I did some further testing to make it even weirder ;-)
On my localhost wit MAMP and PHP 7.2.8 it works fine!
On the server with PHP 7.2.11 I have the issue. I hope I'm not missing something here, but the two Kirby versions should equally be on the latests RC. Does this in any way make sense?

**Comment by bastianallgeier** [comment]
Could you try to delete the media folder on the server and also make sure that your browser cache is flushed? Is it still happening then?

**Comment by distantnative** [comment]
Any locale config settings or so?

**Comment by georgobermayr** [comment]
Cleaning the folder and cache didn't help. However I found out that this works:

```
              birthday:
                label: Birthday
                type: date
                min: 01.01.1910
                translate: false
                help: The birthday of the athlete.
```

While this is not working:
```
              birthday:
                label: Birthday
                type: date
                min: 01.01.1900
                translate: false
                help: The birthday of the athlete.
```

I can certainly live with that, we don't have that old people anyway ;-) So from my side there is no need to understand this further …
