### ISSUE TITLE
Problem updating structurefield

### ISSUE THREAD

**Issue by kgevaert** [getkirby/kirby#1651]
Problem:
**Updating a structurefield via code doesn't work correctly in some cases. Updates are not shown in panel.**

kirby 3.1

**How to reproduce**
1/ Go to the panelpage with a structurefield. Save the panel page (to be sure everything is saved). Then open and close or browse the structurefield without changing anything in it,  in the panel. Go to another page in panel.
2/ Run code (in frontend form) to update the structurefield
3/ Return to the panelpage with the structurefield. The changes via code are not reflected. There is an orange bottom bar which pops up. When you hit 'revert' the changes appear. When you hit 'save', the changes are definitly lost.

more info
https://forum.getkirby.com/t/problem-updating-nested-structurefield/13646

blueprint

```
fields:
  blocks:
    type: structure
    label: Blocks
    fields:
      name:
        label: Block Name
        type: text
      days:
        label: Days
        type: structure
        fields:         
          date:
            label: Date
            type: date
          registered:
            label: Registered  //this one needs to be updated
            type: number
            default: 0
```

code
```
$updateblocks=[];
$blocks=$accommodationpage->blocks()->yaml();
foreach($blocks as $block){	 				
	for($i=0;$i< count($block["days"]);$i++){ 
		$block["days"][$i]["registered"]=$block["days"][$i]["registered"]+1;
	}
	$updateblocks[]=$block;
}

$accommodationpage->update([
	'blocks' => $updateblocks
]);
```
