### ISSUE TITLE
Date field in structure adds current date/timer per default

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#1652]
**Describe the bug**
A date field in a structure field shows the current date/time per default when I open a new item, even if I did not define it in the blueprint. This value is not saved when I hit add.

**To Reproduce**
```
#blueprint
structuredate:
   type: structure
   label: Structure
   fields:
      datum:
         type: date
      datumdefault:
         type: date
         default: now
      datetime:
         type: date
         time: true
      datetimedefault:
         type: date
         time: true
         default: now
```
2. Click add
3. see all fields filled (do not click in to the fields)
4. click add
5. see empty date and datetime fields

**Expected behavior**
Empty fields if default is not set

**Screenshots**
![structure-date](https://user-images.githubusercontent.com/46723734/55498571-3fd1f500-5644-11e9-99fc-092ed161d9d6.gif)

**Kirby Version**
3.1.2-rc.1
