### ISSUE TITLE
Select field options show empty option (--) even if default is set and field is required

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1664]
**Describe the bug**
In a select field like this:

```
      select_field:
        type: select
        default: architecture
        required: true
        options:
          design: Design
          architecture: Architecture
          photography: Photography
          3d: 3D
          web: Web
```
You can still select the empty option from the select drop-down:
<img width="423" alt="Bildschirmfoto 2019-04-08 um 12 18 48" src="https://user-images.githubusercontent.com/5312492/55716961-8d5db180-59f8-11e9-9550-a52908b76897.png">

**To Reproduce**
1. Create a blueprint with above field
2. Create a new page with that blueprint
3. Try to select another option
4. See empty option

**Expected behavior**
When a default is set and the field is required, do not show empty option.

**Kirby Version**
3.1.2-rc1

https://forum.getkirby.com/t/omitting-the-empty-value-in-a-select-field/13700/7
