### ISSUE TITLE
Card Layout in column breaks site width

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/kirby#1666]
**Describe the bug**
Setting a file sections with large card layout enabled, inside a 1/3 right hand column breaks the width of the panel.

**To Reproduce**
1. Set two columns in a blue print, left 2/3, right 1/3
2. Set a files section in the right  hand column
3. Set layout to card, ratio to 16/9

My files section for reference:

```
heroimagefiles:
  type:                   files
  template:               imagefocus
  headline:               Images
  layout:                 cards
  size:                   large
  image:
    cover:                true
    ratio:                16/9
    back:                 black
```

**Expected behavior**
Card fills the column width.

**Screenshots**

![card-bug](https://user-images.githubusercontent.com/28439755/55745110-6621d700-5a2e-11e9-85ad-34a828598ef4.jpg)

**Kirby Version**
Kirby 3.1.1

**Desktop**
 - OS: macOS High Sierra
 - Opera Browser 58.0.3135.127

**Comment by afbora** [comment]
@distantnative I have few tests on 3.2.5 and this issue about following lines. When I deleted these lines, it fixed in all screen resolutions. To be honest, I don't know exactly what it does and why here 😅 

````css
@media screen and (min-width: $breakpoint-medium) {
  .k-cards[data-size="large"] {
    grid-template-columns: repeat(auto-fill, minmax(32rem, 1fr));
  }
}
````

https://github.com/getkirby/kirby/blob/develop/panel/src/components/Layout/Cards.vue#L45-L49
