### ISSUE TITLE
[Checkboxes field] All Options Appear Deselected When Saved Values Are No Longer Options

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1670]
**Describe the bug**
If you have a `checkboxes` field with 4 options, and all 4 options are selected and saved for a page, if you _remove_ an option from the blueprint, everything will appear deselected in the panel.

**To Reproduce**

1. Add this to a blueprint

```yaml
checkboxes:
  type: checkboxes
  options:
      test1: Test 1
      test2: Test 2
      test3: Test 3
      test4: Test 4
```

2. Check the boxes in this order: `1`, `3`, `4`, `2`. The order seems to somewhat matters for the following steps.

3. Save the page. Refresh the page to confirm that they are all saved. You can inspect the JSON response as well.

<img width="382" alt="Screen Shot 2019-04-10 at 11 29 27 AM" src="https://user-images.githubusercontent.com/417182/55904451-b57a1b80-5b84-11e9-83d6-5b150e3403ef.png">

```json
{
    "code": 200,
    "data": {
        "content": {
            "checkboxes": [
                "test1",
                "test3",
                "test4",
                "test2"
            ]
        }
    }
}
```

4. Modify and save the blueprint to remove "Test 3"

```yaml
checkboxes:
  type: checkboxes
  options:
      test1: Test 1
      test2: Test 2
      test4: Test 4
```

5. Reload the page in the page and inspect the JSON response

<img width="403" alt="Screen Shot 2019-04-10 at 11 31 21 AM" src="https://user-images.githubusercontent.com/417182/55904558-fd00a780-5b84-11e9-9402-2cb6e9064b42.png">

```json
{
    "code": 200,
    "data": {
        "content": {
            "checkboxes": {
                "0": "test1",
                "2": "test4",
                "3": "test2"
            }
        }
    }
}
```

**Expected behavior**
The remaining three options should still be selected (but all four should remain saved in the content file, at least until a different change is made to the panel page and saved).

**Note:** In the response JSON, the checkboxes data has changed from an array `[ ]` of values to a JSON object `{ }` (with numeric keys).

**Kirby Version**
`3.1.2`

**Additional context**
The order that you initially check the boxes and remove an option from the Blueprint can make this issue not occur. For example, if you checked "Test 4" last and removed that one from the Blueprint, then I don't think this happens.
