### ISSUE TITLE
[Panel] Cannot Leave Checkboxes Blank Within Structure (Always Selects Default Option)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1685]
**Describe the bug**
If you have a `checkboxes` field within a `structure` field, you cannot leave all checkboxes unchecked _and_ have a `default` option set. If you uncheck all the options and save the page, the default value will be used. The `checkboxes` field _does not_ behave this way outside of a structure field.

**To Reproduce**
1. Add the following to a page blueprint
```yaml
      mystructure:
        type: structure
        fields:
          myoptions:
            type: checkboxes
            default: optionB
            options:
              optionA: Option A
              optionB: Option B
```

2. Add a structure item, and uncheck the default option (Option B).

<img width="819" alt="Screen Shot 2019-04-15 at 1 40 28 PM" src="https://user-images.githubusercontent.com/417182/56164016-ad571d00-5f84-11e9-9bb5-4577f75df860.png">

3. Click the "Add" button.

<img width="827" alt="Screen Shot 2019-04-15 at 1 40 34 PM" src="https://user-images.githubusercontent.com/417182/56164034-b21bd100-5f84-11e9-8cbc-2bdccc0d1692.png">

4. Save the page.

<img width="817" alt="Screen Shot 2019-04-15 at 1 40 40 PM" src="https://user-images.githubusercontent.com/417182/56164052-b942df00-5f84-11e9-911c-7697e9105aa3.png">

**Expected behavior**
The checkboxes field should have no options selected.

**Kirby Version**
`3.1.2`

**Additional context**
The `checkboxes` field works normally when not within a `structure`.
