### ISSUE TITLE
Microsoft Edge 18 Select generated by blueprints not working 

### ISSUE THREAD

**Issue by maxjonas13** [getkirby/kirby#1687]
Hi,

I’m using Kirby 3 and I’m generating select drop-downs in my panel view with blueprints.
When I want to change a value of this dropdown the orange-pink Save bar doesn’t appear when I’m using edge 18. if I Change another field’s value (not the select) the save bar appears. When I save the page and refresh it the value I’ve selected in the select is reverted to it’s original value.

I’ve installed a fresh Kirby 3 starterkit and tested this with the code on the getkirby docs page found here:
https://getkirby.com/docs/reference/panel/fields/select

```
fields:
  category:
    label: Category
    type: select
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
```

Yet this doesn’t work either.

Some more info:
Kirby 3
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
