### ISSUE TITLE
[Panel] page.template query in text property of a pages section returns default if it contains a hyphen

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/kirby#1719]
I have the following pages section:
```
sections:
  pages:
    type: pages
    text: "{{ page.title }} ({{ page.template }})"
    templates:
      - artist
      - highlight-a
      - highlight-b
```
The listed artist pages show _(artist)_, the others show _(default)_.
