### ISSUE TITLE
Language specific headline and help text for `published` section in pages preset not working

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1732]
**Describe the bug**
Setting a languages specific headline and help text for a `published` section in a pages preset has no effect:

```
title: Site
preset: pages
published:
  headline:
    en: Published Content (online)
    de: Seiteninhalt (online)
  help: Some Text
drafts:
  headline:
    en: Drafts (offline)
    de: Entwürfe (offline)
  help: Some Text
```
In this example, the headline and help text for `drafts` section are show, while the `published` section is just called `Published` and no help text appears. When renaming it to `listed` or `unlisted` it works as expected.

When I rename the section to `listed`, headline and help text work again.

**To Reproduce**
1. Put the above example code into site.yml
2. Visit the Dashboard in the Panel
4. See no headline and help text

**Expected behavior**
The language specific headline and help text should also be shown for the `published` section.

**Kirby Version**
3.1.3

**Desktop (please complete the following information):**
 -  macOS
 - Browser [ safari]
