### ISSUE TITLE
Conditional fields not working on key value options

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1751]
On this sample, conditional fields working great!
````
fields:
  category:
    type: select
    options:
      - A
      - B
      - C
  text:
    type: text
    when:
      category: B
````
But key value options not working like following:
````
fields:
  category:
    type: select
    options:
       A: Option A
       B: Option B
       C: Option C
  text:
    type: text
    when:
      category: B
````

Its need to change `B` to `Option B` to work:
````
when:
      category: Option B
````

**Kirby Version**
3.1.3

**Desktop:**
 - Windows 10 Build 17763.473
 - Chrome 74.0.3729.131
