### ISSUE TITLE
Files directly under /content don't get the language extension automatically when adding languages

### ISSUE THREAD

**Issue by flokuek** [getkirby/kirby#1764]
**Describe the bug**
Inside my `site.yml` I have two tabs with each a files section and a files field. Each files section has its own file template and for every files field I use a query to fetch only the files with the same template (see example below). When I add a default and secondary language to my site the files sections/fields inside my `site.yml` are blank and **don't** show the files anymore. 

I think this issue occurs as the files within `/content` **do not** automatically get the language extension when adding languages. 

This works on every other page except within the `site.yml`. 

Tested with a clean starter-kit 

**To Reproduce**
1. Add this to `site.yml`
```
title: Site

tabs:
  page:
    sections:
      files:
        type: files
        template: image
      img:
        type: fields
        fields:
          image:
            type: files
            query: site.images.template('image')
  seo:
    sections:
      metaFiles:
        type: files
        template: opengraph
      metaImg:
        type: fields
        fields:
          image2:
            type: files
            query: site.images.template('opengraph')
```
2. Inside `config.php` set `'languages' => true`
3. Add a default and secondary language
4. Navigation back to the panel dashboard

**Screenshots**

**Kirby Version**
3.1.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74
