### ISSUE TITLE
Files Blueprint not recognized (“This page has no blueprint setup yet”)

### ISSUE THREAD

**Issue by mshoestrng** [getkirby/kirby#1778]
I created the following files blueprint at /site/blueprints/files/foto.yml

```
title: Foto

fields:
  info:
    label: Titel
    type: text
  copy:
    label: Fotograf / Copyright
    type: text
```
…and added it to my blueprint:

```
title: Ausflugsbericht
tabs:
  allgemein:
    fields:
      [...]

  fotos:
    preset: files
    template: foto
```
But no matter whether I open an existing image or upload a new image and open it, on the image page it always says “This page has no blueprint setup yet”.

(When I create a default.yml as suggested at https://getkirby.com/docs/reference/panel/samples/file it shows the text field fine.)

See also https://forum.getkirby.com/t/files-blueprint-not-recognized/14191

**Kirby Version**
3.1.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 74.0.3729.131
