### ISSUE TITLE
[Panel] help text in sections not working with multiple languages

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#1798]
**Translation of help text not working**

Multilang help text is shown in frontend like this:

`{ "de": "Hilfe!", "en": "Help!" }`

**To Reproduce**

````yaml
# /site/blueprints/sections/contentblocks.yml

headline:
  de: Meine Sektion
  en: My Section
type: pages
status: all
help:
  de: Hilfe!
  en: Help!
````

**Expected behavior**
Help text for current language should be shown correctly

**Screenshots**
![help-text-bug](https://user-images.githubusercontent.com/6228942/58307324-98c93880-7dfe-11e9-8586-0ddcebfb2f8c.png)

**Kirby Version**
3.1.4
