### ISSUE TITLE
[Panel] Date field min/max settings not validated

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1801]
**Describe the bug**
When setting up a date field with min and max values the settings are not validated.

```
published:
  type: date
  required: true
  label: Published On
  min: 2019-01-01
  max: 2019-05-01
```

While the dropdown limits the years to choose from (only if `time: true` is not set), this is not true for the months and days. Also, you can still pick any date using the date picker. What is more, you cannot only pick a date outside this range, you can also save this date without validation kicking in.

**To Reproduce**
1. Put the above field into a blueprint
2. Open/create a page with this blueprint in the Panel
3. Use the date picker to choose a date outside the given range.
4. See the page saving without a complaint.

**Expected behavior**
Dates outside the range should not be pickable nor should they validate.

**Screenshots**
<img width="467" alt="Bildschirmfoto 2019-05-26 um 13 27 21" src="https://user-images.githubusercontent.com/5312492/58381153-3026bb00-7fba-11e9-9e11-5d25db8cac8d.png">

<img width="481" alt="Bildschirmfoto 2019-05-26 um 13 11 54" src="https://user-images.githubusercontent.com/5312492/58381099-c73f4300-7fb9-11e9-9024-15c4d9851850.png">

**Kirby Version**
3.1.4 and feature branch

**Desktop (please complete the following information):**
 - macOS
 - Safari

**Comment by GiantCrocodile** [comment]
This is the original thread about the issue I face: https://forum.getkirby.com/t/how-to-use-min-max-for-date-fields/14376

Thanks for reporting this @texnixe!

**Comment by texnixe** [comment]
If I set `time: true`, the dropdown doesn't even limit the years.

**Comment by bastianallgeier** [comment]
✅

**Comment by GiantCrocodile** [comment]
I downloaded v3.2.1-rc1 and used the above example and my origonal example. I'm still able to select invalid dates and to save them. Am I doing something wrong @bastianallgeier?

```
  published:
    type: date
    time: true
        - step: 1
    required: true
    default: now
    label: Published On
    min: 2019-01-01
    max: 2019-05-01
```

![grafik](https://user-images.githubusercontent.com/6271057/60682109-55002f00-9e92-11e9-93dc-8a347b372229.png)

I tried US and German date format for min/max property.

**Comment by texnixe** [comment]
Hm, I can still enter wrong dates, but at least validation does now kick in when I select a wrong date.

**Comment by GiantCrocodile** [comment]
I get no validation at all @texnixe. Maybe it is related to the `default` option. Try this field:

```
  published:
    type: date
    time: true
        - step: 1
    required: true
    default: now
    label: Published On
    min: 2019-01-01
    max: 2019-05-01
```
