### ISSUE TITLE
"No uploaded files" error on uploading specific files

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1812]
**Describe the bug**
Some files are not able to be uploaded because a "No uploaded files" error is thrown. This must be Windows or PHP 7.x (I think 7.3 or 7.2) specific bug.

**To Reproduce**
1. Create a new default page
2. Try to upload this file (https://send.firefox.com/download/45cc9d7ebef77dce/#VOT4tDtRhx43x3y-U1pkFA, password: kirby)
3. See error

**Expected behavior**
File is uploaded.

**Screenshots**

**Kirby Version**
3.1.4

**Console output**
![grafik](https://user-images.githubusercontent.com/6271057/58572508-1ac0c380-823c-11e9-93cc-6fddab0d05e9.png)
![grafik](https://user-images.githubusercontent.com/6271057/58572519-1e544a80-823c-11e9-9157-32965f190855.png)
![grafik](https://user-images.githubusercontent.com/6271057/58572492-12688880-823c-11e9-9106-edf231247234.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 67.0

**Additional context**
We tried to debug this but we found no reason/solution. See this thread: https://forum.getkirby.com/t/what-does-this-error-on-upload-mean-no-uploaded-files/14380

Issue happens with XAMPP and Wampserver.

**Comment by GiantCrocodile** [comment]
`default.yml`:
```
title: Default Page
preset: page
fields:
  text:
    label: Text
    type: textarea
    size: large
    required: true
  author:
    type: users
    required: true
  sources:
    type: structure
    fields:
        source:
            placeholder: http://google.de/...
            required: true
            type: text
        retrieved:
            placeholder: date
            type: date
            required: true
            label: Retrieved On
  tags:
    type: tags
    required: true
    min: 1
    max: 5
  published:
    type: date
    required: true
    label: Published On
    min: 01.01.2019
    max: 01.01.2019
```
