### ISSUE TITLE
structure modal view too tiny

### ISSUE THREAD

**Issue by dinko** [getkirby/kirby#183]
I find the structure modal view too tiny.

* In the screenshot below, the radio options are cut off and there's no title tag or mouseover. If the options are a bit longer, you can hardly read them.
* A textarea field is also very narrow. It does expand when writing, but, in case of a long text, it expands over the viewport.

![panel-structure-1](https://cloud.githubusercontent.com/assets/61015/5916812/b2a9a8ae-a615-11e4-99c0-57093b3e47af.png)

![panel-structure-2](https://cloud.githubusercontent.com/assets/61015/5916813/b42ac3e8-a615-11e4-97d7-68fb41b249a5.png)

**Comment by puckey** [comment]
(I am also coping with the same problem - would really appreciate a fix for this)

**Comment by ausminternet** [comment]
With 2.0.6 came "custom panel stylesheets" and you can change the width via you own stylesheet. So you can adjust the width to your needs.

**Comment by puckey** [comment]
As far as I can see the height of textfields are being set through their style property by javascript..

**Comment by dinko** [comment]
Thx, I'll give it a try.

@puckey: maybe set some ```max-height```, if necessary with ```!important```?

**Comment by puckey** [comment]
Adding the following css using the custom panel stylesheets improved things for me:

assets/css/custompanel.css:
```css
.modal-content {
  max-height: 90vh;
  overflow-y: scroll;
  width: 66.66vw;
  padding: 0 1.5em 0 1.5em;
  background: #efefef;
}
```

In site/config/config.php:
c::set('panel.stylesheet', 'assets/css/custompanel.css');

**Comment by dinko** [comment]
Excellent, thx!

I wrapped it in a media query (works fine below that) and added some css to fix the buttons in case of overflow:

```css
@media screen and (min-width: 50em) {
    .modal-content {
        max-height: 90vh;
        overflow-y: scroll;
        width: 66.66vw;
        padding: 0 1.5em 1.5em 1.5em;
        background: #efefef;
    }

    .modal-content .form {
        position: relative;
    }

    .modal-content .buttons {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        margin: 0;
        padding: 1em;
        text-align: center;
        background-color: #fff;
        background-color: #EFEFEF;
    }

    .modal-content .buttons .btn-cancel,
    .modal-content .buttons .btn-submit {
        float: none;
        display: inline-block;
        margin: 0 1em;
    }
}
```
