### ISSUE TITLE
[Panel] Field options broken (regression in 3.2.0-rc1)

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#1835]
**Describe the bug**
On a page with multiple fields with options (select, multiselect, tags), the options of the first field are copied for all fields with options, ignoring the field's settings.

**To Reproduce**
```yml
columns:
  primary:
    sections:
      context:
        type: fields
        fields:
          category:
            type: select
            label: Kategorie
            options:
              - Print
              - Web
              - App
            translate: false
          period:
            type: multiselect
            label: Zeitraum
            sort: true
            options: api
            api:
              url: '{{ kirby.url }}/hananils/years'
              fetch: years
            translate: false
```

The period field fetched a list of years (the fetch url works fine).

**Expected behavior**
Each field should show it's own options.

**Screenshots**

<img width="632" alt="grafik" src="https://user-images.githubusercontent.com/25466/59018276-d047d400-8845-11e9-9e04-19adeabf0b68.png">

Choosing a category:

<img width="636" alt="grafik" src="https://user-images.githubusercontent.com/25466/59018298-df2e8680-8845-11e9-905f-93f84c785608.png">

Choosing a date range:

<img width="630" alt="grafik" src="https://user-images.githubusercontent.com/25466/59018419-2452b880-8846-11e9-8603-819bd64b9f68.png">

Changing the order of the field makes them all display the options of the period field.

**Kirby Version**
Kirby 3.2.0-rc1, **this does not happen in 3.1.4.**
Using latest Firefox on macOS Mojave.
