### ISSUE TITLE
Provide scrollable and draggable textarea fields

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1838]
**Describe the bug**
It would be nice if textarea fields are scrollable and draggable as described in this post: https://forum.getkirby.com/t/textarea-field-no-scrolling-no-draggable-size/14508

**To Reproduce**
```
fields:
  text:
    label: Text
    type: textarea
    size: large
    required: true
```

**Expected behavior**
The browsers default behaviour for textarea input fields should be kept. It would be nice to be able to drag textarea fields regarding height and width and to be able to scroll inside them to prevent big textarea fields to become very large. If the input field is too large, you have to scroll the page anyway to see the whole content of the textarea field. Maybe this should be a customizable/configurable feature - I'm not sure.

**Kirby Version**
Kirby v3.2.0 rc2
