### ISSUE TITLE
[Panel] Broken *back* button in `pages dialog`

### ISSUE THREAD

**Issue by steirico** [getkirby/kirby#1841]
**Describe the bug**
The `pages field` allows to select any existing page following the structure of the site with all existing pages by the means of the `pages dialog`.  The `pages dialog` provides a *back* button in the upper left corner. Clicking this button  brings the dialog always back to its top-level.

**To Reproduce**
1. Setup a kirby project 
2. Add a page with a sub page which has another sub page and so on... In my test case I named them `Test01`, `Test02`, `Test03`.
3. Add a `pages` field to a blueprint:
```yaml
title: Site
columns:
  - width: 1/2
    sections:
      fields:
        type: fields
        fields:
          test-pages:
            type: pages
```
4. Click on field's *Select* button  in order to open the `pages dialog`.
5. Follow the sub pages structure created in (2).
6. Clicking on the *back* button in the upper left corner brings the dialog back to its top-level.

![pages-dialog-bug](https://user-images.githubusercontent.com/10421363/59148077-177bc380-8a04-11e9-897e-a39ba41a2d4a.gif)

**Expected behavior**

Seen https://github.com/getkirby/kirby/blob/master/panel/src/components/Dialogs/PagesDialog.vue#L108, I expect to go up exactly one level when clicking on the *back* button:

![pages-dialog-fix](https://user-images.githubusercontent.com/10421363/59148091-53168d80-8a04-11e9-8a7f-adcd2806b27e.gif)

**Kirby Version**

3.2.0-rc2
3.1.4
