### ISSUE TITLE
Tiny card setting does not work in columns

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/kirby#1848]
**Describe the bug**
Tiny card setting does not work in columns

**Steps to reproduce the behavior:**
split a blueprint into half columns, put a files field in a column, set it to tiny size.

**Expected behavior**
Card should be much smaller then it is. Tiny only seems to work in a full panel width column or with no columns set at all. 

**Screenshots**
![tiny](https://user-images.githubusercontent.com/28439755/59263299-b0932000-8c38-11e9-88c1-42f6a47536ca.jpeg)

**Kirby Version**
3.1.x

**Desktop:**
 - osx
 - Opera / Vivaldi

**Comment by afbora** [comment]
I can't reproduce on 3.1.0 and 3.2.4

![FireShot Capture 758 - Animals - Mægazine_ - http___localhost_test_kirby_1821_p](https://user-images.githubusercontent.com/3393422/64983973-6cb05680-d8ca-11e9-8b9c-23794bac83de.png)

```
columns:

  - width: 1/2
    fields:
      cover1:
        type: files
        multiple: false
        layout: cards
        size: tiny

      cover2:
        type: files
        multiple: true
        layout: cards
        size: tiny
        
  - width: 1/2
    fields:
      cover3:
        type: files
        multiple: true
        layout: cards
        size: tiny

      cover4:
        type: files
        multiple: true
        layout: cards
        size: tiny
```

Have you used `width` property on `files` field?
