### ISSUE TITLE
[Panel] Error when "image: false" in pages section 

### ISSUE THREAD

**Issue by legowhales** [getkirby/kirby#1864]
Hey,

Since RC-3, I get an error when I set "image: false" in pages sections' blueprints:

```yaml
sections:
  notes:
    type: pages
    image: false
    ...
```

![Capture d’écran 2019-06-13 à 23 29 04](https://user-images.githubusercontent.com/19142403/59469173-53fc5480-8e34-11e9-956d-aca7e874408d.png)
