### ISSUE TITLE
Multiselect field gets skipped when using tab

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/kirby#1880]
**Describe the bug**
When navigating in the Panel with tab, a multiselect field will be skipped.

**To Reproduce**
1. Create a blueprint for a page with a simple text field and a multiselect field, e.g:

```
  text:
    label: Text
    type: text
  multiselect:
    label: Multiselect
    type: multiselect
    options: query
    query: site.children.published
```

2. Go to 'Panel'
3. Click in the textfield so the focus is on this field
4. Press tab
5. Focus will skip the multiselect field and go the the next element

**Expected behavior**
Focus should go to the multiselect field.

**Kirby Version**
3.2.0

**Desktop:**
 - OS: macOS Sierra 10.12.6
 - Browser: Firefox
 - Version: 67.0.4
