### ISSUE TITLE
Default value not working for select field

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1888]
Default value for select field not working

https://getkirby.com/docs/reference/panel/fields/select#default-value

I tried sample blueprint on Kirby 3.2.0 Starterkit like that:

```
fields:
  category:
    label: Category
    type: select
    default: architecture
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
```

**Kirby Version** 3.2.0

**Console output**
No errors on console output

**Desktop**
 - Windows 10
 - Google Chrome 75.0.3770.100
