### ISSUE TITLE
Setting `image: false` in pages/files field within structure field throws error

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#1891]
**Describe the bug**
When setting the image property to false in a files or pages field within a structure field, the Panel throws the error

> Invalid value for "image"

Example blueprint field definition:

```
    audio:
        label: Audiobeispiele
        type: structure
        fields:
            titel:
                label: Titel
                type: text
                width: 1/3
            desc:
                label: Beschreibung
                type: text
                width: 1/3
            audio:
                label: Audio-Datei
                type: pages
                image: false
                query: page.children
                multiple: false
                width: 1/3
```
**To Reproduce**
1. Create a blueprint with the above field definition
2. Create/open a page with that field definition and try to add a structure item

**Expected behavior**
The image property should work inside a structure field context the same way as outside of this context.

**Kirby Version**
3.2.0

**Additional context**
If the image property is not set, the Panel uses the file url as image source no matter what file type is used, which doesn't make sense. I'll create a new issue for that.
