### ISSUE TITLE
404 exception with change email address

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1905]
When you confirm a new email address (which is same as the old/previous one), you get this exception in Kirby 3.2.1-rc.1:

code: 404
exception: "Exception"
file: ""
line: 153
message: "No route found for path: \"null\" and request method: \"GET\""
route: null
status: "error"

I think this issue wasn't there with 3.2.0.

**Comment by bastianallgeier** [comment]
I cannot reproduce this.

**Comment by GiantCrocodile** [comment]
Is this maybe related to having an user model @bastianallgeier?

`admin.yml`:
```
title: Administrator
description: Can do everything and anything
fields:
    source:
        placeholder: http://google.de/...
        required: true
        type: text
```
