### ISSUE TITLE
Special Characters Sorting Issue on Sections

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1913]
I'm using Turkish language and there are some special characters in our language (Ç,Ğ,İ,Ö,Ş,Ü).
If title or sorting field have these characters, sorting not working properly.

**Blueprint**
```
customSection:
    type: pages
    headline: Custom Section
    sortBy: title asc
```

**Screenshots**
![FireShot Capture 704 - PixelShop - http___pixelshop com_panel_site](https://user-images.githubusercontent.com/3393422/61113802-b8dcb600-a497-11e9-9949-800bad486102.png)

**Expected sort**

1. Katalog
2. Kategoriler
3. Özellikler
4. Üretici Firmalar
5. Yorumlar

Tried following setting locales but I didn't get the result I expected:

```
return [
    ...
    'locale' => [
        'tr_TR'
    ]
    ...
];

return [
    ...
    'locale' => [
        LC_ALL  => 'tr_TR.utf-8',
    ],
    ...
];
```

**Kirby Version**
3.2.2

**Desktop:**
 - Windows 10
 - Chrome 75.0.3770.100 (64 bit)

**Comment by lukasbestle** [comment]
PHP's [`array_multisort()` function](https://www.php.net/manual/en/function.array-multisort.php), which we use internally for sorting, doesn't respect the locale by default. It has a special flag called `SORT_LOCALE_STRING` for that. We don't pass it by default because it caused all sorts of issues in the past and therefore should only be used explicitly by the user.

Please try the following (where the `5` is the internal PHP value of `SORT_LOCALE_STRING`):

```yaml
customSection:
    type: pages
    headline: Custom Section
    sortBy: title 5
```
