### ISSUE TITLE
More meaningful error message, if fields keyword is missing in a fields section

### ISSUE THREAD

**Issue by trych** [getkirby/kirby#1935]
If I have a blueprint file containing a section that is missing the `fields` keyword like this:

```yaml
sections:
  content:
    type: fields
      title:
        type: text
      text:
        type: textarea
```

then I get the following error in a panel page that contains the erronous type of page:

```text
The section "projects" could not be loaded: Illegal offset type in isset or empty
```

This would require a more meaningful error message for a user to understand what actually causes the error.

Edit: [problem discussed in the forums](https://forum.getkirby.com/t/section-could-not-be-loaded/15014)
