### ISSUE TITLE
Multilanguage help in files field

### ISSUE THREAD

**Issue by sebastianberns** [getkirby/kirby#1942]
**Describe the bug**
Help texts of a files field in different languages are not displayed correctly. Instead of displaying a specific translation, the complete help option is shown as unprocessed JSON.

**To Reproduce**
1. Include a files field in a page blueprint
```
type: files
headline:
  en: Files
  de: Dateien
help:
  en: English help
  de: Deutsche Hilfe
  ```
2. Go to panel

**Expected behavior**
Only the translation of the user’s selected language should be visible.

**Screenshots**
![output](https://user-images.githubusercontent.com/2394415/61708910-4baa0a00-ad4e-11e9-8d26-5ef7d708eed6.png)

**Kirby Version**
3.1.4

**Console output**
No errors, only regular GET requests.
