### ISSUE TITLE
[Panel] DatetimeField: sub-props for date/time parts

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#195]
e.g.

```
      date:
        label: Date
        type: datetime
        time:
          hours: 24
```
