### ISSUE TITLE
First time use of Toggle is broken in a structured field

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1950]
**Describe the bug**
Given this structured field:

```
      sources:
        when:
          has_sources: true
        type: structure
        fields:
          is_url:
            type: toggle
            default: false
            label: URL?
          name_url:
            type: url
            required: false
            when:
              is_url: true
          name_other:
            type: text
            required: false
            when:
              is_url: false
```

One of both fields is missing on first time:
![grafik](https://user-images.githubusercontent.com/6271057/61984301-1890a080-b004-11e9-95b7-107efd384029.png)

**To Reproduce**
You have to toggle at least once to make sure that one of the both fields (`name_url` or `name_other`) is shown. I think this is not expected behavior or designed like this on purpose.

**Expected behavior**
Either `default` triggers or not even `default` is required to see the field which is enabled when the toggle is off.

![grafik](https://user-images.githubusercontent.com/6271057/61984390-745b2980-b004-11e9-8ba1-2f082944d170.png)

**Kirby Version**
3.2.2

**Desktop (please complete the following information):**
Windows 10, latest FireFox
