### ISSUE TITLE
Overlapping panel columns when using column width 1/6

### ISSUE THREAD

**Issue by trych** [getkirby/kirby#1958]
**Describe the bug**
In the blueprints, if you create a three column layout including a column width of `1/6`as shown below, there is a layout bug with overlapping columns.

**To Reproduce**
Set up a blueprint as follows and open its page in the panel:

```yaml
title: Layoutbug

columns:

  leftcolumn:
    width: 1/2
    type: fields
    fields:
      left:
        type: text

  midcolumn:
    width: 1/6
    type: fields
    fields:
      mid:
        type: pages

  rightcolumn:
    width: 1/4
    type: fields
    fields:
      right:
        type: pages
```

**Expected behavior**
No overlapping in the layout.

**Screenshots**
![20190730-140618_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/62127792-37788680-b2d3-11e9-964e-ac03c1eeafe3.png)

**Kirby Version**
3.2.2

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: All of Chrome, Firefox, Safari
 - Version: lastest versions

**Comment by lukasbestle** [comment]
The three columns don't add up to 100 %, but to 91.67 %. Have you tried if it works if you choose widths that add up?

**Comment by trych** [comment]
If I change it to

```yaml
title: Layoutbug

columns:

  leftcolumn:
    width: 1/2
    type: fields
    fields:
      left:
        type: text

  midcolumn:
    width: 1/6
    type: fields
    fields:
      mid:
        type: pages

  rightcolumn:
    width: 2/6
    type: fields
    fields:
      right:
        type: pages
```

I get this:
![20190730-141703_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/62128467-cd60e100-b2d4-11e9-8024-e99e50f6c51c.png)

Edit: Also, if it did not add up to 100%, I still would expect no overlapping to happen, but to just end up with the columns not filling the page all the way to the right.
