### ISSUE TITLE
Disabled nested structure issue: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1960]
I'm using disabled structure for customer order details/items like readonly.
As you will see screencast, disabled text input can focus but disabled structure field can't focus and error thrown.

**Sample Blueprint**
```
fields:
    addresses:
        label: Addresses
        type: structure
        disabled: false
        fields:
            street:
                label: Street
                type: text
                disabled: true
            zip:
                label: ZIP
                type: text
            city:
                label: City
                type: text

            nested:
                label: Nested Addresses
                type: structure
                disabled: true
                fields:
                    street:
                        label: Street
                        type: text
                    zip:
                        label: ZIP
                        type: text
                    city:
                        label: City
                        type: text
```

**Screencast**

![structure](https://user-images.githubusercontent.com/3393422/62191822-06ed2700-b37d-11e9-8ad6-e1edd074ae6d.gif)

**Kirby Version**
3.2.3-RC.1

**Console output**

> app.js:1 TypeError: Cannot read property 'focus' of undefined
>     at a.focus (app.js:1)
>     at a.focus (app.js:1)
>     at a.focus (app.js:1)
>     at a.<anonymous> (app.js:1)
>     at Array.<anonymous> (vendor.js:41)
>     at le (vendor.js:41)

**Desktop:**
 - Windows 10
 - Chrome 75.0.3770.142
