### ISSUE TITLE
[Panel] Structure Preview For Multiselect Field Just Shows "…"

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1996]
**Describe the bug**
When using a `multiselect` field within a `structure` field, the preview is broken and just shows "…". If this is switched to a `tags` field, the preview looks as expected.

```yaml
bundles:
  label: Bundles
  type: structure
  fields:
    includedAddonIDs:
      label: Included Add-On IDs
      type: multiselect
      options: query
      query:
        fetch: 'page.addons'
        text: "{{ structureItem.name }}"
        value: "{{ structureItem.addonID }}"
```

**Screenshots**

Multiselect
<img width="357" alt="Screen Shot 2019-08-09 at 4 07 26 PM" src="https://user-images.githubusercontent.com/417182/62813523-1b899780-bac0-11e9-986d-f552addc7110.png">

Tags
<img width="361" alt="Screen Shot 2019-08-09 at 4 08 14 PM" src="https://user-images.githubusercontent.com/417182/62813532-217f7880-bac0-11e9-8f0a-225194f41c68.png">

**Kirby Version**
`3.2.3`

**Desktop (please complete the following information):**
 - OS: macOS 10.15 Beta (19A526h)
 - Safari 13.0 (15608.1.37)
