### ISSUE TITLE
Disabled toggle field shows always true/enabled

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2004]
**Describe the bug**

![FireShot Capture 728 - Ahmet Bora - Akyüz Plastik S_ - http___shop akyuz com tr_panel_users_DeeaE2bL](https://user-images.githubusercontent.com/3393422/63086235-1c0aae00-bf58-11e9-97fb-b7841bc7e514.png)

Disabled toggle field shows always true/enabled even value is false. Field text right when false but seems to be selected/checked/enabled.

```
fields:
    isProfileCompleted:
        label: Profile Completed
        type: toggle
        translate: false
        default: false
        disabled: true
        text:
            - Not yet
            - Yeah
```

**To Reproduce**
1. Add above blueprint to any page
2. You will see always as true, it will not matter whether the value is true or false.

**Expected behavior**

It should not be selected/checked/enabled when the value is false like that:

![FireShot Capture 729 - Ahmet Bora - Akyüz Plastik S_ - http___shop akyuz com tr_panel_users_DeeaE2bL](https://user-images.githubusercontent.com/3393422/63086223-1614cd00-bf58-11e9-8ad2-5744025103be.png)

**Kirby Version**
3.2.3

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 76.0.3809.100
 - PHP 7.2 / Apache 2.4
