### ISSUE TITLE
structure field - fields type files - upload false ignored in panel

### ISSUE THREAD

**Issue by findthebug** [getkirby/kirby#2030]
**Describe the bug**
Inside a structure field, the files-option **upload: false** is ignored. Outside a structure the option is working as expected.

**To Reproduce**
- Create structure like this.
- Try to upload a file via panel

```yml
logoList:
  label: Logos
  type: structure
            width: 1/2
            columns:
              logoImageLink:
                  width: 1/1
            fields:
              logoImageLink:
                label: Link
                type: url
              logoImage:
                label: Bild
                type: files
                upload: false
                query: site.index.template('image-pool').images
```

**Expected behavior**
Inside Structure, the option should work as defined

**Version**
-  Kirby 3.2.3
 - osx 10.14.5
 - chrome latest
