### ISSUE TITLE
Video Thumbnail in Structure field actually plays video

### ISSUE THREAD

**Issue by moritzebeling** [getkirby/kirby#2040]
**Describe the bug**
When having a `files` field within a `structure` field, and then select a (mp4) video, the video will actually play inside the field preview of the closed structure field. This slows down the performance of the panel.

**To Reproduce**
1. Create a `structure` field like this
```yml
structureField:
  type: structure
  label: Structure
  fields:

    filesField:
      type: files
      label: Files
      image: false
```
2. Upload a mp4 video file and select it from `filesField`
3. Save the page

**Expected behavior**
Instead, the `file-video` icon should be shown, I guess. Or a thumbnail can be queried using the fields `image` property.

**Screenshots**
Icon is shown when editing the structure entry:
<img width="609" alt="icon is shown when editing the structure entry" src="https://user-images.githubusercontent.com/39742729/63706007-b3acae00-c82e-11e9-808a-1f21740ceb8a.png">

Video playback inside the thumbnail, when structure field is closed after editing:
<img width="600" alt="Video playback inside the thumbnail" src="https://user-images.githubusercontent.com/39742729/63706055-cf17b900-c82e-11e9-9034-a48146fbfa16.png">

**Kirby Version**
3.2.3
