### ISSUE TITLE
Text Field “Pattern” Property Doesn't Enforce Rule

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2041]
**Describe the bug**
When trying to use the `pattern` property of a [`text` field](https://getkirby.com/docs/reference/panel/fields/text#field-properties), nothing seems to have any effect.

https://forum.getkirby.com/t/how-to-use-text-field-pattern-property/15416

**To Reproduce**
```yaml
color:
  type: text
  placeholder: '#ffffff'
  converter: lower
  pattern: '/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/'
```

**Expected behavior**
This field should complain about invalid input when typing in something like `test`, but no error is thrown.

**Kirby Version**
`3.2.3`

**Desktop (please complete the following information):**
 - OS: macOS 10.15 Beta (19A536g)
 - Safari 13.0 (15608.2.2)

**Comment by texnixe** [comment]
What does work, though:

```
    fields:
      color:
        label: Color
        type: text
        validate:
          match: "/^[0-9–]+$/m"
```

But this `validate` option is not documented, just came across it again while cleaning up.
