### ISSUE TITLE
User field info broken

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#2050]
**Describe the bug**
User field info does not print strings.

**To Reproduce**
**plain string**
```yaml
sections:
      users:
        type: fields
        translate: false
        fields:
          users:
            type: users
            info: 'NOPE'
```
**string with current object**
```yaml
sections:
      users:
        type: fields
        translate: false
        fields:
          users:
            type: users
            query: kirby.users.role('strategy')
            info: 'NOPE {{ user.email }}'
```

**Expected behavior**
print strings

**Kirby Version**
3.2.3
