### ISSUE TITLE
[Panel] Field validation for length

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#210]
Using following field:
```yml
headline:
  label: Headline
  type: text
  required: true
  minLength: 10
  maxLength: 20
```

When I try to save `123456789 ` (this is not a real whitespace here) with a whitespace at the end the counter above the field would count the whitespace as a char. So I get a not red `10/20` and get an error when trying to save.

Maybe the inline validation (`10/20`) should count a trimmed string?

Another thing I noticed is that if I try to save `1234567890 ` the whitespace is still there until a refresh although the input is trimmed on save.
