### ISSUE TITLE
[Panel] Dropdown "jumps" on select

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2115]
**Describe the bug**
Using the multiselect field type with a list of years, the dropdown "jumps" to the top of the list when selecting an option from the end of the list. It looks as if the dropdown is re-rendered on select.

**To Reproduce**
This is our blueprint, the API return a list of years:

```yml
years:
  type: multiselect
  label: Zeitraum
  sort: true
  options: api
  api:
    url: '{{ kirby.url }}/hananils/years'
    fetch: years
  translate: false
```

**Expected behavior**
The dropdown scroll position should not change. Otherwise it's very hard to select consecutive options.

**Screenshots**
Before selecting:
<img width="926" alt="grafik" src="https://user-images.githubusercontent.com/25466/65031152-09add680-d941-11e9-87ca-977a11b6cfc6.png">

After selecting:
<img width="928" alt="grafik" src="https://user-images.githubusercontent.com/25466/65031279-48439100-d941-11e9-96b5-651b32e7e879.png">

**Kirby Version**
Latest release and current `develop` branch. 

**Desktop**
Latest Firefox on macOS Mojave.
