### ISSUE TITLE
Structure field: preview for toggle field missing

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2126]
**Describe the bug**

The toggle field does not appear to be significant in the structure field.

```yaml
fields:
  toggles:
    label: Toggle Preview
    type: structure
    fields:
      toggle1:
        type: toggle
        default: false
        label: Toggle Off
      toggle2:
        type: toggle
        default: true
        label: Toggle On
      toggle3:
        label: Toggle Nope/Yay
        type: toggle
        text:
            - Nope
            - Yay

```

**To Reproduce**
1. Go to panel
2. Add above structure fields to blueprint
3. Add content to structure and save
4. See messages as `true` or `-`

**Expected behavior**
It should be more meaningful like `On/Off` or custom text as `Nope/Yay`.

**Screenshots**
![FireShot Capture 762 - Chasing waterfalls - Mægazine_ - http___localhost_test_kirby_3 2 5_](https://user-images.githubusercontent.com/3393422/65152116-004f6780-da30-11e9-86ab-f92e024c8fcf.png)

**Kirby Version**
3.2.5-RC.2

**Desktop**
 - Windows 10
 - Chrome 77
