### ISSUE TITLE
Panel Discards Data When Changing Templates with Different Field Types

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2159]
**Describe the bug**  
In the Panel, if you switch a page template from one to another with a field that has a slightly different type (such as `multiselect` -> `tags` or `email` -> `text`), then the value for that field will be discarded.

**To Reproduce**  
1. Create template `foo1`
```yaml
title: Foo 1

options:
  changeTemplate:
    - foo2

columns:
  - width: 2/3
    fields:
      headline:
        label: Foo 1
        type: headline
        numbered: false
      testField1:
        type: multiselect
        options:
          apple: Apple
          blueberry: Blueberry
          banana: Yellow
          red: Red
          blue: Blue
          yellow: Yellow
      testField2:
        type: email
```

2. Create template `foo2`
```yaml
title: Foo 2

options:
  changeTemplate:
    - foo1

columns:
  - width: 2/3
    fields:
      headline:
        label: Foo 2
        type: headline
        numbered: false
      testField1:
        type: tags
        columns: 5
        options:
          apple: Apple
          blueberry: Blueberry
          banana: Yellow
          red: Red
          blue: Blue
          yellow: Yellow
      testField2:
        type: text
```

3. Create a page with `foo1` and select all the options (`apple, blueberry, banana, red, blue, yellow`) and type in `test@example.com` in the email field.
4. Change that page's template to `foo2`

**Expected behavior**  
The data for `testField1` and `testField2` should be preserved.

**Screenshots**  
<img width="902" alt="Screen Shot 2019-09-30 at 12 40 52 PM" src="https://user-images.githubusercontent.com/417182/65910520-b9426a00-e37f-11e9-8ff7-976350cda8bc.png">
<img width="881" alt="Screen Shot 2019-09-30 at 12 45 05 PM" src="https://user-images.githubusercontent.com/417182/65910750-29e98680-e380-11e9-81a0-e1d624f6657f.png">

**Kirby Version**  
`3.2.5`

**Additional context**  
My expectation with the "Change Template" functionality is that the underlying value stored in the file would stay the same and merely be reinterpreted under the new Blueprint configuration. In other words, the same thing that would happen if simply renamed the content file to `foo2.txt` from `foo1.txt`.

For example, if I change any field type (such as `checkboxes`, `tags`, `select`) to simply `text`, I would expect the resulting text field would contain whatever value was originally saved. The `email` field illustrates this breaking at a very simple level.

There's probably some discussion that needs to happen in regards to "extreme" changes (such as changing a `tags` separator), but I think the default should more immediately be "carry over the value as-is" instead of simply discarding it completely.
