### ISSUE TITLE
File fields validation

### ISSUE THREAD

**Issue by tobiasfabian** [getkirby/kirby#216]
Following blueprint setting
```
files: 
  fields:
    x:
      label: left
      type: number
      required: true
      validate:
        num
        min: -20
        max: 60
```

If the input is `0` the system throws an error: `Please fill in all fields correctly`

If the input is `70` the system doesn’t complain, but should.
If the type is `text` instead of `number` (and the input is `70`) the system throws an error (which is correct).

**Comment by distantnative** [comment]
Shouldn't it simply be the following?

```
files: 
  fields:
    x:
      label: left
      type: number
      required: true
      min: -20
      max: 60
```

Though, this is of course irritating, if the actual validate specification doesn't work properly. Will do some testing.
