### ISSUE TITLE
[Panel] Files pagination page label missing and need translation

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2194]
![FireShot Capture 776 - Animals - Mægazine_ - http___localhost_test_kirby_2192_p](https://user-images.githubusercontent.com/3393422/66666665-d61d4e00-ec59-11e9-9fad-5eb0fad61653.png)

**Describe the bug**  

On files pagination, `Page` string doesn't change when switch the language because of  non-translated string. I tried `pageLabel` option but didnt work.

````yaml
sections:
    images:
        type: files
        layout: cards
        template: image
        info: "{{ file.dimensions }}"
        image:
          ratio: 5/4
          cover: true
        min: 1
        size: small
        limit: 3
        pageLabel: Sayfa

````

**To Reproduce**  
1. Go to panel
2. Add above files section to page blueprint
3. Click pagination of center
4. See untranslated `Page` label

**Related Lines**:

https://github.com/getkirby/kirby/blob/develop/panel/src/components/Navigation/Pagination.vue#L94-L108

**Expected behavior**  
I think `pageLabel` should be translated as default and may be implement `pageLabel` option and fixing should be effect all that using `Pagination` component

**Kirby Version**  
3.2.5
