### ISSUE TITLE
[Panel] Toggle Text in Structure Get Squished Very Easily

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2244]
**Describe the bug**  
The new toggle field in a Structure field is super helpful, but the `text` seem kind of unnecessary/cluttered when viewed in the Structure overview.

**Expected behavior**  
I'd be totally okay if the `text` part of the toggle was just completely omitted in the Structure field (or just showed the default on/off, which is much more compact). The `label` is displayed as the table header, and I suspect a majority of times that's sufficient.

**Screenshots**  
<img width="426" alt="Screen Shot 2019-10-22 at 3 23 41 PM" src="https://user-images.githubusercontent.com/417182/67339930-08903c00-f4e1-11e9-9aa2-ac3e0f3188a5.png">

**Kirby Version**  
`3.3.0-rc.1`

**Desktop (please complete the following information):**  
 - OS: macOS 10.15
 - Browser: Safari
 - Version: 13.0.2

**Comment by bastianallgeier** [comment]
The toggle text is no longer wrapped now. You can also disable text entirely in the columns settings: 

```yml
fields:
  structure:
    columns:
      a:
        text: false
      b:
        text: false
      c:
        text: false
      d:
        text: false
    fields:
      a:
        type: toggle
      b:
        type: toggle
        text: this is some long text
      c:
        type: toggle
      d:
        type: toggle
        text: this is some very very very long text
```
