### ISSUE TITLE
[Panel] Multiselect field search input issues

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2287]
**Describe the bug**  
There are 3 errors in the multiselect search input:
1. Search input resetting after each item select with click
2. Search input not working (focus and click issue) when open + select + close + open..
3. `e.text.match is not a function` error when options is non-string

**Sample blueprint:**

````yaml
fields:
  categories:
    label: Categories
    type: multiselect
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
      tech: Tech
      sport: Sport
````

**To Reproduce**  

**Resetting search**
1. Go to panel
2. Edit any page that have multiselect field
3. Try to search and click any item
4. See search input reset (will not reset selecting item with navigations)

**Search input not working**
1. Go to panel
2. Edit any page that have multiselect field
3. Try to search and click any item
4. Close dropdown and open again (may need to repeat several times)
5. See search input will not focused and clickable input area

**e.text.match is not a function error**
1. Go to panel
2. Edit any page that have multiselect field with options that no text like following sample field
3. Try to search

**Sample multiselect field that has no text just values (non string)**

````yaml
year:
    label: Year
    type: multiselect
    options:
      - 2010
      - 2011
      - 2012
      - 2013
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
````

**Expected behavior**  
1. Search input will not reset after select item.
2. Search input should work always
3. Searching should based on values

**Screenshots**  

**Resetting search**
![multiselect](https://user-images.githubusercontent.com/3393422/68314601-7cc50500-00c7-11ea-9823-3a13460fc277.gif)

**Search input not working**
![multiselect2](https://user-images.githubusercontent.com/3393422/68314969-260bfb00-00c8-11ea-96c7-d929f077e434.gif)

**e.text.match is not a function error**
![FireShot Capture 795 - Sandbox - Mægazine - http___localhost_test_kirby_2287_panel_pages_sandbox](https://user-images.githubusercontent.com/3393422/68387666-e13b9f00-016f-11ea-9121-21af7fd49aec.png)

**Kirby Version**  
3.3.0
