### ISSUE TITLE
Toggle field in structure field

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#2291]
When using a Toggle field in a structure and align it to the right the preview is broken and looks a bit strange. It would be nice if aligned to the right that the toggle is right and the text left of it.

## Preview

<img width="1429" alt="Bildschirmfoto 2019-11-07 um 10 46 04" src="https://user-images.githubusercontent.com/2178466/68378471-75940a80-014c-11ea-8cd5-58b709122193.png">

## Testcase

```
diplom:
  label: Diplom
  type: structure
  min: 1
  columns:
    frage:
      width: 4/6
    aktiv:
      width: 2/6
      align: right
  fields:
    frage:
      type: text
      label: "Frage"
      width: 2/3
    aktiv:
      type: toggle
      label: "Frage aktiv"
      default: true
      text:
        - Nein
        - Ja
```
