### ISSUE TITLE
select field with dynamic files options fails on site options

### ISSUE THREAD

**Issue by Thomas-Lebeau** [getkirby/kirby#230]
**kirby version:** 2.1.0 
**panel version:**  2.1.0

I want to take advantage of the new global site files and add a select field with dynamic options to choose from those files.
I used a fresh plainkit to make sure it wasn't because of any custom code.

my `site/blueprints/site.php` looks like this:
```
<?php if(!defined('KIRBY')) exit ?>

title: Page
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
  logo:
    label: Logo
    type: select
    options: images
```

But when I try to select images from the site options in the panel, the select field is empty.
![screen shot 2015-04-02 at 12 34 29](https://cloud.githubusercontent.com/assets/1926949/6961706/4675be8a-d936-11e4-9032-80e9414a8e50.png)

Although:
- using `options: files` doesn't help.
- It work fine on other pages
