### ISSUE TITLE
Clicking background in panel with multiselect focuses on multiselect

### ISSUE THREAD

**Issue by ticoraap** [getkirby/kirby#2308]
**Describe the bug**  

If a blueprint contains a multiselect field (amongst other fieldtypes). When the user clicks anywhere on the panel page outside the field (like the grey background), the browser automatically focusses on the multiselect field. And after that clicking anywhere on the page, including fields, focusses on the multiselect field. 

**To Reproduce**  
1. Ran the command: `composer create-project getkirby/plainkit your-project`
2. In the new plainkit project edited the about.yml blueprint
3. add the following example multiselect from https://getkirby.com/docs/reference/panel/fields/multiselect#example
```
fields:
  categories:
    label: Categories
    type: multiselect
    min: 0 
    max: 4
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
```
4. opened the example.com/panel/pages/about in the browser and clicked on the grey backgrond.

**Screenshots**  
![ding](https://user-images.githubusercontent.com/6599275/68947017-ae6b5980-07b4-11ea-8ac5-aa8666bf66f4.png)

**Kirby Version**  
Version 3.3.0 only

**Desktop (please complete the following information):**  
 - OS: OSX 10.14.6 (18G103)
 - Browser: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
