### ISSUE TITLE
Can't enter space in multiselect search field

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#2340]
**Describe the bug**  
When I type in the search field of a "multiselect" and press the space bar, no space is inserted in the field.

My field blueprint looks like this:

```
      related:
        label: Related Articles
        type: multiselect
        search: true
        options: query
        query:
          fetch: page.siblings.filterBy("template", "article").published
          value: '{{ page.slug }}'
          text: '{{ page.title }}'
```

**To Reproduce**  
1. Edit a page having a multiselect field with search enabled in the panel
2. Focus the field and start typing words
3. Press the space bar
-> No space is inserted

**Expected behavior**  
The search should allow me to enter spaces to separate words.

**Kirby Version**  
3.3.1

**Console output**  
No errors

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Firefox
 - Version: 71
