### ISSUE TITLE
[Panel] Structure field future inspiration

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#236]
You probably already know about Engineer field for Kirby 2. You can pick any ideas from there to use how you like.

*I've come a long way with my field, so I don't expect the ideas here to land in a near version.*

https://github.com/jenstornell/field-engineer
https://forum.getkirby.com/t/engineer-field-v0-8-and-v0-9-tada/7277

# Features

## Clone

See the clone button. It clones the whole item including nested items to a new item.

![image](https://user-images.githubusercontent.com/927011/37340247-c2aabd48-26bd-11e8-8640-27be7f2ead01.png)

## Fieldsets

Good for page builder features where the site is using building blocks to arrange content.

![1ac34c7eb87c40130ee37034a6fab88e6ba983dc_1_690x347](https://user-images.githubusercontent.com/927011/37340477-8ba8d662-26be-11e8-9362-a4c5ccc893b0.png)

**Example of a blueprint that contains both fieldsets but also a nesting structure:**

DOES NOT MATCH THE SCREENSHOT

```yml
fields:
  my_engineer:
    type: engineer
    fieldsets:
      set1:
        fields:
          first:
            label: Engineer
            type: engineer
            fields:
              my_text:
                type: text
              my_image:
                type: image
          second:
            label: Image
            type: image
      set2:
        fields:
          first:
            type: text
          second:
            type: toggle
```

## Sorting

Both the move icon and the arrows work to sort with. In your case I think drag and drop sort will probably be enough.

![image](https://user-images.githubusercontent.com/927011/37340495-97cf2df6-26be-11e8-8cf9-c6926fc31b64.png)

## Image preview

Because there is not extra step to preview, all fields will show what they do inline.

![3191adf9e6634e0bbd75c9a6502403a39d2d8393_1_690x243](https://user-images.githubusercontent.com/927011/37340522-b4349ab2-26be-11e8-9651-754ee61a3f1b.gif)

## Delete warnings

Here is a warning when clicking on delete. It's especially important for nested structures where lots if data will be lost during the operation.

![05550528c354a0f6f4f4e4444930e95d618a0699_1_621x500](https://user-images.githubusercontent.com/927011/37340551-d0892b6a-26be-11e8-9fa0-e00520d117ab.jpg)

![23314e255081d85227c1cafc90340a94fde38443_1_639x500](https://user-images.githubusercontent.com/927011/37340559-d3c948b4-26be-11e8-921b-fdd35bb48484.jpg)

## Grid

Except table and item style I added grid. In this case I set the grid to 4 which means 4 in a row before a break.

![d515128bcb63840f1bf87ac2d789347e4b39ebc8_1_653x500](https://user-images.githubusercontent.com/927011/37340590-eb541bc6-26be-11e8-95fd-1cade9e9db0e.jpg)

## Complex

Here another complex structure that works (when additional plugin fields are added).

![164aa5cac2c6b67e714983681112c7dd2bff64f4_1_608x500](https://user-images.githubusercontent.com/927011/37341087-891a7606-26c0-11e8-8a13-643a79470f34.jpg)

```yml
fields:
  my_engineer:
    type: engineer
    fieldsets:
      hero_images:
        label: Hero + Images
        fields:
          hero:
            label: Hero
            type: hero
            width: 1/3
          images:
            label: Images
            type: images
            width: 2/3
      switch_quickselect:
        label: Switch + Quickselect
        fields:
          switch:
            label: Switch
            type: switch
            width: 1/2
          quickselect:
            label: Quickselect
            type: quickselect
            options: images
            width: 1/2
```

So this proves that all these things are possible. You can also see how the blueprints work.

For Kirby 3.0 I think the most important thing is to keep things you want to add in the future in the back of your head to not put yourself in a corner.

I hope you found this issue useful. Each idea could be an issue, but I'm not sure you need that right now.

Thanks for the word! Great work with the modal free structure so far! 😄 

**By the way, I think you do right in keeping it as one structure field (instead of a table split). Else you may end up with duplicated code when doing more advanced stuff like the above.**
