### ISSUE TITLE
[Panel] Path is not generated when querying files in textarea

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/kirby#2366]
**Describe the bug**  
Getting files with the file button in a textarea via a query from another page, the correct path is not generated.

**To Reproduce**  
1. Create a textarea field with files set to query another pages files, e.g:
```
text:
    label: Text
    type: textarea
    files:
        query: site.find("downloads").files
```
2. Go to the textarea in the Panel
3. Click on the file button and then select a file (from the page "downloads")
4. See file without path to page "downloads": (file: file.pdf)

**Expected behavior**  
The file should be inserted in the textarea with the path to the page "downloads": 
(file: downloads/file.pdf)

**Kirby Version**  
3.3.1

**Desktop**  
 - OS: macOS High Sierra 10.13.6
 - Browser: Firefox
 - Version: 71.0
