### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by fanningert** [getkirby/kirby#237]
Hi,
I have a second date field (`dateto`) in my article.
But when output the date field with a custom formatting (`Y/m/d`), I get the saved formatting.

**Blueprint part:**
```
fields:
  date:
    label: Date from
    type:  date
    required: true
    format: YYYY-MM-DD
  dateto:
    label: Date to
    type: date
    required: true
    format: YYYY-MM-DD
```

**Template-code:**
```
Date1: <?php echo $subarticle->date('Y/m/d'); ?>
Date2: <?php echo $subarticle->dateto('Y/m/d'); ?>
```

**Result:**
```
Date1: 2015/01/15
Date2: 2015-01-18
```
