### ISSUE TITLE
Page options by role defaults to false for all roles as long as one is set

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#2370]
Adding the following to a page option

```yaml
options:
  changeSlug:
    blogger: false
```

disables the ability to change the slug for all roles, not only "blogger".

You have to specify

```yaml
options:
  changeSlug:
    *: true
    blogger: false
```

for the permissions to work properly.

**Expected behavior**  
Roles that are not defined in the list should defaults to true as long as `*: false` is not defined.

**Screenshots**  

When logged in with a role of "admin", I can't change the URL whereas this ability is not explicitely disabled for this role in the blueprint.

![Capture d’écran 2019-12-20 à 11 10 28](https://user-images.githubusercontent.com/793344/71247660-7a3a0a00-2319-11ea-853b-eab58876bc1a.png)

**Kirby Version**  
3.3.2
