### ISSUE TITLE
Can't edit page with model in panel

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/kirby#2393]
**Describe the bug**  
When I try to save a page in the panel that uses a custom Model, the following error is thrown:

> The form could not be saved
> 
> Exception: TypeError
>     Argument 1 passed to Kirby\Cms\App::{closure}() must be an instance of Page, instance of ExpertisePage given 

**To Reproduce**  
Here's my page blueprint (expertise.yml):

```yml
title: Expertise

preset: page

icon: 📦

pages:
  template:
    - articles-list
    - contact-form
    - free-text
    - logos-list
    - products
    - product
    - project-card
    - quote

fields:
  seo: fields/seo

  icon:
    label: Icon
    type: text
    required: true
    width: 1/2

  headline:
    label: Headline
    type: text
    help: Displayed below the expertise title
    required: true
    width: 1/2

  teaser:
    label: Teaser
    type: text
    help: Displayed in the expertise teaser
    width: 1/2
    maxlength: 120

  teaserTitle:
    label: Teaser title
    type: text
    help: Expertise teaser “title” attribute (for SEO)
    width: 1/2
    maxlength: 120

  intro:
    label: Intro
    type: markdown
    required: true

  champion:
    label: Champion
    type: users
    max: 1
    default: false
    help: Display a picture & office phone number after the expertise introduction.
```

Model (expertise.php):

```php
<?php

use Kirby\Cms\Page;

class ExpertisePage extends Page {

  public function metaTitleIncludesHierarchy(): bool
  {
    return false;
  }

}
```

**Expected behavior**  
I should be able to save the page like any other.

**Kirby Version**  
3.3.2
