### ISSUE TITLE
[Panel] Implement state blueprint options

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#240]
This should be possible in blueprints one day: 

```    
states: 
    draft: 
        label: Project draft
        description: Project drafts are not public on the site. You can edit without worrying about the results being visible to website visitors.
    listed: 
        label: Published project
        description: Published projects will appear in the project grid
    unlisted: 
        label: Client preview
        description: The project will not be listed in the grid, but you can send its URL to a client to preview it.
```
