### ISSUE TITLE
Date Field does not store the picked date properly

### ISSUE THREAD

**Issue by joernroeder** [getkirby/kirby#2416]
**Describe the bug**  

As reported by a client and replicated in a plainkit the date field does not save the selected value (on GMT+1) after updating to the latest version.

**To Reproduce**  
1. Get the plainkit and modify the following files:

__default.yml__

```yml
title: Default Page
preset: page
fields:
  date:
    label: Date
    type: date
    default: today
  text:
    label: Text
    type: textarea
    size: large
```

__home.txt__

```
Title: Home

----

Date: 2020-02-21

----

Text: 
```

1. Go to the home page in the panel
2. The date field is prepopulated with the correct date `2020-02-21`
2. Choose the 22th feb via the calendar on the right hand side of the date field
3. Open the inspector and save the page.
4. Inspect the params of the `PATCH` request (it send `2020-02-21T23:00:00.000Z` in my case)
5. Confirm that `home.txt` is still stores `2020-02-21`
6. Reload the page and the date field shows `2020-02-21` again

**Expected behavior**  

the text file should store the selected date. `2020-02-22`

**Screenshots**  

![kirby-datefield-bug](https://user-images.githubusercontent.com/270540/73370272-40fb9f00-42b4-11ea-9d1a-24edd31258b5.gif)

**Kirby Version**  
v3.3.3

**PlainKit used**
[plainkit-master-datefield-bug.zip](https://github.com/getkirby/kirby/files/4128871/plainkit-master-datefield-bug.zip)
