### ISSUE TITLE
Default values of some field types are not displayed correctly in the Panel

### ISSUE THREAD

**Issue by SkidX** [getkirby/kirby#2460]
**Describe the bug**  
The default value of some field types is not showed correctly in the Panel when the field is added to an existing page.

Affected field types I discovered so far:
text, textarea, checkboxes, radio, multiselect 

Field types not affected:
toggle

**To Reproduce**  
1. Add a checkboxes field on a blueprint, with a default value
```
fields:  
  categories:  
    label: Categories
    type: checkboxes
    default: architecture
    options:
      design: Design
      architecture: Architecture
      photography: Photography
      3d: 3D
      web: Web
```
2. Open a page using that blueprint in the Panel

**Expected behavior**  
The Architecture checkbox should appear checked, it is not. 

**Kirby Version**  
3.3.3 

**Desktop**  
 - OS: Win10 
 - Browser: Chrome
 - Version:  79

**Additional context**  
Inside Builder blocks, the default value of text, textarea and select fields is enforced correctly, while checkboxes, radio and multiselect fail as well.
