### ISSUE TITLE
Textarea upload - Cannot read property 'drop' of undefined

### ISSUE THREAD

**Issue by yoanmalie** [getkirby/kirby#2482]
**Describe the bug**  
When uploading a file with drag and drop on a textarea, with the uploads option disabled I get this error :

On Chrome : 
> Cannot read property 'drop' of undefined

On Firefox :
> this.$refs.fileUpload is undefined

**EDIT**: Not tested elsewhere.

**To Reproduce**  
Here my blueprint :
```
fields:
  address:
    label: Adresse
    type: textarea
    buttons: false
    counter: false
    icon: home
    spellcheck: false
    uploads: false
```

**Expected behavior**  
A clear information that we can't upload here because the feature it's disabled on this field. Without error log.

**Kirby Version**  
3.3.4

**Console output**  
On Chrome :
```
TypeError: Cannot read property 'drop' of undefined
    at a.onDrop (app.js:1)
    at oe (vendor.js:41)
    at HTMLTextAreaElement.n (vendor.js:41)
    at HTMLTextAreaElement.Ni.i._wrapper (vendor.js:41)
errorCaptured @ app.js:1
```

On Firefox :
```
TypeError: "this.$refs.fileUpload is undefined"
    onDrop http://example.com/media/panel/05181df89a02def7a50270e532e61bbf/js/app.js:1
    oe http://example.com/media/panel/05181df89a02def7a50270e532e61bbf/js/vendor.js:41
    n http://example.com/media/panel/05181df89a02def7a50270e532e61bbf/js/vendor.js:41
    _wrapper http://example.com/media/panel/05181df89a02def7a50270e532e61bbf/js/vendor.js:41
```
**Desktop:**  
 - OS: macOS
 - Browser: Firefox
 - Version: 72.0.2

Also tested on Chrome 79.0.3945.130
