### ISSUE TITLE
Date field off-by-one when `time: false`

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2566]
**Describe the bug**  
When you save a `date` field, the actual saved value is off by one day:

![image](https://user-images.githubusercontent.com/5570098/78994320-6de7f000-7b48-11ea-8b8a-7c6293f3e65d.png)

**To Reproduce**  
Use this blueprint:

```yml
num: '{{ page.date.toDate("Ymd") }}'

tabs:
  content:
    preset: page
    fields:
      date:
        type: date
        default: now
        required: true
```

...and save the page. This doesn't happen if I have `time: true` in the field's blueprint, though.

**Expected behavior**  
The dates should match.

**Kirby Version**  
3.3.5
