### ISSUE TITLE
Can not changeTemplate to the default template

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2567]
**Describe the bug**  
You can use the `changeTemplate` functionality to switch from the default template to another one, but you can't do the opposite.

**To Reproduce**  
Create a default template:

```yml
title: Default Page
options:
  changeTemplate:
    - foo
```

...and template `foo`:

```yml
title: Foo
options:
  changeTemplate:
    - default
```

You'll be able to select the default template in the "Change template" dialog, but once you click "Change," nothing happens.

**Expected behavior**  
The content file should be renamed from `foo.txt` to `default.txt`.

**Kirby Version**  
3.3.5
