### ISSUE TITLE
Tab content wrong

### ISSUE THREAD

**Issue by owzim** [getkirby/kirby#2584]
**Describe the bug**  

The following `site.yml` tab structure fails and only shows the content of the last tab.

```yml
title: Site

tabs:

  settingsfoo:
    label: Settingsfoo
    icon: cog

    sections:
      content:
        type: fields
        fields:
          foo:
            label: foo
            type: text

  settingsbar:
    label: Settingsbar
    icon: cog

    sections:
      content:
        type: fields
        fields:
          bar:
            label: bar
            type: text

```

![kirby-tabs](https://user-images.githubusercontent.com/1720088/80099205-6411b400-856e-11ea-841f-9d8869abb451.gif)

**To Reproduce**  
1. ceate a `site.yml` with the content form above
2. goto the panel, see both tabs containing the content of the last

**Kirby Version**  

`3.3.5`

**Desktop (please complete the following information):**  
 - OS: macOS 10.14.6
 - Browsers: 
   - Chromium 81.0.4036.0 (Developer Build) (64-bit)
   - Firefox 75.0 (64-bit)
   - Firefox Dev 75.0 (64-bit)

**Additional context**  

This is a simplified example, it also failed when using columns inside each tab.

The slightly more complex setup involved a dashboard (like from the docs examples) in the first tab, and additional fields in the second and third tab. In this case the first tab displays correclty and the second and third tab showed behavior like described above.
