### ISSUE TITLE
Field validation doesn't support string syntax

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2586]
The [Kirby Guide](https://getkirby.com/docs/guide/blueprints/fields#validating-fields__using-validators) shows that a field's `validate` property should be an array, like:
```yaml
text:
  type: text
  validate:
    ip
```

However, the examples for the validators themselves show it being a string. This is for the [integer validator](https://getkirby.com/docs/reference/system/validators/ip):
```yaml
fields:
  example:
    label: Example field
    type: text
    validate: ip
```

And it seems like Kirby (3.3.5) refuses any value that isn't an array.
> Argument 2 passed to Kirby\Toolkit\V::errors() must be of the type array, string given, called in /var/www/html/kirby/src/Form/Field.php on line 328

<img width="593" alt="Screen Shot 2020-04-23 at 10 17 04 AM" src="https://user-images.githubusercontent.com/417182/80129188-95c55380-854b-11ea-9b1f-6342f96dfff0.png">

Also affects _most_ of the other validators, such as [integer](https://getkirby.com/docs/reference/system/validators/integer),  [date](https://getkirby.com/docs/reference/system/validators/date), [email](https://getkirby.com/docs/reference/system/validators/email), etc.
