### ISSUE TITLE
[Panel / CMS] Structure-Field/Page Sections

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#259]
One idea I had playing around with the new structure-field esp. with the *kitchensink/restaurant-menu* example was: Why not introducing something like **sections/groups** for the structure field. The whole `restaurant-menu.yml` would then boil down to something like:

```yml
fields:
  dishes:
    label: All Dishes
    type: structure
    sectionsField: section
    fields:
      dish:
        label: Dish
        type: text
        width: 1/3
      description:
        label: Description
        type: text
        width: 1/3
      price:
        label: Price
        type: number
        prefix: €
        step: 0.01
        width: 1/3
      section:
        label: Section
        type: select
        options:
          starters: Starters
          pasta: Pasta
          meat: Meat
          desert: Desert
```

The panel then automatically splits the structure field exactly how it looks now. This would also make drag'n'drop possible among groups which is really nice and intuitive imho.

***

Thinking further: This is not only useful when it comes to the structure-field but also to pages. Instead of manually splitting them in the blueprint with `sections` they could be automatically splitted by a defined field.

A special case would be the new publishing-state where the `events.yml` could be written like:
```yml
  allPages:
    type: pages
    headline: Unpublished events
    sectionsField: page.publishingState
    create: event
    item:
      info: "{{ page.from.toDate('d.m.Y') }} - {{ page.to.toDate('d.m.Y') }} / {{ page.location }}"
```

Just dreaming a bit :)
Dennis
