### ISSUE TITLE
Text "No" and "Yes" in toggle

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/kirby#2674]
If `No` and `Yes` is used as text in a toggle, it shows as `false` and `true` in the Panel. If it's written with quotation marks `"No"` and `"Yes"` it shows as `No` and `Yes`.

**To Reproduce**  
1. Build a toggle field with `No` and `Yes` as text:
```
toggle:
  label: Toggle
  type: toggle
  text:
    - No
    - Yes
```
2. Go to the Panel
3. The text is shown as `false` and `true`
4. Change the text to `"No"` and `"Yes"`:
```
toggle:
  label: Toggle
  type: toggle
  text:
    - "No"
    - "Yes"
```
5. The text is shown as `No` and `Yes`

**Expected behavior**  
It shouldn't be necessary to wrap `No` and `Yes` in quotation marks?

**Kirby Version**  
3.3.5

**Desktop (please complete the following information):**  
 - OS: macOS 10.15.5
 - Browser: Firefox
 - Version: 77.0.1
