### ISSUE TITLE
[3.4.0 RC2] `image: icon` feature for pages creates error message

### ISSUE THREAD

**Issue by nimi09** [getkirby/kirby#2680]
**Describe the bug**  
The new `image: icon` feature for pages creates the following error msg: `Der Bereich "listed_pages" konnte nicht geladen werden: Access to non-existing property icon on array `

**To Reproduce**  
```
tabs:
  pages:
    label: Pages
    icon: page     
    columns:
      - width: 1/3
        sections:
          listed_pages:
            headline: Public Pages
            type: pages
            status: listed
            layout: list
            image: icon
```

**Expected behavior**  
pages display icons instead of images in the List-View

**Kirby Version**  
3.4.0-rc.2
