### ISSUE TITLE
Structure Field saves horizontal line in content file

### ISSUE THREAD

**Issue by mullema** [getkirby/kirby#2702]
**Describe the bug**  
Using the horizontal line to separate fields from each other in a structure field results in `line: null` being saved in the content file.

**To Reproduce**  
1. Use a horizontal line in a structure field
```yaml
lineTest:
  type: structure
  fields:
    title:
      type: text
    line-a:
      type: line
    description:
      type: text
```
2. add a new entry
3. check the content file
```
Linetest:

- 
  title: test
  description: test
  line-a: null
```
4. Also the structure field preview treats the line as a field

**Screenshots**
![lineok](https://user-images.githubusercontent.com/46723734/87240646-9b7c5800-c41b-11ea-8176-9798926984ba.JPG)

![line](https://user-images.githubusercontent.com/46723734/87240649-9e774880-c41b-11ea-87eb-ee1238d6d4f8.JPG)

**Expected behavior**  
The line not present in the structure field

**Kirby Version**  
3.4.0
