### ISSUE TITLE
Can't filter files section by default template

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2704]
**Describe the bug**  
I have a page that contains both files with blueprint `logo` and files without any blueprint (they use the default one). In my page blueprint, I want to have two sections - one for logos and one for all other files (with the default blueprint).

I tried this:

```yml
sections:
  files:
    type: files
    template: default
  logos:
    type: files
    template: logo
    headline: Logos
```

...but the files section that should show default blueprint files is empty. It only shows files if they have `Template: default` in their meta file. This is bad because files uploaded from elsewhere (a files field's upload button, for example) don't add `Template: default` and therefore don't show in the files section.

**To Reproduce**  
1. Create a blueprint with a files section
2. Set the available blueprints in the section to `default`
3. Files without `Template: default` are not visible

**Expected behavior**  
You should be able to filter a files section by default template and Kirby should never add `Template: default` to files' meta data. The lack of `Template` means it's default.

**Kirby Version**  
3.4.0

**Comment by afbora** [comment]
If I understood correctly, I can say it works properly (almira file uploaded from `bar` section)

@hdodov Don't you think following looks right? 🤔 

````yaml
sections:
  files:
    type: files
    template: default
    headline: Default Template
  logos:
    type: files
    template: logo
    headline: Logos
    headline: Logo Template
  foo:
    type: files
    template: image
    headline: Foo
    headline: Image Template
  bar:
    type: files
    headline: Bar
    headline: No Template
````

![screen-capture-146-Exploring the universe - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/87310521-bd163600-c526-11ea-8936-39ae8fdf4731.png)
