### ISSUE TITLE
NetworkError or t.user.role is undefined on logout from "Your Account"

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#2713]
**Describe the bug**  
Logging out from the path 'Your account' does cause one of these two errors. Other pages work fine. The user is able to create pages, delete pages, edit stuff, etc. No error beside that. Logging out from another path does work.

**To Reproduce**  
1. Go to http://localhost/kirby/panel/account
2. Click the main menu dropdown
3. choose 'Logout'

**Expected behavior**  
No error thrown.

**Screenshots**  

![grafik](https://user-images.githubusercontent.com/6271057/87555694-16609f80-c6b6-11ea-8808-95ebd619cc2c.png)

**Kirby Version**  
Kirby v3.4.0

**Console output**  
see above

**Desktop (please complete the following information):**  
latest FireFox on Windows 10

**Additional context**  
Multilang site with only 1 language defined

There's an admin blueprint with these fields:

```
fields:
    address:
        label: Anschrift
        type: textarea
        buttons: false
    twitter:
        type: text
        label: Twitter Handle
        before: @
```

I did update the name and email address of the user in the panel during this session. Browser cache is emptied on every browser close. Not sure if updating the user is related to this.
