### ISSUE TITLE
[Panel] Required status option for PageSection

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#272]
Currently, we have a logic problem, e.g. see with the events list from the kitchen sink:
<img width="811" alt="screen shot 2018-03-22 at 23 23 40" src="https://user-images.githubusercontent.com/3788865/37801809-457d386a-2e28-11e8-8628-492d94869f12.png">

When adding a new page by hitting the Add button on the published section, a new draft is created which of course then appears in the draft section "unpublished events":
<img width="832" alt="screen shot 2018-03-22 at 23 23 30" src="https://user-images.githubusercontent.com/3788865/37801834-5d92cf14-2e28-11e8-9e74-76a9cc9a4094.png">

That makes sense somehow, but still is completely unintuitive to what you would expect from clicking the button next to the published section.

**Comment by jenstornell** [comment]
This is because you can't add a published event or even a unlisted event. The only thing you can add is the unpublished event.

Therefor the add-buttons on anything but unpublished events makes no sense.

Should it be self aware of that the add button should not be added, or a "flag" in the blueprint to prevent the add button to display? Magic or less magic.

**Comment by distantnative** [comment]
I know why this happens 😉 But yea, the question is what should actually happen.

Magic could be a bit too heavy, so maybe it's in the hand of the developer to then set `create: false`on these sections, @bastianallgeier?

**Comment by jenstornell** [comment]
Or `add: false` to make it match the button label (at least for the en panel).

**Comment by bastianallgeier** [comment]
There are only two options IMHO: 

A.) devs would always have to take care of this themselves by setting `create:false` to avoid logic issues. 

B.) We refactor the pages section and require setting the type of pages, that will be listed: 

```
sections: 
    drafts:
        type: pages
        template: project
        status: draft

    published: 
        type: pages
        template: project
        status: listed

    unlisted: 
        type: pages
        template: project
        status: unlisted
```

In this case only when the status is draft, the create button will be shown. I think this would simplify this issue a lot.
