### ISSUE TITLE
[Panel] Link in tab jumps to first tab before following route

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2742]
Kirby 3.4.0 reintroduced the issue #1389.

**Sample reproduced blueprint for starterkit**

````yaml
title: Sandbox

tabs:
  content:
    label: Content
    fields:
      text:
        type: textarea
        size: huge
        
  test:
    label: Test
    sections:
      notes: sections/notes
````

**Kirby Version**  
3.4.0
