### ISSUE TITLE
Permission access.site causes the panel to crash

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2760]
**Describe the bug**  
I'm finally getting into user blueprints and at some point, the panel started crashing. After digging into it, the cause appears to be the `site: false` access setting:

```yml
title: Editor
permissions:
  access:
    site: false
```

This causes the whole browser tab to become unresponsive. Perhaps it falls in some infinite loop?

**Kirby Version**  
3.4.0
