### ISSUE TITLE
Using toArray() on a multiselect field containing page IDs throws errorException

### ISSUE THREAD

**Issue by till-kammertoens** [getkirby/kirby#2793]
**Describe the bug**  
Using toArray() on a select field containing page IDs throws errorException

**To Reproduce**  

**Screenshots**  
<img width="1536" alt="Screen Shot 2020-08-29 at 22 33 20" src="https://user-images.githubusercontent.com/5666158/91644762-e4c64c80-ea47-11ea-9b06-cf12231005c8.png">

**Kirby Version**  
3.4.2

**Additional context**  

Whoops\Exception\ErrorException thrown with message "Array to string conversion"

Stacktrace:
#18 Whoops\Exception\ErrorException in kirby/src/Cms/Collection.php:211
#17 Whoops\Run:handleError in kirby/src/Cms/Collection.php:211
#16 Kirby\Cms\Collection:not in site/snippets/sections/section-mb-list.php:17
#15 include in kirby/src/Toolkit/F.php:400
#14 Kirby\Toolkit\F:loadIsolated in kirby/src/Toolkit/F.php:377
#13 Kirby\Toolkit\F:load in kirby/src/Toolkit/Tpl.php:35
#12 Kirby\Toolkit\Tpl:load in kirby/config/components.php:288
#11 Kirby\Cms\App:{closure} in kirby/src/Cms/App.php:1359
#10 Kirby\Cms\App:snippet in kirby/config/helpers.php:699
#9 snippet in site/templates/home.php:8
#8 include in kirby/src/Toolkit/F.php:400
#7 Kirby\Toolkit\F:loadIsolated in kirby/src/Toolkit/F.php:377
#6 Kirby\Toolkit\F:load in kirby/src/Toolkit/Tpl.php:35
#5 Kirby\Toolkit\Tpl:load in kirby/src/Cms/Template.php:167
#4 Kirby\Cms\Template:render in kirby/src/Cms/Page.php:1200
#3 Kirby\Cms\Page:render in kirby/src/Cms/App.php:665
#2 Kirby\Cms\App:io in kirby/src/Cms/App.php:1014
#1 Kirby\Cms\App:render in index.php:5
#0 require in /Users/till/.composer/vendor/laravel/valet/server.php:191

**Comment by afbora** [comment]
Can you give a little more detail about the content and blueprint file? Btw could you mean the multiselect field?

**Comment by till-kammertoens** [comment]
Sorry yes, multiselect.
This is in the blueprint:

```
  restrict_list:
    label: Exclude from list
    type: multiselect
    options: query
    query: 
      fetch: page.list_page.first.toPage.children.published
      text: "{{ page.title }}"
      value: "{{ page.id }}"
```

it allows to select the children from a page that's in another field.

**Comment by till-kammertoens** [comment]
The same thing happens when I use the split() method on the same field.
and
`<?= gettype($section->restrict_list()) ?>
`
returns "object" – is that correct?

**Comment by afbora** [comment]
I've tested on Starterkit 3.4.2 with following setup and i am not getting an error. Can you share how you call your `->toArray()` method on the page/template please?

**/site/blueprints/pages/sandbox.yml**

````yaml
fields:
  test:
    label: Exclude from list
    type: multiselect
    options: query
    query: 
      fetch: kirby.page('photography').children.published
      text: "{{ page.title }}"
      value: "{{ page.id }}"
````

**content/sandbox/sandbox.txt**

````txt
Title: Sandbox

----

Test: photography/trees, photography/ocean, photography/mountains, photography/plants
````

**/site/controllers/sandbox.php**

````php
<?php

return function ($page) {
    var_dump($page->test()->toArray());
    var_dump($page->test()->split());
};
````

**Output**

````
array(1) {
  ["test"]=>
  string(79) "photography/trees, photography/ocean, photography/mountains, photography/plants"
}

array(4) {
  [0]=>
  string(17) "photography/trees"
  [1]=>
  string(17) "photography/ocean"
  [2]=>
  string(21) "photography/mountains"
  [3]=>
  string(18) "photography/plants"
}
````
