### ISSUE TITLE
Dynamic API URLs stopped working with ".test" Domains in 3.4.x

### ISSUE THREAD

**Issue by helllicht** [getkirby/kirby#2804]
**Describe the bug**  
Up until 3.4.0 it was able to define [dynamic API urls](https://getkirby.com/docs/reference/panel/fields/checkboxes#options-via-api__dynamic-api-urls) via query builder syntax in checkbox blueprint fields.
E.g. `url: "{{ site.url }}/some.json"`

The important part here is the `site.url` which would dynamically set the site's url for calling the right route. 
In this example it would return a json object from a custom Kirby Route that would populate the checkbox field (see example further below)

This was working perfectly fine until updating to **3.4.0**, where it stopped working. 
Now, when calling the respective page in the backend, it would show the following error:
Locally: `Could not resolve: your-domain.test (Domain name not found)`
~~On Production: `Invalid options format`~~ See Update 2

**To Reproduce**  
1. Create a blueprint field for a page as follows:

```
label: Checkboxes
type: checkboxes
options: api
columns: 2
api:
  url: "{{ site.url }}/some/route.json"
  text: "{{ item.name }}"
  value: "{{ item.id }}"
```

2. Open the respective page in the panel
3. You should see the error described above

**Expected behavior**  
The field should list the checkbox items based on the content of the json from the route

**Kirby Version**  
3.4.0 / 3.4.1 / 3.4.2

---- 

**Update**: At least for local development it seems to be be related to the `.test` Domain. 
Switching the url to a hardcoded `url: "http://localhost:3000/some/route.json"` resolves the issue locally. 

---- 

**Update 2**:
Updated the issue and description as the problems in local/prod are coincidentally and not related to each other.
The `Invalid options` are a result of the **password protection** on the live domain. That's an a different issue in general.

**Comment by afbora** [comment]
If there was no point I missed, I couldn't reproduce the issue on 3.4.2 🤔 

**Blueprint**

````yaml
fields:
  test:
    label: Checkboxes
    type: checkboxes
    options: api
    columns: 2
    api:
      url: "{{ site.url }}/test.json"
      text: "{{ item.text }}"
      value: "{{ item.value }}"
````

**Config**

````php
return [
    'debug' => true,
    'routes' => [
        [
          'pattern' => 'test.json',
          'action'  => function () {
            return json_encode([
                [
                  'value'=> 'APPLE',
                  'text'=> 'Apple'
                ],
                [
                  'value'=> 'INTEL',
                  'text' => 'Intel'
                ],
                [
                  'value'=> 'MICROSOFT',
                  'text' => 'Microsoft'
                ]
            ]);
          }
        ]
      ]
];
````

**Output**

![screen-capture-258-Sandbox - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/92235848-0c406d80-eebd-11ea-8079-f1db204445fa.png)
