### ISSUE TITLE
Files field — fix filename

### ISSUE THREAD

**Issue by mrvicis** [getkirby/kirby#2835]
I suggest fixing the filename in the Files field to keep the content folder clean.
**Example for blueprint:**
```
fields:
  logo:
    type: files
    multiple: false
    query: page.images
    filename: logo
```
If the user wants to replace a file in this field, Kirby will only offer to overwrite that file.
