### ISSUE TITLE
Can't update checkboxes with dynamic options via php

### ISSUE THREAD

**Issue by helllicht** [getkirby/kirby#2841]
**Describe the bug**  
It doesn't seem possible to update checkboxes fields via php api when the options are populated via json api.

**To Reproduce**  

1. Create a blueprint field with a **dynamic** checkbox field via **api** for a page as follows:

```
label: Checkboxes
type: checkboxes
options: api
api:
  url: "{{ site.url }}/some/route.json"
  text: "{{ item.name }}"
  value: "{{ item.id }}"
```

In this example the API would return something like this:

```json
[
  {
    "id": 50,
    "name": "Some"
  },
  {
    "id": 28,
    "name": "Name"
  }
]
```

2. Update the page via php
```
$page->update(['checkboxes' => '50, 28']);
```

3. The page will update, but the "Checkboxes" field won't be updated – it's not added to the pages `txt` file. 

**Expected behavior**  
The passed checkboxes (values 50 and 28 in this example) should be updated. Instead, nothing happens. 

We have tested it with regular (hardcoded) option values, which works as expected:

```
options:
  - value: "50"
    text: Some
  - value: "28"
    text: Name
```

In that case the value for the checkboxes field is updated as expected (20, 30).

**Kirby Version**  
3.4.3

**Closing thoughts**
A possible reason for this behavior might be that Kirby always checks if the provided value is valid before updating the field. In case of the "hardcoded" checkboxes options it knows which values are allowed (50, 28).
But even if the values don't match, Kirby would at least an empty field value in the pages text file (`Checkboxes: `) which doesn't happen with the api – the field isn't updated at all.

**Comment by afbora** [comment]
I've tested on Starterkit 3.4.3 and works great as expected with string and array. 
Have you checked the plugins installed on your system?

````yaml
fields:
  test:
    label: Checkboxes
    type: checkboxes
    options: api
    api:
      url: "{{ site.url }}/some/route.json"
      text: "{{ item.name }}"
      value: "{{ item.id }}"
````

````php
// with string
$page->update(['test' => '50, 28']);

// with array
$page->update(['test' => [50, 28]]);
