### ISSUE TITLE
[Panel] Can't save nested Markdown lists in structure entries

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2865]
**Describe the bug**  
Leading whitespace in structure fields is removed on save, making it impossible to have nested lists.

**To Reproduce**  

1. Create a structure with the following blueprint:

    ```yml
    struct:
      type: structure
      fields:
        text:
          type: textarea
    ```

2. Add the following content manually in the TXT file:

    ```yml
    - 
      text: |
        Test:
        - foo
        - bar
            - baz
            - qux
    ```

3. In the panel, add a new entry with text `Test 2`, for example
4. The resulting structure data is:

    ```yml
    - 
      text: |
        Test:
        - foo
        - bar
        - baz
        - qux
    - 
      text: Test 2
    ```

**Expected behavior**  
The first structure entry should be left intact and you should be able to create fields with leading whitespace.

**Kirby Version**  
3.4.2
