### ISSUE TITLE
Users field wrong href in last added item

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2904]
Related to 3.4.4:

In a `users`-field the last newly added item has a wrong href.

Blueprint:

```
        fields:
          recipients:
            label: Empfänger
            type: users
            query: kirby.collection("recipients")
            text: "{{ user.name }} - {{ user.email }}"
            empty: Noch keine Empfänger ausgewählt
```

When a user from the collection out of the modal dialog is selected, it will be added to the end of list. 
When you click on that newly created entry, it contains a wrong href with another accounts id (which even doesn't exist, and what leads to an error page (`Der Account "D4WR0WSl" wurde nicht gefunden.`).
When you first reload the page and then click on the same entry, everything works and you'll get directed to the correct user page.
