### ISSUE TITLE
Non-admin user cannot change role of another user

### ISSUE THREAD

**Issue by PaulRaschke** [getkirby/kirby#2919]
I have a project running on Kirby 3.4.4 and I'm still facing this issue.
The bug seems to emerge from [`UserPermissions->canChangeRole()`](https://github.com/getkirby/kirby/blob/6112f1cb8ebf9c36e8a9f97ae08acc910ddbc792/src/Cms/UserPermissions.php#L37), where the number of available user roles is checked with [`User->roles()`](https://github.com/getkirby/kirby/blob/6112f1cb8ebf9c36e8a9f97ae08acc910ddbc792/src/Cms/User.php#L685), which always returns only the role of the specified user, unless the logged in user is an admin.

_Originally posted by @PaulRaschke in https://github.com/getkirby/kirby/issues/1919#issuecomment-721215752_

**Comment by afbora** [comment]
Yes, I wonder if `changeRole` permission covers all roles when we give permission (although it doesn't work)?

````yaml
permissions:
    users:
      changeRole: true
````

---

I think it would be more correct to be like this.

````yaml
permissions:
    users:
      changeRole: 
        - editor
        - customer
````
