### ISSUE TITLE
Using `site.find(self)` in blueprint breaks change status dialog for drafts

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2925]
**Describe the bug**  
A self reference in the blueprint using `site.find(…)` breaks the change status dialog for pages in draft mode.  
It's complicated, let me try to explain:

We've got an "awards" page that features three pages sections to display drafts, unlisted and listed pages (nothing special). As this section is needed repeatedly across the site, we defined it in a separate file, `blueprints/sections/awards.yml`, using a hardcoded reference to the awards page for the `parent`:

```yml
headline: Awards
type: pages
layout: cards
parent: site.find("awards")
status: listed
templates: award
info: '{{ page.related.toPage.title }} ({{ page.year }})'
```

This works fine as long a the referenced page is not a draft, because drafts are excluded by the `find` method. In this case, all sections using this definition will throw an error. This is expected behaviour.

In our case though, as this hardcoded reference is also used on the awards page itself, the change status dialog is broken as soon as awards is put into draft mode. It seems to promote the section error to the change status dialog:

**To reproduce:**  
Clone the Starterkit and change `blueprints/sections/notes.yml` to the following:

```yml
type: pages
headline: Notes
parent: site.find("notes")
info: "{{ page.date.toDate('d.m.Y') }}"
template: note
empty: No notes yet
sortBy: date desc
```

Put the notes page into draft mode.

**Screenshots:**  

This is what the section looks like when the page is in drafts mode (expected):

![grafik](https://user-images.githubusercontent.com/25466/98939615-fe751d00-24e9-11eb-9993-9792b773d35e.png)

This is what's displayed when you try to load the change status dialog:

![grafik](https://user-images.githubusercontent.com/25466/98939641-0765ee80-24ea-11eb-87f5-9eb4718bef60.png)

**Expected behavior**  
The error should not be promoted to the change status dialog and changing status should be possible as usual.

**Workaround:**  
Looking at the Starterkit, `kirby.page(…)` should be used instead of `site.find(…)` because it includes drafts.

**Kirby Version**  
Kirby 3.4.x and 3.3.x, not sure about earlier versions.
