### ISSUE TITLE
when option does not work for fields of a structure if outside of it

### ISSUE THREAD

**Issue by LouisJackson** [getkirby/kirby#2938]
**Describe the bug**  
`when` option does not work for fields of a `structure` field when the "condition field" is outside of the structure

**To Reproduce**  
1. Create the opposite blueprint file:

```
fields
  toggle:
    type: toggle
  test:
    type: structure
    fields:
      example:
        type: text
        when:
          toggle: true
```

**Expected behavior**  
`example` should be hidden in the panel when `toggle` is true.

**Kirby Version**  
3.4.4

**Console output**  
nothing

**Desktop (please complete the following information):**  
 - OS: macos big sure
