### ISSUE TITLE
Lists not displayed properly in Info field

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#2946]
**Describe the bug**
Ordered and unordered lists in info fields are not displayed with a number or bullet:

![image](https://user-images.githubusercontent.com/5570098/100061095-35c2c280-2e36-11eb-8074-3468b3e44295.png)

**To Reproduce**  
Add the following field:

```yml
type: info
label: Publish Checklist
text: |
  1. Check the URL (slug)

  - foo
  - bar
```

**Kirby Version**  
3.4.2
