### ISSUE TITLE
Bug in new feature "The template in the page creation dialog is only shown if there's more than one option"

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#2947]
In version 3.5 it was announced that the template field is no longer displayed if only one template is available (which I consider very useful). Unfortunately I cannot get this to work with version 3.5.

https://kirby.nolt.io/103

This section should not show a template field anymore, but it still appears

```
drafts:
  headline: Drafts
  type: pages
  status: draft
  templates: article
```
<img width="504" alt="Bildschirmfoto 2020-11-24 um 17 49 05" src="https://user-images.githubusercontent.com/2178466/100125801-798cea80-2e7d-11eb-9eb6-b95792b4ad50.png">
