### ISSUE TITLE
Video Block Error

### ISSUE THREAD

**Issue by modufolio** [getkirby/kirby#2955]
If you paste this type of youtube url in the video block it will result in an error.

example url: https://www.youtube.com/watch?list=PL7CcGwsqRpSM3w9BT_21tUU8JN2SnyckR&v=21HuwjmuS7A&index=1

Exception
Invalid YouTube source

**Comment by afbora** [comment]
@modufolio Seems working as expected on 3.5.0-RC.2 🤔 

![screen-capture-501-Sandbox - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/100587215-550f9300-3301-11eb-8291-075035e1f3f7.png)

**Comment by modufolio** [comment]
The preview works! But not if you render it.

Steps to reproduce. Plainkit -> upgrade kirby folder to 3.5.0-RC.2.

default.yml

```
title: Default Page
preset: page
fields:
  text:
    label: Text
    type: textarea
    size: large

  blocks:
    type: blocks
```

default.php

```
<h1><?= $page->title() ?></h1>

<?= $page->blocks()->toBlocks() ?>

```

Homepage
```

Home
Block error: "Invalid YouTube source" in block type: "video"

```
