### ISSUE TITLE
Range field tooltip overlapping when the width is narrow on Firefox

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#2961]
When setting the range field width to `1/3` and using an `after:` value, the tooltip overlaps the `after:` value.

![image](https://user-images.githubusercontent.com/5200901/100615956-9db15700-32d5-11eb-814a-63edd0d96812.png)

![image](https://user-images.githubusercontent.com/5200901/100616041-bd487f80-32d5-11eb-9830-47389ee44f38.png)

**Comment by afbora** [comment]
I have test blocks and layout field on 3.5.0-RC.2 and couldn't reproduce the issue with before and after option both.

![screen-capture-510-Sandbox - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/100785055-2be62400-3421-11eb-838c-c9340d34147f.png)

````yaml
fields:
  blocks:
    type: blocks
    fieldsets:
      test:
        name: Range
        icon: bolt
        fields:
          range1:
            label: Range 1
            type: range
            min: 1
            max: 10
            after: px
            width: 1/3
          range2:
            label: Range 2
            type: range
            min: 1
            max: 10
            before: width
            width: 1/3
          range3:
            label: Range 3
            type: range
            min: 1
            max: 10
            before: width
            after: px
            width: 1/3
````
