### ISSUE TITLE
[Blocks] Blueprint fieldset not recognized

### ISSUE THREAD

**Issue by mynameisfreedom** [getkirby/kirby#2966]
Hi, I am testing the new 3.5.0-rc3 version on a website that uses Kirby Builder, and I am trying to transfer Kirby Builder fields to the new Blocks field. Some things are working, but some don't. 

**BUG**
For example, some blueprint fieldsets that worked with Kirby Builder are not working now. And there is no error. If that block is used on a page then all others disappear. 

**Example blueprint fieldset to test**  

```
name: Slider
label: Slider {{title}}

tabs:
  # content tab
  content:
    label: 
      en: Content
      de: Inhalt
    icon: edit
    fields:
      # slider
      slider:
        type: files
        query: page.images
        layout: cards
        size: small

  # settings tab
  settings:
    label: 
      en: Settings
      de: die Einstellungen
    icon: cog
    fields:
      title:
        label: 
          en: Block title
          de: Blocktitel
        type: text
        placeholder: - My custom Block name
        help: 
          en: Useful when you have many blocks on one page.
          de: Nützlich, wenn Sie viele Blöcke auf einer Seite haben.
        width: 1/2
      blockClass:
        label: Block custom class
        type: text
        placeholder: my-custom-class
        width: 1/2
      # slider width
      sliderWidth:
        label: 
          en: Section width
          de: Abschnittsbreite
        type: select
        default: large
        options:
          large: 
            en: Large
            de: Groß
          small: 
            en: Small
            de: Klein
          xsmall: 
            en: XSmall
            de: XKlein
        width: 1/3
      # section backgorund
      sliderBack:
        label: 
          en: Section background
          de: Hintergrund des Abschnitts
        type: select
        default: default
        options:
          default: 
            en: Default
            de: Standard
          muted: 
            en: Muted
            de: Stumm geschaltet
          primary: 
            en: Primary
            de: Primär
          secondary: 
            en: Secondary
            de: Sekundär
        width: 1/3
      # images width
      sliderImgWidth:
        label: 
          en: Images width
          de: Bildbreite
        type: select
        default: 2-3
        options:
          " uk-width-1-1@m": 1-1
          " uk-width-2-3@m": 2-3
          " uk-width-1-2@m": 1-2
          " uk-width-1-3@m": 1-3
        width: 1/3
```

It can be reproduced with this blueprint fieldset.

**Comment by afbora** [comment]
@mynameisfreedom Can you share the whole blueprint for blocks field? Because the issue does not appear, looks good.

![screen-capture-519-Sandbox - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/100921908-3e7a5f00-34ee-11eb-8adf-d8aa4dab91d6.png)

**Comment by mynameisfreedom** [comment]
Hi, @afbora, thank you for the fast response.

I am calling fieldsets in a section

```
type: fields
fields:
  modules:
    label: 
      en: Page sections
      de: Seitenabschnitte
    type: blocks
    fieldsets:
      heading: false
      text: false
      image: false
      quote: false
      code: false
      gallery: false
      video: false
      kirbytext: false
      grid: fieldsets/grid
      editor: fieldsets/editor
      text-image: fieldsets/text-image
      cpt: fieldsets/cpt
      hero: fieldsets/hero
      media-image: fieldsets/media-image
      media-video: fieldsets/media-video
      gallery: fieldsets/gallery
      slider: fieldsets/slider
      slideshow: fieldsets/slideshow
      articles: fieldsets/articles
      projects: fieldsets/projects
```

And calling that section in a **tab** in page 

```
# page builder tab
  content:
    label: Page builder
    icon: layers
    columns:
        - width: 2/3
          sections:
            # Builder options
            sectionsSettings:
              extends: sections/builder-options
            # Builder sections
            sectionsBuilder:
              extends: sections/page-builder
```

The builder options section doesn't have anything with the builder field, it is just a switch for animations.
I am also aware, I should rename Gallery block, but I am still in testing, and it shouldn't influence this issue.
