### ISSUE TITLE
Query Language support in Block and Layout fields

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#2977]
In the Builder field we were able to do the following:

![image](https://user-images.githubusercontent.com/5200901/101488429-d62be300-391c-11eb-8f69-f59e293a3ed4.png)

As per the discord chat with @bastianallgeier, creating an issue to add query language support in the Block and Layout fields:

```yaml
fetch: page.content.form.toBlocks
text: "{{ block.field_label }}" 
value: "{{ block.field_id }}"
```
[Discord Message](https://discord.com/channels/525634039965679616/761608160565133343/785855471264989236) for above snippet.

```yaml
fetch: page.content.form.toLayout.first.columns.first.blocks
text: "{{ block.field_label }}" 
value: "{{ block.field_id }}"
```
[Discord Message](https://discord.com/channels/525634039965679616/761608160565133343/785856629446017024) for above snippet.
