### ISSUE TITLE
[3.5.0-rc.6] Time field doesn't working with display

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2993]
**Describe the bug**  

If you use display option on time field, field doesn't working properly. It can never be saved.

**To Reproduce**  
1. Go to panel
2. Create time field with display option like below
3. Try to change the time

Sample field:

````yaml
  myTime:
      type: time
      display: hh.mm A
````

**Kirby Version**  
3.5.0-rc.6

**Console output**  
No output

**Desktop (please complete the following information):**  
 - Windows 10
 - Chrome 87.0.4280.88

**Comment by distantnative** [comment]
Does it work if you actually do this?

```yaml
  myTime:
      type: time
      display: hh.mm A
      notation: 12
```

Since the `notation` option defaults to `24` you are trying to display a 24 hour based parsing with a 12 hour display and that crashes.

However, I can see how this is confusing. I am wondering whether 
- we completely remove the `notation` option and only check if `display` includes `a`/`A`
- still support the `notation` option but base the default on whether `display`  includes `a`/`A`

**Comment by distantnative** [comment]
If looking at @neildaniels's blueprint (https://github.com/getkirby/kirby/issues/2991), I think people use the `notation` option without the `display` option as well. So we shouldn't remove it completely, instead only alter the default of `notation` based on `display`.

**Comment by afbora** [comment]
Yes your setup working but still doesn't working when i remove the `a/A`

````yaml
  myTime:
      type: time
      display: hh.mm
````
