### ISSUE TITLE
3.5.0-RC.6: New DateTime field display issue

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#2998]
Trying the new display options I'm seeing something odd in the output:

![image](https://user-images.githubusercontent.com/5200901/101956654-35a81e00-3bbd-11eb-8ea2-17b5b2aa6bad.png)

The above snippet results in this output:

![image](https://user-images.githubusercontent.com/5200901/101956861-8c155c80-3bbd-11eb-8ce1-9c0fa8d7d486.png)

The full blueprint is large so he's the first column which contains the dates:

```yaml
title: "Article"
status:
  draft: Draft
  unlisted: In-Review
  listed: Published

tabs:
  content:
    label: Content
    columns:
      column2:
        width: 1/4
        sections:
          options:
            type: fields
            fields:
              date_published:
                label: Publish Date
                type: date
                display: "MM/DD/YYYY h:m A"
                time: true
                default: now
                required: true
              date_created:
                label: Date Created
                type: date
                time: true
                default: now
                disabled: true
                display: "MM/DD/YYYY h:m A"

              date_updated:
                label: Date Updated
                type: hidden
                time: true
                default: now
              author:
                type: users
              category:
                type: select
                label: Category
                default: updates
                required: true
                options:
                  updates: Updates
                  newsletters: Newsletters
                  releases: Press Releases
                  Leadership: Messages from the Leadership
              tags:
                type: tags
```

**Comment by distantnative** [comment]
You are mixing the time display into your date field part, which is why you are seeing the start of the time (then gets cut off by the input (due to https://github.com/getkirby/kirby/issues/2992) and what follows is the default of the time input.

Blueprint should be (would be great if you could paste your blueprint in the future instead of a screenshot, makes posting fixed code easier than re-typing it all form the screenshot)

```yaml
date_published:
  type: date
  display: MM/DD/YYYY
  time:
    display: h:m A
```

Can you confirm if that works for you?
