### ISSUE TITLE
[3.5.0-rc.6] Time field savebar and pressing up/down issues

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3001]
**Describe the bug**  

When you use time field like document, you have an two issues.
https://getkirby.com/v35/date#what-s-about-time

**Test following cases with empty input**

1. Press up/down button, you get following error
> Cannot read property 'length' of undefined

2. When you fill the input manually, savebar doesn't appear

**Test blueprint setup**

````
  myTime:
    type: time
    display: hh.mm.ss a
    step:
        unit: Second
        size: 15
````
