### ISSUE TITLE
Date Field w/ Time: "Today" button inserts from time (maybe Timezone related)

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3005]
**Describe the bug**  
My PHP server and locale machine are both in the Pacific time zone (`America/Los_Angeles`). My computer's clock says `12:14 PM`, but when I press the "Today" button on the Date field, it inserts `8:14 pm`.

I suspect it's using the UTC time (which would be `8:14 pm`).

Kirby 3.4.5 would have filled the expected `12:14 pm` time in.

```yaml
          created:
            label: Published Date
            type: date
            translate: false
            time:
              step: 1
              notation: 12
            width: 1/3
```

**To Reproduce**  
1. Use above date field
2. Click "Today" button (also occurs if you pick any specific day)
3. If you save, it will be committed as the `8:14 pm` time (in Pacific timezone).

**Expected behavior**  
Time should reflect the "current" time. For Kirby 3.4.5, this was always from the perspective of the server. (I don't think it tried to adjust for the browser's time zone.)

**Screenshots**  
<img width="340" alt="Screen Shot 2020-12-14 at 12 14 15 PM" src="https://user-images.githubusercontent.com/417182/102131046-79da2f00-3e06-11eb-8857-5afbb2d3d1ae.png">

**Kirby Version**  
`3.5.0-rc.7`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari 14.0.1 (16610.2.11.51.8)
