### ISSUE TITLE
Layout settings don't support „extends“

### ISSUE THREAD

**Issue by saschabregenhorn** [getkirby/kirby#3011]
The new layout settings (3.5) can't be [extended for reusing fields](https://getkirby.com/docs/guide/blueprints/extending-blueprints).

**Comment by afbora** [comment]
✅

**Comment by iskrisis** [comment]
Extend functionality doesn't behave same as with page blueprints. You can't "un-extend settings" that have been set in extended blueprint.
```yml
fields:
  layout:
    extends: fields/layout
    settings: false
```
gives `Argument 1 passed to Kirby\Form\Field\LayoutField::setSettings() must be of the type array, bool given`

`settings: false` should disable settings and hide the settings button shown to users
