### ISSUE TITLE
asterix in field label yaml needs to be escaped with single or double quotes

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#3014]
this will cause an 

> `site.yml` leads to 500: "Call to a member function options() on null"

see similar...
https://github.com/getkirby/kirby/issues/2265

this will not work
```yml
    headline_emailsclient:
      type: headline
      label: E-Mail an Bestellende*n
```

this will work
```yml
    headline_emailsclient:
      type: headline
      label: 'E-Mail an Bestellende*n'
```

maybe a yaml thing but not that easy to spot - so i posted it as issue for further reference.
