### ISSUE TITLE
Extending blocks type "text" adds p tags to the input

### ISSUE THREAD

**Issue by jnetzlr** [getkirby/kirby#3016]
**Description**  
I’m currently extending the text block type:
```
text:
  extends: blocks/text
  fields:
    text:
      type: textarea
```
But when editing the block, there are p tags added to the content. Even while writing in the input field (while the right side modal of the block is opened) there are p tags added to each typed character.

**Expected behavior**  
p tags shouldn't be added to the input field.

**Kirby version**  
3.5

**Desktop**  
 - OS: macOS 10.15.7
 - Browser: Chrome
 - Version: 87
