### ISSUE TITLE
Error when uploading font (.ttf, .otf...) in Kirby 3.5

### ISSUE THREAD

**Issue by guidoferreyra** [getkirby/kirby#3030]
**Describe the bug**  
If I try to upload a font to a files section I get **Invalid file type: -** this worked fine before 3.5 

**To Reproduce**  
Create a files section, drag and drop a otf, ttf or woff font.

**Expected behavior**  
Upload the file normally

**Kirby Version**  
3.5.0

**Desktop**  
 - OS: macOS 10.14.6
 - Browser: Firefox, Chrome

**Comment by afbora** [comment]
Yes there was an update on 3.5 for that. To allow all file types, you need to add code to the file blueprint as follows.

````yaml
# /site/blueprints/files/default.yml
title: Default
accept: true
````

Perhaps @lukasbestle who the author of the development, can provide other tips on this.

Document:
https://getkirby.com/docs/reference/panel/blueprints/file#accept

Related PR #2973

**Comment by guidoferreyra** [comment]
oh great, didn’t knew about it. What you suggested solved my issue thanks!

**Comment by lukasbestle** [comment]
@guidoferreyra @afbora Best would be to only allow the file types you need instead of allowing everything, otherwise users may upload files that are a security risk. So you can for example use:

```yaml
# /site/blueprints/files/font.yml
title: Font file
accept:
  extension: otf, ttf, woff
```
