### ISSUE TITLE
Date Field: Highlighted "today" day seems to always be tomorrow

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#3089]
**Describe the bug**  
On a date field, the indicated "today" day (in orange) does not reflect the local day. My PHP server and locale machine are both in the Pacific time zone (`America/Los_Angeles`). My computer's clock shows that it's Thursday, January 14. However, the date popover highlights Friday, January 15. (In UTC time, it is January 15.)

Possibly a continuation of #3005, or a result of #3075.

Kirby 3.4.5 highlights the expected day of "Thursday, January 14."

```yaml
          created:
            label: Published Date
            type: date
            translate: false
            time:
              step: 1
              notation: 12
            width: 1/3
```

**To Reproduce**  
1. Use above date field
2. Set your server's time zone to something that would cause the day to wrap to something else (probably relative to UTC)
3. Click into a blank date field

**Expected behavior**  
"Today" date should be reflective of the server's time zone, not UTC.

**Screenshots**  
<img width="793" alt="Screen Shot 2021-01-14 at 5 10 51 PM" src="https://user-images.githubusercontent.com/417182/104667964-0c7f1f80-568c-11eb-912d-dcb1d80fd275.png">

**Kirby Version**  
`3.5.1-rc.1`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari Version 14.0.2 (16610.3.7.1.9)
