### ISSUE TITLE
Blocks: Field property max has no effect

### ISSUE THREAD

**Issue by chrfickinger** [getkirby/kirby#3096]
**Describe the bug**  
The field property `max` for a maximum number of allowed blocks does not work. The field property `min`works as expected.

**Blueprint**
```
fields:
  text:
    type: blocks
    min: 1
    max: 3
```
**Kirby Version**
3.5.1

**Comment by afbora** [comment]
````yaml
fields:
  text:
    type: blocks
    min: 1
    max: 3
````

> You must not add more than 3 blocks

I can't reproduce the issue. Have you tried it in fresh starterkit?

**Comment by chrfickinger** [comment]
Yes, I used the fresh starterkit.

This is my `site/blueprints/pages/default.yml`:
```yml
title: Default Page
preset: page
fields:
  blocks:
    type: blocks
    min: 1
    max: 3
```
and this is my `site/templates/default.php`:
```php
<?php
	// Header
	snippet('header');

	// Blocks
	echo $page->blocks()->toBlocks();

	// Footer
	snippet('footer');
?>
```
