### ISSUE TITLE
Tabs on account page no longer work

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3098]
**Describe the bug**  
Tabs on account page no longer work. It works on 3.4.5 but not on 3.5.x. 

**Sample blueprint**

````yaml
# /site/blueprints/users/default.yml

title: User

tabs:

  # content tab
  content:
    label: Content
    icon: text
    columns:

      # main
      left:
        width: 2/3
        sections:

          # a simple form
          content:
            type: fields
            fields:
              headline:
                label: Headline
                type: text
              text:
                label: Text
                type: textarea

      # sidebar
      right:
        width: 1/3
        sections:
          # a list of files
          files:
            type: files
            headline: Files

  # seo tab
  seo:
    label: SEO
    icon: search
    fields:
      seoTitle:
        label: SEO Title
        type: text
      seoDescription:
        label: SEO Description
        type: text

````

**Kirby Version**  
3.5.x

**Console output**  
No errors

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome latest
