### ISSUE TITLE
set(date.handler, strftime) doesn't allow sorting by date in panel

### ISSUE THREAD

**Issue by Pascalmh** [getkirby/kirby#310]
If you set `c::set('date.handler', 'strftime');` in your config.php you can not sort pages by date anymore.

```
pages:
  template: news_item
  num:
    mode: date
    field: date
  sort: flip
```

Pages can not be made visible anymore. every time you try to make the page visible it seems to append `Ymd-` - example: `content/news/Ymd-Ymd-Ymd-my-folder`.

So this doesn't seem to be good practice at the moment: http://getkirby.com/docs/languages/setup (see  **Date handlers**)
