### ISSUE TITLE
Error when overwriting block tabs

### ISSUE THREAD

**Issue by iskrisis** [getkirby/kirby#3101]
When setting `tab: false` in extended block blueprint:
blocks/text.yml
```yml
name: Text
tabs:
  content:
    fields:
      text:
        type: text
  test:
    fields:
      test:
        type: text
```
blocks/test.yml
```yml
extends: blocks/text
name: Test
tabs:
  test: false
```
Error happens
`Return value of Kirby\Cms\Blueprint::extend() must be of the type array, bool returned kirby/src/Cms/Blueprint.php line: 199`
