### ISSUE TITLE
Time in date field with default: now is always 00:00

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/kirby#3106]
**Describe the bug**  
When creating a new page in the Panel, a date field with `default` set to `now` always shows `00:00` as time.

**To Reproduce**  
1. Install a fresh Starterkit and log in to the panel
2. Click "Add" for Notes to create a new note
3. See error: the time in the date field shows `00:00` (despite `default` set to `now` in the `note.yml` blueprint)

The error also persists when altering the blueprint as follows:
```
date:
  type: date
  time:
    step: 1
    display: HH:mm
    default: now
  default: now
```

**Expected behavior**  
A time field with `time: true` and `default: now` would use the current time, either by default or at least when the time value is also set to `default: now`.

**Kirby Version**  
3.5.1

**Console output**  
No console output.

**Desktop:**  
 - OS: Linux Mint 19.3
 - Browser: Firefox
 - Version: 84.0.2

**Comment by distantnative** [comment]
Just on my phone, so apologies that I can't check myself right now. But I think it's because your blueprint defines the step as 1 day and everything gets rounded to the nearest day therefore.

**Comment by moevbiz** [comment]
I'm having the same issue with every date field, without having set `step` at all. 

```yml
date:
  type: date
  time: true
  default: today
  # same with default: now
  display: DD.MM.YYYY
```
See also this thread in the forum: https://forum.getkirby.com/t/panel-time-defaults-to-00-00/20896?u=bruno

**Comment by afbora** [comment]
> But I think it's because your blueprint defines the step as 1 day and everything gets rounded to the nearest day therefore.

@distantnative But step is set for `time` prop. Shouldn't it be 1 minute?

**Comment by distantnative** [comment]
That happens when I read on the phone 🙈
I would imagine all of it is related to the step mechanism but I also agree if it's date and time the default step should be based on minute, if only date then on day

**Comment by CrisGraphics** [comment]
```yaml
date:
  type: date
  label: "Date"
  time:
    display: HH:mm:ss
    step:
      unit: second
      step: 1
```

I'm also having issues with the combined date + time field.
With this setup, seconds in- or decrease by 5 instead of 1.

**Comment by moevbiz** [comment]
so what's the definite solution to store date & time with a correct time default? it's always showing `00:00`, no matter what I do...

**Comment by MaluNoPeleke** [comment]
Would also be nice to have a time picker in the popup as well.

**Comment by distantnative** [comment]
@MaluNoPeleke could you please create this as an idea over at feedback.getkirby.com? Thanks?

**Comment by MaluNoPeleke** [comment]
I guess I found one: https://kirby.nolt.io/304

**Comment by isaactopo** [comment]
It would be very nice to solve this as it is a problem for RSS automations with Mailchimp, thanks! <3

**Comment by teichsta** [comment]
same, here would be very interested in a fix @distantnative.

**Comment by MaluNoPeleke** [comment]
Could this be part of Kirby 3.6.0 @afbora @bastianallgeier?

**Comment by isaactopo** [comment]
Not solved on 3.6, right?

**Comment by distantnative** [comment]
✅ will be fixed in 3.6.2

**Comment by vivaneo** [comment]
Hello,

in 3.6.6 it is not corrected. Do not forget us :)

**Comment by sebastiangreger** [comment]
I have a blueprint using

```
date:
  type: date
  time:
    step: 1
    display: HH:mm
  default: now
```

and this has worked fine ever since 3.6.2 – it sets both date and time to the current moment, as expected.

@vivaneo Have you verified that the `default: now` statement is indented correctly? It has to be a sibling to `time:`, not its child.
