### ISSUE TITLE
Seconds in date field get not saved correctly

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#3107]
**Describe the bug**  
When setting up the time display to also include seconds, seconds don't trigger a change and also don't get stored correctly in the text files.

**Comment by distantnative** [comment]
✅ Cannot reproduce this with 3.6.2 anymore (upcoming release).
If you still encounter the issue, please provide a reproducible setup/blueprint. Thank you :)

**Comment by crisgfx** [comment]
Sorry to bring this up again,
but I still can't enter seconds in the time field.
Well, I can, but the value resets back to 00 as soon as the field loses focus.

```yaml
time_info:
  type: date
  label: Ende
  display: DD.MM.YYYY
  time:
    display: "HH:mm:ss"
    step: 1
```



https://user-images.githubusercontent.com/16305374/159676819-39fe4dc4-87b4-4335-a75f-75589514e805.mp4



Kirby Version: 3.6.3 (also happenes with 3.6.2)

**Comment by bastianallgeier** [comment]
@CrisGraphics that's expected in this case. The unit is minute by default. Try:
```yaml
time_info:
  type: date
  label: Ende
  display: DD.MM.YYYY
  time:
    display: "HH:mm:ss"
    step: 1
    unit: second
```

**Comment by crisgfx** [comment]
Unfortuntely that doesn't work. I still get the same result.
The docs also don't mention unit `second`

Edit: sorry, they do. Was looking at the Date reference.

**Comment by crisgfx** [comment]
Ok, I got it – had some wrong indentation.
This works. Sorry again for the inconvenience!

```yaml
time_info:
  type: date
  label: Ende
  display: DD.MM.YYYY
  time:
    display: "HH:mm:ss"
    step:
      unit: second
      size: 1
```
