### ISSUE TITLE
Invalid block type in a layout field causes a front-end error in the panel

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#3121]
**Describe the bug**  
If the JSON content of a layout field contains an invalid block type, you get an error in the panel and you can't edit anything. That's an issue if you refactor a block and change its name in the process - all fields that use it will throw errors!

**To Reproduce**  

1. Create a layout field
2. Add a custom block type in the field blueprint
3. Add an instance of that block type in the panel
4. Remove the custom block from the blueprint
5. Reload the panel and see the error

**Expected behavior**  
The block should be ignored or treated as a `text` block (if it's specified as valid in the fieldsets option).

**Screenshots**  
![image](https://user-images.githubusercontent.com/5570098/106274986-d0c48800-623d-11eb-8c5d-07fed08b833c.png)

**Kirby Version**  
3.5.1

**Comment by afbora** [comment]
I've tested now with following field:

````yaml
fields:
  text:
    type: layout
    fieldsets:
      button:
        name: Button
        icon: bolt
        fields:
          link:
            type: url
          text:
            type: text
````

I added a new field and created new instance with filled:

![screen-capture-700-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/106277232-cad4a400-6249-11eb-9d7c-84427b633a51.png)

Then I deleted `button` block type from blueprint and it keeps looking like this:

![screen-capture-707-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/106277369-04a5aa80-624a-11eb-8a45-40d8e41dc8ea.png)

I think it fails on a specific blueprint. Can you share your custom block type blueprint?
