### ISSUE TITLE
Layout field settings not validated

### ISSUE THREAD

**Issue by yandodov** [getkirby/kirby#3139]
**Describe the bug**  
I have the following layout field:

```yml
type: layout
settings:
  fields:
    hash:
      type: text
      pattern: "[a-z-0-9]+"
```

The `hash` field correctly turns red when you put in invalid characters, but you can save the field anyways. Similarly, using `required: true` has no effect - you can save an empty field.

**Expected behavior**  
You should get an error that the field is incorrectly filled.

**Kirby Version**  
3.5.1
