### ISSUE TITLE
Blocks writer preview doesn't apply field props

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3145]
**Describe the bug**  
Props applied to the field are not applied to the block preview.

**To Reproduce**  
1. Go to panel
2. Add new block type that included writer field like following sample
3. Disable `marks` and `nodes` prop
4. You'll see nodes and marks on preview but not in drawer (as expected).

````yaml
name: Test
wysiwyg: true
preview: text
fields:
  text:
    type: writer
    nodes: false
    marks: false
````

**Expected behavior**  
The field props should also be applied to field preview.

**Kirby Version**  
3.5.2.RC-1

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome latest
