### ISSUE TITLE
Tabs with settings for layouts not documented

### ISSUE THREAD

**Issue by hdodov** [getkirby/kirby#3213]
[In the docs](https://getkirby.com/docs/reference/panel/fields/blocks#extending-core-blocks__adding-tabs), you can see that tabs can be used for **block** settings:

> You can extend our core blocks with additional tabs.

I just tested it and you can use tabs in _layout_ settings as well:

```yml
title: Page
preset: page
fields:
  content:
    type: layout
    layouts:
      ...
    fieldsets:
      ...
    settings:
      tabs:
        content:
          fields:
            ...
        styles:
          fields:
            ...
```

I needed layout tabs instead of block tabs, so it would be useful to add it in the docs. I was about to make a suggestion in Nolt, but decided to try it out before doing so - turns out the functionality was there and I just didn't know about it.
