### ISSUE TITLE
multi-language labels in kirby 2.2: labels not showing

### ISSUE THREAD

**Issue by p-h-i-l** [getkirby/kirby#322]
Hey, 

i already posted this bug in the [Forum](https://forum.getkirby.com/t/kirby-2-2-error-with-labels/2533).
But here is the short explanation again. 

For multi-language labels like: 

```
fields:
  title:
    label:
      de: Überschrift
      en: Headline
    type: text
```

The pages dont switch/show the labels.

Additionally when: 

```
c::set('debug', true);
```

i receive the following error message: 
```
Warning: Illegal offset type in isset or empty in pathto/kirby/toolkit/lib/a.php on line 56
```

Hope this helps to find and solve the bug. 

Thank you!
