### ISSUE TITLE
Files section and field ignore image preview settings

### ISSUE THREAD

**Issue by moritzebeling** [getkirby/kirby#3226]
**Describe the bug**  
The `files` section and field, both ignore the `image.cover: false` option. 

**To Reproduce**  
1. Create a page with a files section and a files field, e.g.
```yaml
sections:

  uploads:
    type: files
    image:
      cover: false

  fields:
    type: fields
    fields:

      gallery:
        type: files
        image:
          cover: false
```
2. Upload and select some images
3. You will see, that both the section and the field have cropped images

**Expected behavior**  
The cropping or fitting of the image should follow the `image.cover` option.

This topic is important for image editors to instantly see the image orientation and aspect ratio.

**Screenshots**  
<img width="384" alt="Bildschirmfoto 2021-03-30 um 09 16 28" src="https://user-images.githubusercontent.com/39742729/112948675-a22d3580-9138-11eb-89bb-e96943bde01b.png">

**Kirby Version**  
3.5.3.1

**Device**  
macOS, safari
