### ISSUE TITLE
Links overflows on disabled structure field

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3227]
**Describe the bug**  
This issue reported by `Modufolio` from Discord channel.

**To Reproduce**  
1. Go to panel
2. Create or edit page that have `structure` field
3. Add long URL to field in `structure` field
4. See error when field disabled

**Sample Blueprint**

````yaml
fields:
  social:
    label: On the web
    type: structure
    disabled: true
    fields:
      platform:
        label: Platform
        type: text
        width: 1/2
      url:
        label: URL
        type: url
        width: 1/2
````

**Screenshots**  

**Active**

![screen-capture-967-About us - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/113713074-92d95980-96ef-11eb-8bbf-8a67c48bb333.png)

**Disabled**

![screen-capture-970-About us - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/113713114-9ff64880-96ef-11eb-98cc-ad3f4c9855c4.png)

**Kirby Version**  
3.5.3.1
