### ISSUE TITLE
Date field bug when display: YYYY

### ISSUE THREAD

**Issue by possible-is** [getkirby/kirby#3234]
If i add display: YYYY to a date field and then try to enter a year manually (not via the date picker) into the date field in the panel, i get this response:
"Cannot read property '0' of null"

As a suggestion i would recommend to just automatically pick the date 01.01. of that year. 

If i change the display: YYYY to MM.YYYY the manual typing works again.

My version of kirby: 3.5.3

**Comment by sboegel** [comment]
same here! It would be great to have a date picker to select the year only for this purpose.
My field definition:
```
fields:
   year:
        label: Jahr
        type: date
        display: 'YYYY'
        required: true
        calendar: true
        format: 'Y'
        translate: false
        step: year
        default: today
```
