### ISSUE TITLE
Date field bug with default time value

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/kirby#3236]
When a date field is created together with the time option, the initial value does not work correctly at the page creation. Correct would be that the date and the time correspond to the current state. However, only the date is set to today and the time always remains at 0:00:00.

Also, no matter what I do, I can't enter seconds manually. But I think thats another story.

Example:

```yaml
buchungsdatum:
  label: "Gebucht am"
  type: date
  default: today
  required: true
  display: "DD.MM.YYYY"
  time:
    display: HH.mm.ss
    step: 1
    default: now
```
