### ISSUE TITLE
Blueprint > query > text - Does not interpret html markup anymore?

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#3278]
**When using HTML markup in text query option in a Blueprint, HTML is not interpreted anymore**  

**Example:**  
```
evaluatorProposals:
    label: Proposals to evaluate
    type: checkboxes
    width: 3/4
    options: query
    query: 
      fetch: page.parent.children.unlisted.template('proposal')
      text: '{{ page.title }} <span style="width:125px;text-align:right;font-size:0.75em;color:#777;float:right">{{ page.nbrEvaluators }}</span>'
```

**Expected behavior**  
The HTML markup should be interpreted in the panel.

**Kirby Version**  
Work in Kirby 3.3.6 for instance but not in 3.5.3.1

**Desktop (please complete the following information):**  
 - OS: Linux
 - Browser: Firefox
 - Version: 88.0 (64 bits)
