### ISSUE TITLE
Table block: writer field output in preview not correct

### ISSUE THREAD

**Issue by silllli** [getkirby/kirby#3324]
**Describe the bug**  

In the preview of the table block (`blocks/table`) the output of the writer field is not correct. The HTML tags are visible and not applied.

**To Reproduce**  
1. Create a block that extends `blocks/table`
2. Add a writer field to the `fields`
3. Use the block, add an entry and enter something in the writer field
3. Look at the preview

Sample code:
```yaml
name: Tabelle
extends: blocks/table
fields:
  rows:
    type: structure
    columns:
      entry:
        width: 1/3
      description:
        width: 2/3
    fields:
      entry:
        type: text
        counter: false
        label: Eintrag
        width: 1/3
      description:
        type: writer
        label: Erläuterung
        marks:
          - bold
          - link
        width: 2/3
    label: Einträge
```

**Expected behavior**  

The content of the writer field being rendered correctly.

**Screenshots**  

![Bildschirmfoto 2021-05-12 um 17 08 37](https://user-images.githubusercontent.com/9334305/117998991-b2921c00-b344-11eb-9bc3-d278a2c10aba.png)

**Kirby Version**  

3.5.5

**Console output**  

No console output.

**Desktop (please complete the following information):**  
 - OS:  macOS
 - Browser:  Google Chrome
 - Version:  90.0.4430.212
