### ISSUE TITLE
[Regression] Permissions access 

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#3468]
**Describe the bug**  
Permissions access set to false in a custom user blueprint did not disabled/faded corresponding items in the panel menu

**To Reproduce** 
Create a custom user blueprint
Set some access option to false 

 /blueprint/users/test.yml:

```
title: user test

permissions:
 access:
   panel: true
   site: true
   users: false
   settings: false
```

**Expected behavior**  
Items menu (users and settings in this example) should be disabled (not clickable) and faded.

**Kirby Version**  
3.5.6 and 3.5.7 rc1

**Desktop (please complete the following information):**  
 - OS: Linux
 - Browser: Firefox
