### ISSUE TITLE
[3.6.0] User with no access to `users` areas cannot access `account` view either

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#3532]
```yaml
title: Editor

permissions:
  access:
    users: false
```

Menu entry is correctly disabled:

<img width="303" alt="Screen Shot 2021-07-17 at 19 56 54" src="https://user-images.githubusercontent.com/3788865/126045837-7bdcb0e4-1e06-4c04-b6a9-4a80a65a1b56.png">

But clicking on `Your account` doesn't do anything.

Console:
<img width="1406" alt="Screen Shot 2021-07-17 at 19 57 44" src="https://user-images.githubusercontent.com/3788865/126045856-e9abf328-ab4d-4b6b-81c1-52dcc0f07d8c.png">
