### ISSUE TITLE
[3.6.0-alpha.2] Blocks field dropdown receives block instead of flex

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/kirby#3552]
**Describe the bug**  

Instead of `display: flex`, the blocks dropdown receives `display: block` on selection.
This results in spaces that offset the buttons.
```css
.k-block-container[data-selected] .k-block-options {
  display: block;
}
```

**To Reproduce**  
1. Add a blocks field
2. Focus one of the blocks

**Expected behavior**  
```css
.k-block-container[data-selected] .k-block-options {
  display: flex;
}
```

**Screenshots**  

<img width="265" alt="Screenshot-20-07-2021_15-22-52@2x" src="https://user-images.githubusercontent.com/7975568/126331605-67e8e633-4fa0-44aa-af83-e8cb2b818edf.png">

**Kirby Version**  

3.6.0-alpha.2
