### ISSUE TITLE
Panel: Long tags wrap text which overflows black box

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#3614]
**Describe the bug**  
See screenshot

**To Reproduce**  
1. Have a tags field
2. Insert e very long tag

**Expected behavior**  
Either clip the text with an ellipsis, or don't fix the height of tags (replace it with min-height and paddings; at least in `list` layout). 

**Screenshots** 
Is now:
![image](https://user-images.githubusercontent.com/6684137/128509263-3136999a-4c2f-4602-b7ad-ae6dc1104a41.png)
Could be:
![image](https://user-images.githubusercontent.com/6684137/128509509-e68fe070-04a4-4782-8acb-e3c0ccd35d31.png)

**Kirby Version**  
3.5.6

**Additional context**  
Can be worked around with custom panel css:

```css
.k-input[data-theme=field][data-type=tags] .k-tags-input[data-layout=list] .k-tag {
    height:auto; 
    min-height:1.75rem;
}

.k-tags-input[data-layout=list] .k-tag-text {
    padding:.25rem .75rem;
}
```
