### ISSUE TITLE
[3.6.0-alpha.4] - blueprint column width  for 1/4 & 3/4 display error 

### ISSUE THREAD

**Issue by garethworld** [getkirby/kirby#3629]
**Describe the bug**  
Columns overlap when using files section set to width 1/4 and fields section with a width of 3/4. 

**To Reproduce**  
```
columns:
      left:
        width: 1/4
        sections:
          profile:
            type: files
            headline: Profile image
            template: cover
            layout: cards
            size: medium
            max: 1
            image: 
             ratio: 1/1

      right:
        width: 3/4
        sections:
          info:
            type: fields
            fields:
              role:
                type: text 
```

**Screenshots**  

![Screenshot 2021-08-11 at 12 55 18](https://user-images.githubusercontent.com/55981730/129024797-241b45e9-a320-49fa-a5a1-505433871586.png)

**Kirby Version**  
3.6.0-alpha.4

**Desktop **  
 - OS: macOS 
 - Browser: Chrome 
 - Version: 92.0.4515.131

**Comment by bastianallgeier** [comment]
@distantnative we can solve this by reducing the min value in 1/4 columns, but I wonder if there's a more stable version: 

```css
@media screen and (min-width: 30em) {
  .k-column[data-width="1/4"] .k-cards-items {
    --min: 10rem;
  }
}
```

**Comment by distantnative** [comment]
We would probably have to define even more since we also allow `1/12` and `1/6` as column widths. I assume they would be even worse affected at the moment.

**Comment by bastianallgeier** [comment]
This is one of those cases where element queries would solve all our problems :(

But for now I don't see another choice. We have to define all those cases.

**Comment by distantnative** [comment]
I think we could do this:

```css
@media screen and (min-width: 30em) {
  .k-column[data-width="1/4"] .k-cards-items,
  .k-column[data-width="1/5"] .k-cards-items,
  .k-column[data-width="1/6"] .k-cards-items {
    --min: 1fr;
  }
}
```

In these column sizes, not matter the card size, we should probably only display one card per row.

If you agree, I can open the PR, I have a local branch already.
