### ISSUE TITLE
[3.6.0-alpha.4]  - Image: false on page sections no longer works

### ISSUE THREAD

**Issue by garethworld** [getkirby/kirby#3633]
**Describe the bug**  
No longer possible to hide the image on list view of page sections

**To Reproduce**  

```
menu:
      headline: ' '
      type: pages
      status: all
      image: false

```
**Expected behavior**  
No black squares on the page items

**Screenshots**  
![Screenshot 2021-08-12 at 10 37 32](https://user-images.githubusercontent.com/55981730/129174979-df63178d-bf5a-4a01-8ff2-2922b211fcac.png)

**Kirby Version**  
3.6.0-alpha.4

**Desktop:**  
 - OS: OSX
 - Browser: Chrome
