### ISSUE TITLE
[3.6.0-alpha.4] Conditional sections with extending fields doesn't working

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3636]
**Describe the bug**  

Following sample working on 3.5.7.1 but not for 3.6.0-alpha.4.

````yaml
columns:
  - width: 1/3
    fields:
      test:
        type: toggle
      
  - width: 2/3
    sections:
      test:
        extends: fields/test # includes multiple fields
        when:
          test: true
````

**fields/test.yml**

````yaml
type: fields
fields:
  foo:
    type: text
````

**Kirby Version**  

3.6.0-alpha.4
