### ISSUE TITLE
Structure field with custom column widths breaks on mobile

### ISSUE THREAD

**Issue by VIPStephan** [getkirby/kirby#3638]
**Describe the bug**  
There seems to be an inconsistency with responsive layout adjustments: I have a table block with a structure field with three columns by default. I want only two columns to show up in the block preview, so I’ve specified two columns with 1/2 width each. This looks fine in the table preview but it also uses the width setting in edit mode where it just shows the first field, and it screws up the width.

**To Reproduce**  
1. Set the viewport width to 1040px or lower.
2. Create a table block, according to https://getkirby.com/docs/reference/panel/blocks/table, with three fields and only two columns specified to show up (see first image below)
3. Add content to the structure field
4. Open edit mode of table block
5. See error.

**Expected behavior**  

If columns are hidden by the system due to CSS media queries, column/width settings should be ignored or adapted.

**Screenshots**  

Blueprint setup (~/site/blueprints/blocks/table.yml):
![table_block_blueprint](https://user-images.githubusercontent.com/13770606/129639854-6cc7d98e-a9bc-456a-9f22-f6ae1ad1cf4e.png)

Default table preview in the main area without column specification:
![default_columns_preview](https://user-images.githubusercontent.com/13770606/129640042-ff21e5ef-6eb0-4877-8cdc-e0b04b068d92.png)

Default table preview in the edit mode overlay:
![default_columns_edit_mode](https://user-images.githubusercontent.com/13770606/129640143-7e2fb60c-31d4-4f59-85dc-ba3c09185533.png)

Table preview in the main area with columns specified:
![2_columns_preview](https://user-images.githubusercontent.com/13770606/129640211-5a46d8a4-a6e8-4e1f-be00-541f937c3a38.png)

Table preview in edit mode overlay with columns specified:
![2_columns_edit_mode](https://user-images.githubusercontent.com/13770606/129640243-bf422ed9-db3f-4b24-bc53-d59ba69011ae.png)

**Kirby Version**  
3.5.7.1

**Desktop (please complete the following information):**  
 - OS: macOS 10.15.7 (Catalina)
 - Browser: Firefox
 - Version: 91

**Comment by lukasbestle** [comment]
@VIPStephan Could you please post the blueprint YAML as text in a Markdown code block:

    ```yaml
    your blueprint
    ```

This makes it a lot easier for us to reproduce and debug this. Thanks!

**Comment by VIPStephan** [comment]
```yaml
name: Tabelle
icon: menu
preview: table
fields:
  rows:
    type: structure
    label: Einträge
    fields:
      kuenstler:
        label: Künstler
        type: text
        help: Formatierungen wie \**kursiv*\* und \*\***fett**\*\* sind möglich.
      kuenstler_link:
        label: Link
        type: url
      media:
        type: blocks
        label: Medien
        fieldsets:
          - audio
          video_link:
            name: Video
            icon: video
            label: "{{ video_title }}"
            fields:
              video_url:
                label: YouTube-/Vimeo-URL
                type: url
              video_title:
                label: Titel
                type: text
```

**Comment by lukasbestle** [comment]
Thanks! I can reproduce the same issue with a simple `structure` field outside of `blocks`:

```yaml
fields:
  structure:
    type: structure
    label: Einträge
    fields:
      kuenstler:
        label: Künstler
        type: text
      kuenstler_link:
        label: Link
        type: url
      media:
        type: text
    columns:
      kuenstler:
        width: 1/2
      kuenstler_link:
        width: 1/2
```

So the issue is that the `max-width: 65em` media query of the `StructureField` doesn't behave correctly if the structure columns have custom widths. Have I understood the problem correctly @VIPStephan?
