### ISSUE TITLE
accepted mime types are NOT checked when associating files

### ISSUE THREAD

**Issue by andidevi** [getkirby/kirby#3639]
steps to reproduce
1. create two seperated blueprints for image and for audio files. 
2. set the accepted mime type that audio files only accept 'audio/mpeg'
3. create a panel to upload both types of files
4. try to upload an jpeg to the audio files. it will be rejectet
5. upload that jpeg to the image files. 
6. use the associate feature on the audio files and choose the uploaded image. It is accepted.

Expected behaviour:
The image file should be rejected in step 6 above.

**Comment by afbora** [comment]
If I understood correctly, you mentioned the inconsistency between uploading and selecting part. Uploading and selecting parts work differently. Maybe what you need is just filter via query as below:

````yaml
cover:
  type: files
  query: page.images
  
voice:
  type: files
  query: page.audio
````

**Comment by lukasbestle** [comment]
You can also filter by the file template:

```yaml
cover:
  type: files
  template: your-image-template-name

voice:
  type: files
  template: your-audio-template-name
```

This will at the same time also automatically set the correct template if users upload files directly to these sections. You can find additional configuration options [in the reference](https://getkirby.com/docs/reference/panel/sections/files).
