### ISSUE TITLE
Kirby Blocks can't use field info as label

### ISSUE THREAD

**Issue by dgsiegel** [getkirby/kirby#3661]
**Describe the bug**  

With Kirby Builder I had a field set up like this:

```
name: Hero Image
label: Hero Image - {{image.0.filename}}

fields:
  image:
    label: Image
    type: files
    image:
      ratio: 3/1
      cover: false
    max: 1
```

The label was showing the filename of the first image.

With Kirby Blocks I use this field setup:

```
name: Hero Image
label: 'Foo {{image.0.filename}}'
preview: fields
wysiwyg: true
icon: image

fields:
  image:
    label: Image
    type: files
    image:
      ratio: 3/1
      cover: false
    max: 1
```

However the label just shows as `Foo … `

**To Reproduce**  
1. Use the above field definition as a block
2. Add the block
3. Look at the label

**Expected behavior**  
I would expect to be able to select all field properties

**Screenshots**  
![Screenshot from 2021-09-01 23-37-04](https://user-images.githubusercontent.com/4396895/131748648-22af7f19-430b-4adf-8558-b0a165cf25fb.png)

**Kirby Version**  
3.5.7.1

**Additional context**  
Interestingly, using only `'{{image}}'` as label results in `[object Object] `
