### ISSUE TITLE
Pre text in text fields

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#367]
Sometimes it's useful with a pre text to a text field like this:

![image](https://user-images.githubusercontent.com/927011/38314920-a36d7a4e-3827-11e8-828a-dfd0912ce488.png)

```yml
my_text:
  label: My text
  type: text
  prefix: GA-
```
