### ISSUE TITLE
Link and email buttons will not display when textarea is nested within structure field

### ISSUE THREAD

**Issue by piperhaywood** [getkirby/kirby#389]
I am using a structure field to allow editors to add an image (select field) and write a caption (textarea field). The italics button is appearing as specified in the nested textarea field definition, but the link and email buttons don't show up. Full structure field definition and screenshot below:

```
project_images:
    label: Images
    type: structure
    entry: >
      {{image}}
      {{caption}}
    fields:
      image: 
        label: Image
        type: select
        options: images
      caption:
        label: Caption
        type: textarea
        buttons:
          - italic
          - link
          - email
```
![screen shot 2016-02-25 at 15 37 16](https://cloud.githubusercontent.com/assets/4711611/13324450/b5e89a38-dbd5-11e5-8d96-45370f116def.png)

I tried to have a look at the `panel/app/fields/textarea` and `panel/app/fields/structure` code to see what might be going on but couldn't really figure it out... Let me know if you need any more info!
