### ISSUE TITLE
[CMS & Panel] Custom pageModels not working

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#408]
I am using kirby and panel `origin/develop` but i can not get custom pageModels to work. what am i missig? I assumed creating a template, blueprint and model named *product* should do the trick.
I created a custom plugin with composer and psr-4 like your demo-plugin.

sidequestion: will the pageModel be loaded in the kirby 3 panel? kirby 2 did not do this without a little hack.

**site/plugins/bnomei-product/config.php**
```php
Kirby::plugin([
    'name' => 'bnomei/product',
    'extends' => [
        'pageModels' => [
          'product' => Bnomei\Model\Product::class, // name of template, right?
        ],
        'blueprints' => [
            'pages/product' => __DIR__ . '/blueprints/pages/product.yml',
        ],
        'templates' => [
            'product' => __DIR__ . '/templates/product.php'
        ],
    ]
]);
```

**site/plugins/bnomei-product/blueprints/pages/product.yml**
```yml
name: product # does this override the templatename based on filename if set to another string?
title: Product
sections:
  content:
    type: fields
    fields:
      text:
        label: Text
        type: textarea
  cover:
    extends: sections/image
    template: cover
    min: 1
```

**site/plugins/bnomei-product/models/product.php**
```php
namespace Bnomei\Model;

class Product extends Kirby\Cms\Page
{
    public function test()
    {
        return $this->id();
    }
}
```

**site/plugins/bnomei-product/templates/product.php**
```php
  echo Bnomei\Model\Product::class. ' ?= ' .get_class($page); // Bnomei\Model\Product ?= Kirby\Cms\Page
  echo ' => ['.$page->id().' ?= '.$page->test().']'; // products/product-a ?=
  echo $page->template(); // product
```
