### ISSUE TITLE
[Panel] Evaluate CSS variables as possible configuration option

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/kirby#409]

**Comment by jenstornell** [comment]
I recently discovered the real power befind CSS variables. I can share some of my learnings here.

## "Wrong approach"

What I did before was an approach where I used media queries everywhere in my sass files.

Let's say we need a padding of `10px` for small screens and `20px` for large screens. Then we use media queries on that component. But what if another component also would like to use this exact padding? We can use css variables for sure, but we will still end up with multiple media queries, one set for each component.

## Better approach

```css
:root {
  --padding: 10px;

    @media screen and (min-width: 30rem) {
      --padding: 20px;
    }

    @media screen and (min-width: 40rem) {
      --padding: 40px;
    }
}
```

The above means that `--padding` now changes automatically to the environment and we no longer need to think about it when we create our component css:

```css
.my-component {
  padding: var(--padding);
}
```

The padding of `.my-component` can now be `10px`, `20px` and `40px` depending on the screen size. It's really awesome to have the media queries in one place to keep the components clean. In many cases many components use the same breakpoints and this makes a great overview.

https://www.madebymike.com.au/writing/using-css-variables/

## Config to CSS

To have "theme" features, we can put a style block in our body like this (PHP):

```php
<style>
:root {
  --my-color: <?= $site->my_color()->value(); ?>;
}
</style>
```

Then the css file will be aware of `--my-color` so I don't need to generate it to put that value in.

**style.css**

```css
.my-div {
  color: var(--my-color);
}
```

I'm really hyped about what you can do with CSS variables. Therefor I hope you take advantage of them, which will probably be a big gain.

I hope you got some ideas from this, or did you already know about it?
