### ISSUE TITLE
[Docs] Incorrect User Permissions docs on Notion

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#415]
creating a **site/blueprints/users/visitor.yml** like described in the notion docs does break the panel login. how to do this right? meaning you can no longer login with the `developer@getkirby.com` account event if its role is `admin`.

```yml
title: Visitor
permissions:
  panel: false
```

this does not work either since notion doc has wrong keys. otherwise this would work.
```yml
title: Visitor
permissions:
  access:
    *: false
  site:
    *: false
  pages: # should be page
    *: false
  users: #should be user
    *: false
  files: #should be file
    *: false
```
