### ISSUE TITLE
[Panel] Firefox highlighting when dragging items

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#441]
Firefox 60

![sortable](https://user-images.githubusercontent.com/10027897/39235882-74d6c2fc-4877-11e8-9c53-c9c47e04e6b2.png)

I was able to prevent this with `user-select: none`.

```css
.sortable-chosen {
  -moz-user-select: none;
}
```
