### ISSUE TITLE
[Panel] Tag options in structure fields

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#470]
When adding options to a tag list inside a structure field, the panel displays the following message and suggestion won't show up

![bildschirmfoto am 2018-05-29 um 14 58 24](https://user-images.githubusercontent.com/25466/40660411-399fb816-6351-11e8-95b4-c4e45cfcf559.png)

This is the related part of the blueprint:

```yaml
      credits:
        label: Credits
        type: structure
        fields:
          title:
            label: Group
            type: text
            width: 1/3
          names:
            label: Names
            type: tags
            width: 2/3
            options: query
            query:
              fetch: site.find('projects').children
```

Using the same settings outside a structure field works flawlessly. 
It doesn't matter wheather options are static or queried dynamically.

**Comment by distantnative** [comment]
I get `Cannot read property '$invalid' of null` with the following blueprint:

```
fields:
  credits:
    label: Credits
    type: structure
    fields:
      title:
        label: Group
        type: text
        width: 1/3
      names:
        label: Names
        type: tags
        width: 2/3
        options: query
        query: site.find("projects").children
```

Causing the following console error:

```
Invalid prop: type check failed for prop "options". Expected Array, got String.

found in

---> <KirbyTagsField> at node_modules/getkirby-ui/src/components/Forms/Field/TagsField.vue
```
