### ISSUE TITLE
[Panel] Structure field stores undefined values

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#473]
When adding content to the structure field, the panel sometimes stores `undefined` ghost key/value pairs:

```yaml
Credits: 

- 
  title: Team
  names: >
    Max, Moritz
- 
  undefined: null
  title: 'A longer title'
  names: >
    a, b, c
- 
  undefined: null
  title: Another title
```

Also notice the single quotes added to the second item.  
The last item's names field is supposed to be empty so this output is correct.

This is the related blueprint:

```yaml
      credits:
        label: Credits
        type: structure
        fields:
          title:
            label: Title
            type: text
            width: 1/3
          names:
            label: Names
            type: text
            width: 2/3
```
