### ISSUE TITLE
Using blueprint field definitions in the registry?

### ISSUE THREAD

**Issue by samnabi** [getkirby/kirby#474]
It appears that the extension registry doesn't support blueprints that use [field definitions](https://getkirby.com/docs/panel/blueprints/global-field-definitions).

This is my file structure:

```
plugins/
  test/
    test.php
    blueprints/
      default.yml
      fields/
        test.yml
```

```php
# plugins/test/test.php

$kirby->set('blueprint', 'default', __DIR__.'/blueprints/default.yml');
```

```yml
# plugins/test/blueprints/default.yml

title: Page
pages: true
files: true
fields:
  title: test
```

```yml
# plugins/test/blueprints/fields/test.yml

label: Test title
type:  text
help: This is the blueprint from the plugin
```

The Panel gives me the following error message:

```
Panel Error:

Error without a useful message :(

It happened here:
File: /panel/app/src/panel/models/page/blueprint.php
Line: 85

Find more info on: getkirby.com 
```
