### ISSUE TITLE
[Panel] Columns and fluid gutters

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#486]
While playing around with blueprints I ended up with the following column setup:

```yaml
tabs:
  pages:
    label: Projects
    icon: page
    columns:
      - 1/1: drafts
      - 1/1: public
      - 1/1: unlisted
```

This resulted in 3 full-width "columns", one beneath the other. Due to the dynamic grid gabs in the CSS this resulted in growing whitespace between the sections depending on the content height (`grid-gab: 5%`). TIt looks especially weird when switching between pages because the spacing is never the same.

![bildschirmfoto am 2018-05-31 um 15 44 46-fullpage](https://user-images.githubusercontent.com/25466/40785711-95ef6f28-64e9-11e8-8ed1-76b6c0af4c11.png)

Of course, I should have set up my columns like this:

```yaml
tabs:
  pages:
    label: Projects
    icon: page
    columns:
      - 1/1: drafts, public, unlisted
```

But I can think of layout like this that might be more reasonable depending on the site's needs:

```yaml
tabs:
  pages:
    label: Projects
    icon: page
    columns:
      - 1/3: nav1
      - 2/3: list1
      - 1/3: nav2
      - 2/3: list2
```

My guess is that the grid gab was specified with horizontal spacing in mind. 
I'm not sure if this can be solved in an acceptable way (maybe creating a new section as soon as columns added up to full width), but if the grid layout stays as is, it would be good to document the mentioned behaviour so people know why the gab is growing.
