### ISSUE TITLE
[Panel] pages section: feature to disable page creation when "templates" is set

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#500]
It seems like the only way of removing the `(+) Add` button is to not set the "templates" option. However there are occasions where you want to display a certain page without giving the user the option to add another one. 

E.g.: I was trying to create a single large button for the homepage in my site.yml:

```yml
homepage:
  type: pages
  headline: Homepage
  layout: cards
  templates: home
```

The user should not be able to add a second "homepage". The Journal mentions that omitting the `create` option disables the add button, but the `create` option doesn't seem to exist anymore. 

## what I've tried
```yml
homepage:
  type: pages
  headline: Homepage
  layout: cards
  #templates: home
  query: site.find("home")
```
But I think `query` was removed because of the logic problems it created. 

## what I would like
if `create` was scrapped, maybe replace it with the feature of having `create: false` to explicitly disable page creation.
