### ISSUE TITLE
[Panel] Allow optgroup

### ISSUE THREAD

**Issue by lukaskleinschmidt** [getkirby/kirby#508]
I have currently some page sections and there are more to come.
It would be nice to be able to group these templates.

Of course this might also be handy in some situations for the select field in general.

```yml
sections:
  type: pages
  parent: page.find("section")
  headline: Sections
  layout: list
  templates:
    Header:
      - section-a
      - section-b
    Content:
      - section-c
      - section-d
    Media:
      - section-e
      - …
```
