### ISSUE TITLE
[Panel] Improve sorting for a high number of pages

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/kirby#528]
Looking at a „pages“ section, I wish I had the ability to sort / drag and drop subpages across the „pagination divide“. 

A possible solution could be adding the functionality to change the number of entries displayed for Drafts/Public/Unlisted.

**Comment by distantnative** [comment]
> A possible solution could be adding the functionality to change the number of entries displayed for Drafts/Public/Unlisted.

You can change the number of pages displayed per "pagination page" by setting the `limit` option in the blueprint part for that section, e.g.

```
kitchensink:
    headline: Examples
    type: pages
    status: listed
    limit: 99
```

Does that solve your issue?
