### ISSUE TITLE
Consistent language codes for panel translations

### ISSUE THREAD

**Issue by olach** [getkirby/kirby#534]
When working on a multi language site, I encountered an issue with the panel translations. The language codes are inconsistent. Some uses the short language code and some uses the longer language code.

This means I have to use different formats when translating form fields in blueprints.

I.e, for swedish I have to use the longer language code:

```yaml
fields:
  street:
    label:
      de: Straße
      en: Street
      sv_SE: Gata
```

My suggestion would be to always use the longer language code to be consistent and future proof if more languages is added.

Another suggestion would then be to specify a default fallback for every short language code for ease of use. I.e. `en` would fallback to `en_US` and `de` would fallback to `de_DE`.
