### ISSUE TITLE
[Panel] Structure field: before and after for table cells

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#545]
The structure field table layout looks great already, but as of now (when having multiple fields, especially number fields) one can not distinguish what a value in a certain table column stands for without opening it.

Since it's about sizes in this example, one could guess that all three columns stand for dimensions:
![structure-fields_now](https://user-images.githubusercontent.com/2584674/42192111-ff60581e-7e66-11e8-8d06-b16c28d6b26a.png)

But actually one is the price :smile:

![bildschirmfoto von 2018-07-03 01-42-31](https://user-images.githubusercontent.com/2584674/42192896-ee84adba-7e6b-11e8-95de-653df811fa48.png)

---

In Kirby 2 there was a table headline with the field labels. Thereby it was possible (but not always optimal with a lot of entries) to see what each column contained.

**So propably you should think about adding back a table head**

But at least (and maybe also if a table head returns) I feel you should display the **before** and **after** options in the table overview, too:

![structure-fields](https://user-images.githubusercontent.com/2584674/42192142-53e52d6a-7e67-11e8-8af2-82520e4683e3.jpg)

Optionally, the value could be simply aligned by the existence of before and after options:
- **nothing / before only** = align left (default)
- **after only** = align right
- **before & after** = align center

**Comment by bastianallgeier** [comment]
That's quite nice! I was thinking about an additional columns option for the structure field, which would be optional and could look like this: 

```
columns: 
  title: text
  size: 
    type: text
    align: center
  width: 
    type: number
    after: cm
  height: 
    type: number
    after: cm
  price: 
    type: number
    after: €
  articleId: 
    hide: true
```  
 
That could give us a couple more options later, like hiding columns, or adding links. etc. But I really like the simplicity of your solution.

**Comment by jenstornell** [comment]
@bastianallgeier What about `before` as well? Common in CSS. Could be useful for things like `$20`.

**Comment by bastianallgeier** [comment]
Yes, I was just recreating @REHvision's example. We have before and after in most of the form fields anyway already, so it would make sense to keep it consistent. 

There could be more stuff like: 

```
columns: 
  title: 
    width: 1/2
    type: link
    url: "https://somethingsomething.com/{{ item.articleId }}"
```

Maybe even formulas at some point: 

```
columns: 
  title: 
    type: text
  price: 
    type: number
  vat: 
    type: number
  total: 
    type: formula
    formula: item.price + item.vat
```

But I'm just dreaming here :)
