### ISSUE TITLE
[Panel] Date field: allow other field's value as min or max

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#555]
```
from:
  label: Start
  type: date
to:
  label: End
  type: date
  min: "{{page.from}}"
```
