### ISSUE TITLE
How can I retrieve the relative URL of an image within a Structure field?

### ISSUE THREAD

**Issue by Splendorr** [getkirby/kirby#557]
Hey there! I love Kirby, and am on my second project. For some reason, this is really perplexing me, and I've scoured the documentation to no avail.

I have the following Structure field in the Home blueprint, which I am able to access from the page.

```
slides:
    label: Slides
    type: structure
    entry:
      {{mobileImage}}<br />
      {{description}}
    fields:
      mobileImage:
        label: Mobile Image
        type: image
      description:
        label: Description Text
        type: textarea
```

And the following code, to render each of the Slides.

```
<?php foreach($page->slides()->toStructure() as $slide): ?>
  <div class="p-slide">
    <img src="content/home/<?= $slide->mobileImage()->html() ?>" alt=""/>
    <?= $slide->description()->html() ?>
  </div>
<?php endforeach ?>
```
The description comes out fine. And as you can see, I've gotten the image to render by adding "content/home/" before rendering the location of mobileImage() as html. But I shouldn't have to do that, right?

I've tried every other way I can find to just render an html tag that links properly to the relative location of this image. The images are just in /content/home/, but I can't seem to render anything except the file name. What is the sensible way to render an image from within a toStructure() call? Am I doing something ridiculous?

Thank you for your help!
