### ISSUE TITLE
[Panel] Templates of Kitchensink-Pages can only be changed between `form` and `sandbox`

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#568]
When I try to change the template of a kitchensink-page in the starterkit it only allows me to set either `Form Demo` or `Sandbox` which equals the allowed templates set for the Playground (but not the Kitchensink) section..

From `site.yml`:

```yaml
  kitchensink:
    headline: Examples
    type: pages
    status: listed
    item:
      image: false
      info: "{{ page.template }}"

  playground:
    headline: Playground
    type: pages
    status: unlisted
    templates:
      - form
      - sandbox
```
