### ISSUE TITLE
Date filtering bug

### ISSUE THREAD

**Issue by WeTurkstra** [getkirby/kirby#571]
On the docs there is a page about filtering.

I was using the part about date filtering 
[https://getkirby.com/docs/cookbook/filtering#fun-with-filtering-by-date](https://getkirby.com/docs/cookbook/filtering#fun-with-filtering-by-date)

When using this snippet: 
```
$collection = page('blog')->children()->visible()->filterBy('date', '>', strtotime('2015-01-01'))->filterBy('date', '<', strtotime('2015-12-31'))
```

i changed the snippet to this:
```
->filterBy('end_date', '>', time())->filterBy('start_date', '<', time());
```

I was getting the following error: 
Object of class Field could not be converted to int

My fileds are defined like this: 
```
start_date:
    label: Start datum (dd-mm-jjjj)
    type: date
    format: DD-MM-YYYY
  end_date:
    label: Eind datum (dd-mm-jjjj)
    type: date
    format: DD-MM-YYYY

```

Am i doing something wrong?
