### ISSUE TITLE
[Cms] section queries not working

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#593]
Following the docs over at notion (Kirby 3 Docs / Sections / pages) I can't seem to get the queries working. 

```yaml 
title: Blog

sections:

  drafts:
    headline: Drafts
    type: pages
    query: page.children.invisible
    create: article

  published:
    headline: Published Articles
    type: pages
    query: page.children.visible
````

Both sections list all pages, no matter what the status is. I have tried adding filters and stuff, but whatever i try, it has no effect. Only explicitly specifying templates changes the output.

I'm using the beta 1 plainkit btw.

**Comment by bastianallgeier** [comment]
The docs are not up to date. The same as with the files docs :( I missed those when I rewrote the docs. 

We removed the query to avoid too many edge cases. But you can specify the page status instead:

```yaml
title: Blog

sections:

  drafts:
    headline: Drafts
    type: pages
    status: draft
    create: article

  published:
    headline: Published Articles
    type: pages
    status: listed
```
