### ISSUE TITLE
Site Options: Indirect modification of overloaded property Collection::$title has no effect

### ISSUE THREAD

**Issue by ptbobolakis** [getkirby/kirby#595]
Hey guys,

I'm getting started with kirby right now. I searched for the issue on big G but I couldn't find anything.
The Prob:

Everything works just fine (as far as I know), except when I click on Site Options I get an error screen with the following content.

Whoops\Exception\ErrorException: Indirect modification of overloaded property Collection::$title has no effect in file /var/www/html/web/panel/app/forms/pages/edit.php on line 21
Stack trace:
  1. Whoops\Exception\ErrorException-&gt;() /var/www/html/web/panel/app/forms/pages/edit.php:21
  2. Whoops\Run-&gt;handleError() /var/www/html/web/panel/app/forms/pages/edit.php:21
  3. Kirby\Panel-&gt;{closure}() /var/www/html/web/kirby/vendor/getkirby/toolkit/helpers.php:280
  4. call() /var/www/html/web/panel/app/src/panel.php:330
  5. Kirby\Panel-&gt;form() /var/www/html/web/panel/app/src/panel/models/site.php:64
  6. Kirby\Panel\Models\Site-&gt;form() /var/www/html/web/panel/app/controllers/options.php:30
  7. OptionsController-&gt;index() /var/www/html/web/kirby/vendor/getkirby/toolkit/helpers.php:280
  8. call() /var/www/html/web/panel/app/src/panel.php:447
  9. Kirby\Panel-&gt;response() /var/www/html/web/panel/app/src/panel.php:407
 10. Kirby\Panel-&gt;launch() /var/www/html/web/panel/index.php:44

Any idea where I might have screwed up? (see this img for more info: https://cloudup.com/ca3ejKmo9Fy)

Thanks in advance!

**Comment by lukasbestle** [comment]
Could you please try that again with Kirby 2.5.4 (which was released today)?

**Comment by ptbobolakis** [comment]
Hey @lukasbestle,

thanks for taking the time. Just updated, but the issue persists.
Check out the img again: https://cloudup.com/cVnJ7ViH96A

Btw.: I'm using Kirby in a Docker container. But I don't think it's a problem, right?

**Comment by texnixe** [comment]
See here: https://forum.getkirby.com/t/site-options-indirect-modification-of-overloaded-property-collection-title-has-no-effect/8155/4?u=texnixe

**Comment by texnixe** [comment]
While we can remove the title field from standard page blueprints, removing the title field from the site.yml blueprint causes this issue.

**Comment by ptbobolakis** [comment]
@lukasbestle @texnixe 
Guys, thanks a million & sorry.

My Issue was caused because I was missing the following field in two blueprints.

```
fields:
  title:
    label: Title
    type:  text
```


Btw. I'm using the builder and thats my Blueprint for default.yml:
```
title: Page
files: true

fields:
  title:
    label: Title
    type:  text
  builder:
    label: Sections
    type: builder
    fieldsets:
      slideshow:
        label: Slideshow
        snippet: modules/slideshow/slideshow
        fields:
          pictures:
            label: Slideshow
            type: gallery
          headline:
            label: Headline Text
            type: text
          copy:
            label: text
            type: textarea
      bodytext:
        label: Body Text
        snippet: components/bodytext/bodytext
        fields:
          copy:
            label: text
            type: textarea
      stage:
        label: Stage
        snippet: modules/stage/stage
        fields:
          video:
            label: Video
            type: select
            options: videos
          picture:
            label: Background Image
            type: image
          headline:
            label: Headline Text
            type: text
          copy:
            label: text
            type: textarea
      quote:
        label: Quote
        snippet: components/quote/quote
        fields:
          text:
            label: Quote Text
            type: textarea
          citation:
            label: Citation
            type: text
```
Is it OK like this?

**Comment by texnixe** [comment]
Yes, looks ok, each blueprint has to have a title at the top (the title field in the `fields` section, however, is not mandatory)

**Comment by ptbobolakis** [comment]
Nice, thanky @texnixe and sorry again. 
Btw. the error occurs when 

```
title: Page
files: true

fields:
  title:              <|
    label: Title      <| these lines are missing
    type:  text       <|
  builder:
    label: Sections
    type: builder
    fieldsets:
      slideshow:
```
