### ISSUE TITLE
[Panel] Use queries in other parts of blueprint

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#600]
E.g. as defaults, in help etc.

```
artist:
  label: Artist
  type: select
  options: query
  query: site.find('artists').children
copyright:
  label: Copyright
  type: text
  default: '{{ site.find('artists').find(page.artist).name }}'
```

**Comment by nilshoerrmann** [comment]
This would be very, very helpful and powerful. I actually thought this was already possible and was a bit disappointed to find out it wasn't. You've been setting the bar high ;)

**Comment by bastianallgeier** [comment]
It's possible in section headlines so far, but we should definitely extend this.

**Comment by tillprochaska** [comment]
Users might expect that those values update when changing the fields they depend on. E. g. in the following example, when changing the value of the select field, it might be confusing if the placeholder text of the copyright field does not change and I assume that implementing this in a way where queries would update in place would be non-trivial.

That said, I still think this feature/enhancement would be helpful, but there should probably a clear note on the limitations of the feature in the docs. :)

```
artist:
  label: Artist
  type: select
  options: query
  query: site.find('artists').children
copyright:
  label: Copyright
  type: text
  placeholder: '{{ site.find('artists').find(page.artist).name }}'
```
