### ISSUE TITLE
[Panel] - Bug with date field when included in a structure field

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#6282]
## Description
I found a bug with the date field when it’s included in a structure field.
If I choose a date in the calendar, the right date is displayed in the date field but when I click on the “tick” icon to close the sliding sidebar of the structure field then the date value is changed.

Looks like it only happens when the display format is set.

**Expected behavior**  
We keep the same date value after clicking on the "tick" icon to close the sliding sidebar of the structure field.

**Screenshots**  
I did two screencasts to illustrate:
https://github.com/getkirby/kirby/assets/664089/beb95c5c-1ef8-4f97-a4c5-c820c9a1f806
https://github.com/getkirby/kirby/assets/664089/55157b3c-58c4-4de3-9c6b-1adf8cbb7086

## To reproduce

```
f_primary_approval:
            label: Primary approval
            type: structure
            fields:
              f_s_title:
                label: Title
                type: text
              f_s_files:
                label: Egnyte files
                type: structure
                fields:
                  f_s_s_last_update_date:
                    label: Last update
                    type: date
                    display: MM/DD/YYYY
                    help: Click on the calendar icon
```

## Your setup
**Kirby Version**  
4.1.0

**PHP Version**  
8.3.3

**Your system (please complete the following information)**
 - Device: PC
 - OS: Linux
 - Browser: Firefox

**Comment by distantnative** [comment]
Also getting weird dates when removing one nesting level with just

```yml
f_s_files:
  label: Egnyte files
  type: structure
  fields:
    f_s_s_last_update_date:
      label: Last update
      type: date
      display: MM/DD/YYYY
      help: Click on the calendar icon
  ```
