### ISSUE TITLE
[Panel] Line field is not visible in Chrome & Safari

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#636]
fix it like so:

```css
.kirby-line-field {
 ...
  width: auto;
}
```
