### ISSUE TITLE
Date field behaves weird when "display" MM/YYYY is used

### ISSUE THREAD

**Issue by mit-stauffer** [getkirby/kirby#6408]
## Description
When displaying a date field in the panel in the format MM/YYYY, the date input jumps to 08/2025 after saving, no matter what I selected. No other options are used (except width). Tried it in the 4.2 startkit

```
datetest:
   type: date
   display: MM/YYYY
   width: 1/4
```

The content .txt files saves the wrong date:
`Datetest: 2025-08-01`

**Comment by jhogervorst** [comment]
I'm having the same issue. I'm using Kirby 4.3.0 with the following field configuration:

```yaml
published:
  label: Maand van uitgave
  type: date
  required: true
  display: MM-YYYY
  calendar: false
  step: month
```

The issue occurs both in the page creation dialog, as well as in the regular page editor in the panel. Here's a short recording; you can see that as soon as I click outside (blur) the date input field, the typed value `01-2024` is changed to `08-2025`:

![CleanShot 2024-08-06 at 12 54 05](https://github.com/user-attachments/assets/e78f6ab3-b2c4-47f5-8a7f-a920e18cb2a7)

I've noticed that as a workaround, you can type the full date (`DD-MM-YYYY`) instead of only the month (`MM-YYYY`), in which case it works correctly:

![CleanShot 2024-08-06 at 12 56 41](https://github.com/user-attachments/assets/a8984a63-b002-4da0-8ea8-5cc8b9fa514e)
