### ISSUE TITLE
Language permissions not working

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [getkirby/kirby#6497]
## Description
According to the [documentation](https://getkirby.com/docs/guide/users/permissions#role-based-permissions-in-user-blueprints), I can disable the creating and deletion of new languages:

```yml
# site/blueprints/users/editor.yml
title: Editor
permissions:
  languages:
    create: false
    delete: false
```

These permission options are available in the `window.panel.permissions.languages` object, but it seems that they are not implemented in the [`LanguagesView.vue`](https://github.com/getkirby/kirby/blob/main/panel/src/components/Views/Languages/LanguagesView.vue) (?)

## To reproduce
In a plainkit installation, add the user blueprint mentioned above. Also set `'languages' => true` in `site/config/config.php`

## Your setup
**Kirby Version**  
4.3

**Your system (please complete the following information)**
Chrome 126 on macOS 14.5

**Comment by afbora** [comment]
I can able to reproduce the issue. As workaround you can disable access to languages view:

````yaml
permissions:
  access:
    languages: false
````
