### ISSUE TITLE
Force create thumbnail with the source image dimensions

### ISSUE THREAD

**Issue by maximelebreton** [getkirby/kirby#656]
Hello!

I use `thumb` function to create srcset images, with optimizations like quality, remove exif etc...

But when the `thumb` size is `>=` of the `source` size, Kirby returns the `source` file instead of a `thumb`,
so I don't have quality and remove exifs optimizations.

How can I manage this case?

Thanks.

behaviour expected:
````yaml
# passing this:
  source: image.jpg
  width: 800

# with these thumb sizes
  small: 300
  medium: 600
  large: 900

# should returns this
  small: thumb-300.jpg
  medium: thumb-600.jpg
  large: thumb-800.jpg # --> instead of image.jpg
  


````
