### ISSUE TITLE
[Panel] Don't make the info field a quote

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#664]
The Kirby 2 info field looks really nice. We can have whatever info we want here, controlled by HTML:

![image](https://user-images.githubusercontent.com/927011/42761912-2df1e7f8-890f-11e8-8fd5-0936716c7906.png)

The new Kirby 3 info field looks like a quote. I understand the reason for it. It's short info to the user.

![image](https://user-images.githubusercontent.com/927011/42761990-63bcfcd8-890f-11e8-9064-19913fed870d.png)

The possibilities to the new quote version is much more limited. Things that we did not need plugins for before, will need plugin now, or at least additional css to strip the quote look away.

So my vote is, keep it simple.

**Comment by wottpal** [comment]
Maybe an option like `plain: true` would be nice. But actually I enjoy the new look of the `info`-field because they seek more attention and can't be so easily ignored by the editor like in the past 😅

Oh yes and 👍 for list-support

**Comment by jenstornell** [comment]
**This is always possible (without a plugin) but really ugly:**

```yaml
      new_info:
        label: Info
        type: info
        text: >
          <style>
          .kirby-box[data-theme=info] {
            background: none;
            border: none !important;
            padding: 0 !important;
          }
          </style>
          This is an info box
```

@wottpal Yes, a list support would be much better than nothing. 😄 Then we could express ourselves a bit more.
