### ISSUE TITLE
[Panel] Add `icon-action` in blueprints

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#674]
I just discovered the icon of `url`-fields is linked to the according page. It would be nice if an icon-action like this could be added in the blueprints as well for e.g. Twitter or Instagram. Just like:

```yaml
twitter:
   label: Twitter Account
   type: text
   icon: twitter
   iconURL: "twitter.com/{{twitter}}"
```

Where `{{twitter}}` means the content of the `twitter`-field.
