### ISSUE TITLE
[Panel] Structure required not yet implemented or not working

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#686]
I use a structure field and added required to a select field. Still I can save it without a value and I don't get a warning about it.

```yaml
day:
  label: Dag
  type: select
  default: mandag
  required: true
  options:
    mandag: Måndag
    tisdag: Tisdag
    onsdag: Onsdag
    torsdag: Torsdag
    fredag: Fredag
    lordag: Lördag
    sondag: Söndag
  width: 1/3
```
