### ISSUE TITLE
[Panel] Tabs disapear

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#691]
When I added a new tab, every not active tab became hidden.

**I found this css:**

```css
.kirby-header-tabs[data-compact] .kirby-tab-button:not([aria-current]) .kirby-button-text {
    display: none;
}
```

I use 5 tabs when this happends, no icons.

## Update

In the first one it's the behaviour of the panel:

![image](https://user-images.githubusercontent.com/927011/42879901-92889f48-8a92-11e8-99c1-cb050ef21409.png)

Below is when I removed the display: none style:

![image](https://user-images.githubusercontent.com/927011/42879887-839db824-8a92-11e8-82fc-3fd3b8338d07.png)

I prefer the last one where I can see what I'm doing.
