### ISSUE TITLE
[Blueprint] Make `site.index()` an option for `parent`

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#706]
Then these few lines in the blueprint could easily replace the former [drafts-widget](https://github.com/Thiousi/kirby-drafts-widget). Maybe a `not` or `exclude` option would be cool as well.

```yaml
drafts:
    headline: All Drafts
    type: pages
    status: draft
    parent: site.index()
```
