### ISSUE TITLE
[Blueprint] Add validation for tags do disallow non-queried values

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#714]
In the following example from the starterkit (which is 🔥 by the way) it would be nice to have a way to restrict the possible tags to the queried ones. Otherwise it results in a form-error. Something like `restrict: true`-

```yml
tags:
    label: Tags
    type: tags
    options: query
    query:
       fetch: site.tags.toStructure.sortBy("name", "asc")
       text: "{{ structureItem.name }}"
       value: "{{ structureItem.value }}"
```
