### ISSUE TITLE
[Blueprint] `index` option for tags still available?

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#715]
I guess the syntax has changed from K2?

<img width="626" alt="bildschirmfoto 2018-07-22 um 16 39 45" src="https://user-images.githubusercontent.com/3930150/43046750-ddc006b6-8dcd-11e8-9088-4ad47fe1047b.png">

**Comment by bastianallgeier** [comment]
No! The index option is gone in favor of the more consistent `options` option.

**Comment by wottpal** [comment]
Could you help me replicating `index: siblings` behavior with the `options` parameter?

**Comment by bastianallgeier** [comment]
Yes, sure! 

```
options: query
query: page.siblings.pluck("tags", ",", true)
```

Might indeed be good to have a shortcut for this though :)

**Comment by wottpal** [comment]
Okay I'm actually using the `tags`-field inside a file-template. Life is so complicated 😞

I tried this without luck:

```yaml
  location:
    label: Standort(e)
    type: tags
    width: 1/2
    required: true
    options: query
      query: page.files().template(file.template()).pluck("location", ",", true)
```

**Comment by wottpal** [comment]
Oh files have siblings too 🎊

```yaml
    query: file.siblings.pluck("location", ",", true)
```

**Comment by bastianallgeier** [comment]
Yes, but it would indeed be cool to have something like `page.templateSiblings` and `file.templateSiblings`

**Comment by wottpal** [comment]
Hey @bastianallgeier, some nightlies ago this stopped working? Any idea?

```yaml
  location:
    type: tags
    options: query
    query: file.siblings.pluck("location", ",", true)
```

<img width="373" alt="bildschirmfoto 2018-08-10 um 16 34 00" src="https://user-images.githubusercontent.com/3930150/43963718-63c99e38-9cbb-11e8-9971-bf6fdd85ad71.png">
