### ISSUE TITLE
[Panel] Page Selector field

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#72]

**Comment by bnomei** [comment]
any news on this one? would love to have it final release.

current workaround
```
mypagesfield:
  type: select
  options: query
  query:
    fetch: site.index.visible.sortBy('id')
    text: "{{ page.title }}"
    value: "{{ page.id }}" # or autoid
```
