### ISSUE TITLE
[Panel] Uploaded PDF-files are not shown in `files`-section

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#726]
Upload works (they are in the `content`-folder) but they are not displayed in the panel.

**Comment by bastianallgeier** [comment]
Works for me. What is the blueprint setup for the files section?

**Comment by wottpal** [comment]
This is the whole blueprint. It's about the `anfahrtsskizze` section.

```yaml
title: Filiale
icon: 🏨

options:
  changeSlug: true
  changeTemplate: false
  changeStatus: true
  changeTitle: true
  delete: true
  preview: false


tabs:

  sprechzeiten:
    label: Sprechzeiten
    icon: page
    columns:
      - 1/1: sprechzeiten

  kontakt:
    label: Kontakt
    icon: page
    columns:
      - 1/1: kontakt
      - 1/1: anfahrtsskizze


sections:

  sprechzeiten:
    extends: sections/sprechzeiten

  kontakt:
    type: fields
    fields:
      address:
        type: text
        label: Adresse
        required: true
        help: z.B. Engelplatz 8, 07743 Jena
      email:
        type: email
        label: E-Mail
        required: true
        placeholder: false
      phone:
        type: tel
        label: Telefon
        required: true
        width: 1/2
      fax:
        type: tel
        label: Fax
        icon: draft
        width: 1/2

  anfahrtsskizze:
    type: files
    max: 1
    headline: Anfahrtsskizze
    template: anfahrtsskizze
```

And this the files-template is basically empty. I had `accept: mime: application/pdf` inside and removed it to test if that's where the error comes from.
