### ISSUE TITLE
[Panel] Better align fields without label

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#732]
<img width="585" alt="screen shot 2018-07-23 at 10 24 07" src="https://user-images.githubusercontent.com/3930150/43065602-9fcfcf2c-8e62-11e8-95a9-9a6407123fe9.png">

```yaml
type: structure
fields:

  days:
    label: Tag(e)
    type: text
    required: true
    placeholder: Montag - Freitag
    width: 1/2

  vereinbarung:
    test: tabs
    type: toggle
    text: Nur nach Vereinbarung
    width: 1/2
```
