### ISSUE TITLE
[Panel] Date field breaks in structure field when required: true

### ISSUE THREAD

**Issue by ralfgoeke** [getkirby/kirby#753]
![2018-07-25 07 49 40](https://user-images.githubusercontent.com/6228942/43181925-b54d0e9a-8fdf-11e8-8538-fa4a6f2901dd.gif)

works:

```yaml
date:
  label: Datum
  type: date
```

does not work:

```yaml
date:
  label: Datum
  type: date
  required: true
```

**Comment by bastianallgeier** [comment]
Hm, I can't reproduce this in the latest nightly build. I guess one of our recent changes fixed it.

**Comment by ralfgoeke** [comment]
Just downloaded the brand new nightly and double checked. It's still broken.

Here's a drop-in blueprint snippet to test:

```yaml
# pages/home.yml
title: Startseite

sections:
  datebug:
    type: fields
    fields:
      demo:
        label: 🐞
        type: structure
        fields:
          # this works
          date:
            label: Datum
            type: date
          # this does not work
          datereq:
            label: Datum
            type: date
            # required breaks field
            required: true
```
