### ISSUE TITLE
[Panel] Layout-Option without text (image-only)

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#759]
In this example I would like to only show the image, because neither the filename nor other information about the image are necessary for the editor. Of course the options-button needs to be visible in fron of the image then.

<img width="614" alt="screen shot 2018-07-26 at 11 51 04" src="https://user-images.githubusercontent.com/3930150/43255507-4e8abafe-90ca-11e8-8b86-6f8ed6046fde.png">

🤷‍♂️

```
  header:
    type: files
    layout: cards
    item:
      text: false
```
