### ISSUE TITLE
[Panel] Pages-section in site.yml doesn't add new pages to assigned parent

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#774]
As the title states, if I add a pages section in site.yml and assign it a parent page it
- shows all subpages of Blog correctly
- but adds new pages to Site instead of the Blog page

```
sections:
  articles:
    headline: Blog-Artikel
    type: pages
    parent: site.find("blog")
    sortBy: date desc
    status: all
    templates: article
```
Shouldn't new subpages get added to the respective parent instead of site?
