### ISSUE TITLE
devkit section files error

### ISSUE THREAD

**Issue by beebmx** [getkirby/kirby#787]
A fresh installation of `devkit` creates an error with the `files` section.

If the section `files` is renamed, the section works normal/without errors.

The blueprint is the default:
```yml
title: Default Page

columns:
  - 1/3: pages, files
  - 2/3: content

sections:
  pages:
    headline: Pages
    type: pages
  files:
    headline: Files
    type: files
  content:
    type: fields
    fields:
      text:
        label: Text
        type: textarea
        size: large
```

<img width="1110" alt="2018-07-31 15 55 14" src="https://user-images.githubusercontent.com/2191576/43486797-595708f2-94da-11e8-8776-64dafd451172.png">
