### ISSUE TITLE
[Panel] section: files doesn't take the template value

### ISSUE THREAD

**Issue by beebmx** [getkirby/kirby#793]
Using the `beta-3` the section `type:files` doesn't take the options from the template.

Here is the blueprints:

```yml
title: Home

sections:
  files:
    headline: Files
    type: files
    template: cover
    layout: list
```
Template:
```yml
title: Cover

fields:
  alt:
    label: Alt Text
    type: text
```

The result is: 
<img width="686" alt="2018-08-01 19 06 43" src="https://user-images.githubusercontent.com/2191576/43555163-37ba706e-95be-11e8-8aeb-04f7c3bd6925.png">

If the template line is removed, the result is:
<img width="668" alt="2018-08-01 19 09 15" src="https://user-images.githubusercontent.com/2191576/43555213-7af7ba12-95be-11e8-98d4-df5661df9fc8.png">

**Comment by distantnative** [comment]
I think that happens because those files do not have the template `cover`.

```
sections:
  files:
    headline: Files
    type: files
    template: cover
    layout: list
```

That section setting only lists files with the `cover` template.
