### ISSUE TITLE
[Panel] Allow simple templates in e.g. `label` and `help` too

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#796]
For example:

```yaml
  jobs:
    type: fields
    fields:
      jobs:
        label: Stellenangebote in {{ page.title }}
        type: structure
        ...
```
