### ISSUE TITLE
[Cms] `toString()` throws an error on `tags`-fields inside a structure

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#821]
Add the following fields in the blueprints, then add some content:

```yml
  outerTags:
    type: tags

  structure:
    type: structure
    fields:
      innerTags:
        type: tags
```

This throws no error and works as expectet (outputs the tags):

```php
<?= $page->outerTags() ?>
```

This throws the error `Method Kirby\Cms\Field::__toString() must not throw an exception, caught Whoops\Exception\ErrorException: Array to string conversion`:

```php
<?php foreach($page->structure()->toStructure() as $item): ?>
  <?= $item->innerTags() ?>
<?php endforeach ?>
```
