### ISSUE TITLE
[Panel] Allow HTML in field help

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/kirby#869]
In Kirby 2 it’s possible to use HTML in the field `help`. I often add line breaks, bold and italic or even links to help the user understand what they can do with the field.

Can you bring this back in Kirby 3? Or maybe even markdown and kirbytext support like in the `info` field?

```
text:
  label: Text
  type: textarea
  help: >
    See the <a href="https://getkirby.com/docs/content/text">documentation</a> on how to format text.
```
