### ISSUE TITLE
[Panel] New Page is created as `unlisted` and shows the wrong template

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#879]
I have an issue with the latest nightly. Unfortunately I couldn't reproduce it with the Starterkit (even with my exact same blueprints 😕), maybe somebody has an idea: When I create a new page in a page-section defined like

```yml
  pages:
    status: all
    templates: filiale
    type: pages
```

the new page is (1) created as *unlisted*, (2) does not show up in the page-section but is created in `_drafts`, and (3) show the *default* template in the Panel instead of the defined one *filiale*.

I did not set up any languages if that helps.
