### ISSUE TITLE
[Panel] Default value in structure field reorders YAML output

### ISSUE THREAD

**Issue by frttbrg** [getkirby/kirby#915]
I have a simple structure field with three elements:
```
label: Creator
type: structure
fields:
  lastname:
    label: Last Name
    type: text
  firstname:
    label: First Name
    type: text
  role:
    label: Role
    type: select
    options: 
      Author: Author
      Editor: Editor


# Output in content file
Creator: 

- 
  lastname: …
  firstname: …
  role: Author
```

But when I add a default value to just one of the three fields, the output gets reordered and the field with a default moves up to the top. That’s also the case by two fields with default values.
```
label: Creator
type: structure
fields:
  lastname:
    label: Last Name
    type: text
  firstname:
    label: First Name
    type: text
  role:
    label: Role
    type: select
    default: Author
    options: 
      Author: Author
      Editor: Editor


# Output in content file
Creator: 

- 
  role: Author
  lastname: …
  firstname: …
  
```
Of course I can change the field order in the blueprint at any time and by doing this the content file values won’t be in the same order as shown in the panel. But maybe the behavior with single `default` values is not in intended.
