### ISSUE TITLE
Panel access false together with other permissions prevents login

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#939]
With. a user blueprint like this

```
title: Visitor
permissions:
  access:
    panel: false
    users: true
    site: true
```

it is not possible to login anymore. While such a setting obviously doesn't make sense, maybe Kirby should nevertheless just ignore the other settings instead of preventing login for everyone?

This works fine, though:

```
title: Visitor
permissions:
  access:
    panel: false
```
