### ISSUE TITLE
[Panel] Date Field in a structure throws error

### ISSUE THREAD

**Issue by gerricom** [getkirby/kirby#950]
This is (to me) a kind of crazy bug. Steps to reproduce:

Get the latest starterkit. Open the blueprint `form.yml`. Add a date field as first field to the structure at the end of the file, like this:

```
  structure:
    label: Structure
    type: structure
    fields:
      date:
        label: Date
        type: date
        width: 1/4
      title:
        label: Title
        type: text
        width: 3/4
      icon:[...]
```

Go, visit the panel and add a new entry. You get: `this.$refs.day is undefined`. You also get this error, if you click on the date column you entered.
