### ISSUE TITLE
[Panel] content removed from fields after saving

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#960]
When fill in fields with content then save the data, some fields loose their content.

**Comment by bastianallgeier** [comment]
Could you describe this a little more? Which type of fields. What kind of blueprint setup do you have?

**Comment by jenstornell** [comment]
Some info from Slack:

>jenstornell [8 days ago]
I think I've had that issue as well. I thought I missed to fill in fields but probably not.

>hectorromo [8 days ago]
I’m having a similar issue when saving a draft with the files field. But when I change the page status to visible it works fine.

>flokuek [4 days ago]
I‘ve had the same issue a couple times running the latest beta on php 7.2

It does not narrow the problem down, but it contains a bit more info.

**Comment by vauvarin** [comment]
Which type of fields:
Text field, tags field, Textarea field, URL field ...

This is my blueprint:
[post.txt](https://github.com/k-next/kirby/files/2389668/post.txt)

if you want me to send all my website in a zip, just let me know

**Comment by bastianallgeier** [comment]
I have really no idea what the problem could be. @vauvarin the blueprint has still some old syntax, but that should not be the problem. Could you send me the zip. I think it will make it easier for me to debug this.

**Comment by vauvarin** [comment]
Hi Bastian, 

I'm sending my project The whale as a zip file with the WeTransfert service on mail@getkirby.com

In the panel:
login: mail@getkirby.com
password: bastian is back from holiday

You can for instance open an existing issue and add a post. Try to fill in the fields one by one then save or it's often happen when I fill in the two URL fields as the same time and save.

I'm here to answer your questions if you need it.

**Comment by bastianallgeier** [comment]
I tested a couple entries and it never happend to me once. Maybe it's Caddy or what kind of browser do you use?

**Comment by vauvarin** [comment]
I use Firefox Quantum v62.0, 64 bits on Linux (Ubuntu 18.04).
But it's not happen all the time, you need to make several tests

**Comment by jenstornell** [comment]
I used Chrome on Windows when it happend here.

**Comment by joernroeder** [comment]
happens to me too, here my blueprints, request and response

```yml
# news.yml

title: News
icon: 🗞

columns:
  - width: 1/4
    sections:
      date:
        type: fields
        fields:
          date:
            label: Date
            type: date

      images:
        extends: sections/images
        layout: list

  - width: 3/4
    sections:
      content:
        type: fields
        fields:
          content:
            type: textarea
            size: huge
          gallery:
            extends: fields/gallery
```

```yml
#sections/images

type: files
headline: Images
layout: cards
template: gallery
item:
  info: "{{ file.dimensions }}"
```

```yml
#fields/gallery

type: files
template: gallery
layout: cards
cover: true
```

1. upload an image
2. add image to fields field
3. click save sends the following:

```
curl 'http://localhost:5000/api/pages/schools+foo-news' -X PATCH -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:63.0) Gecko/20100101 Firefox/63.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: http://localhost:5000/panel/pages/schools+foo-news' -H 'x-requested-with: xmlhttprequest' -H 'content-type: application/json' -H 'origin: http://localhost:5000' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: kirby_session=bf70fd76ecd5462b57998163006cec0ff636bf26%2B1537482536.acfebabc5d5b7eb2ec7d.88784deb416d609fc7420916d83c630388e26c1405a39cef92da40b344da3e14' --data '{"title":"Foo NEws","content":"","gallery":[{"filename":"tesla-cat.jpg","id":"schools/foo-news/tesla-cat.jpg","link":"/pages/schools+foo-news/files/tesla-cat.jpg","type":"image","url":"http://localhost:5000/media/pages/schools/foo-news/tesla-cat.jpg","selected":true}],"date":""}'
```
![screen shot 2018-09-20 at 23 03 14](https://user-images.githubusercontent.com/270540/45846917-7e980180-bd29-11e8-81e7-5d8b7f2f93d8.PNG)

responds with:

![screen shot 2018-09-20 at 23 04 41](https://user-images.githubusercontent.com/270540/45846959-a0918400-bd29-11e8-9269-6daccc6f906d.PNG)
