### ISSUE TITLE
[Panel] Strange blueprint permission errors

### ISSUE THREAD

**Issue by johannschopplich** [getkirby/kirby#970]
When adding some permissions in the users' blueprint, the Panel throws this error: `The panel cannot connect to the API 😭 ` or prevents logging in all along.

This blueprint works:
```
title: Redakteur
extends: users/default

permissions:
  pages:
    sort: false
    delete: false
```

When adding just the line `changeURL: false` the user **cannot login anymore at all**.
