### ISSUE TITLE
[Panel] Suggestion filtering broken

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#975]
Take this field that let's the user select related projects:

```yaml
              related:
                label: Awarded Project
                type: tags
                options: query
                query:
                  fetch: site.find('projects').children
                  value: '{{page.uid}}'
                  text: '{{page.title}}'
```

The query fetches all projects with their UID and their title. This work perfectly as I can see all projects in the API response in the network panel. There is this entry for example:

```json
[
    {
        "text": "Lenticular Curtain",
        "value": "breathtaking"
    }
]
```

The interface doesn't find this project when typing in the tags field no matter which snippet I'm trying to find ("Len", "breath", "Curtain").

**Comment by bastianallgeier** [comment]
@nilshoerrmann Is "Lenticular Curtain" a draft?

**Comment by nilshoerrmann** [comment]
No, it's public.

**Comment by bastianallgeier** [comment]
Damn. It works here, if I add the project with the same title and uid. Would it be possible to get the rest of the blueprint. Maybe something interfers with another field.

**Comment by nilshoerrmann** [comment]
It's part of the project I shared with you two weeks ago. This should be the related blueprint:

```yaml
name: award
title: Award
tabs:
  content:
    label: Content
    icon: text
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              title:
                label: Title
                type:  text
              category:
                label: Category
                type: text
              other:
                label: Other
                type:  text
              url:
                label: External Link
                type: url
              related:
                label: Awarded Project
                type: multiselect
                options: query
                query:
                  fetch: site.find('projects').children
                  value: '{{page.uid}}'
                  text: '{{page.title}}'
      - width: 1/3
        sections:
          year:
            headline: Year
            type: fields
            fields:
              year:
                label: Year
                type: text
                validate:
                  minLength: 4
                  maxLength: 4
                  - num
```
