### ISSUE TITLE
[CMS] Structure field with default values writes to root of content file

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#991]
```yaml
fields:
  text:
    type: text
  builder:
    label: Builder
    type: structure
    fields:
      waffle:
        label: CSS Classes
        type: text
        default: 'bg-white push-0-of-12 col-12-of-12 sm-un-push col-sm-6-of-6'
      text:
        label: Text
        type: textarea
```

when using this structure in the panel a not defined field with the default value from the structure is created. maybe only if structure was added to the blueprint and content-file already existed – not sure.

```yaml
Text: some text
----
Waffle: bg-white push-0-of-12 col-12-of-12 sm-un-push col-sm-6-of-6
----
Builder:
# data of structure follows...
```
